****** Warning: The !! notation is really old and ugly, it should
not be used anymore. Please update your code and use the `create'
keyword.

Line 15 column 10 in BAD_CREATION1 (/home/persocad/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_creation1.e):
         !!aux;
         ^     
------
****** Warning: Added missing `default_create'. Actually, a creation list must
not be empty. You must have at least the `default_create' procedure inherited
from ANY. The `default_create' indicates that one can also create an object
with no creation procedure.

Line 6 column 1 in AUX_CREATION1 (/home/persocad/Workspace/Dev/Liberty/test/language/error_warning_msg/aux_creation1.e):
create {ANY}
^           
------
****** 2 warnings.
