****** Warning: Added missing "then" keyword.

Line 13 column 3 in BAD_IF1 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_if1.e):
    end
    ^  
------
****** 1 warning.
****** Error: "if" (or "elseif" as well) must be followed by a
BOOLEAN expression.

Line 12 column 3 in BAD_IF1 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_if1.e):
    if 1
    ^   
------
****** Fatal Error: The declaration type of this expression is
INTEGER_8 (this is not BOOLEAN).

Line 12 column 6 in BAD_IF1 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_if1.e):
    if 1
       ^
------
