****** Fatal Error: No more "expanded" keyword allowed here. The
obsolete "expanded FOO" notation is no longer accepted.

The source lines relevant to this message are the following:

Line 12 columns 30, 39 in BAD_WEAK_REFERENCE03 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_weak_reference03.e):
         bwr: WEAK_REFERENCE[expanded BAD_WEAK_REFERENCE03]
                             ^        ^                    
------
