****** Warning: Deleted optional "=".

Line 14 column 15 in BAD_CONSTANT10 (/home/doug/projects/eiffel/liberty-eiffel/git/liberty-eiffel/test/language/error_warning_msg/bad_constant10.e):
   f: INTEGER =
              ^
------
****** Fatal Error: Bad constant-attribute definition. The feature value must
be a manifest constant.

Line 15 column 7 in BAD_CONSTANT10 (/home/doug/projects/eiffel/liberty-eiffel/git/liberty-eiffel/test/language/error_warning_msg/bad_constant10.e):
      do
      ^ 
------
