****** Fatal Error: Incorrect hexadecimal notation. Wrong number
of hexadecimal digits (3 digits). You must use exactely 2, 4,
8 or 16 digits only. A 2 digits value denote an INTEGER_8, a 4
digits value denote an INTEGER_16, a 8 digits value denote an
INTEGER_32, and, finally, a 16 digits value denote an INTEGER_64.
(See examples in file "SmartEiffel/tutorial/hexadecimal.e".)

Line 14 column 20 in BAD_HEXADECIMAL1 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_hexadecimal1.e):
         i := 0xfff
                   ^------
