****** Warning: Added missing ",".

Line 9 column 4 in BAD_FEATURE1 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_feature1.e):
   i: INTEGER;
   ^          
------
****** Fatal Error: Keyword "end" expected at the end of a class.

Line 9 column 5 in BAD_FEATURE1 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_feature1.e):
   i: INTEGER;
    ^         
------
