****** Fatal Error: Class AUX_GENERIC8 is a generic class (missing
actual generic).

The source lines involved by the message are the following:

Line 12 column 7 in BAD_GENERIC8 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_generic8.e):
         a: AUX_GENERIC8
            ^           
Line 4 column 19 in AUX_GENERIC8 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_generic8.e):
class AUX_GENERIC8[E]
                  ^  
------
