****** Error: Overflow while reading integer constant. Value `9223372036854775808'
does not fit on INTEGER_64).

Line 17 column 17 in BAD_INTEGER_CONSTANT8 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_integer_constant8.e):
         i64 := 9223372036854775808
                ^                  
------
****** 1 error.
Load class "/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_integer_constant8.e" aborted.
****** Fatal Error: Unable to load class "BAD_INTEGER_CONSTANT8".

------
