****** Error: Feature found is a procedure.

The source lines relevant to this message are the following:

Line 14 column 17 in BAD_PROCEDURE1 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_procedure1.e):
         bar := foo
                ^  
Line 17 column 4 in BAD_PROCEDURE1 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_procedure1.e):
   foo
   ^  
------
****** Fatal Error: This call has no result.

Line 14 column 17 in BAD_PROCEDURE1 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_procedure1.e):
         bar := foo
                ^  
------
