****** Warning: BAD_DEFERRED2 cannot be a root class since it
is a deferred class.

------
****** Warning: Deferred class should not have creation clause
(VGCP.1).

The source lines relevant to this message are the following:

Line 4 column 7 in BAD_DEFERRED2 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_deferred2.e):
class BAD_DEFERRED2
      ^            
Line 6 column 1 in BAD_DEFERRED2 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_deferred2.e):
create {}
^        
------
****** 2 warnings.
