****** Warning: Keyword "require else" replaced with "require"
(There is no inherited require assertion here).

Line 33 column 7 in BAD_REQUIRE2 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_require2.e):
      require else --'require' needed
      ^                              
------
****** Warning: Keyword "require" replaced with "require else"
because there is an inherited require assertion.

Line 26 column 7 in BAD_REQUIRE2 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_require2.e):
      require --'require else' needed
      ^                              
------
****** 2 warnings.
