****** Error: Unable to find the feature name which is mandatory
just after the "frozen" keyword.

Line 10 column 11 in BAD_FEATURE8 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_feature8.e):
   frozen Current
          ^      
------
****** Fatal Error: Expression `Current' is not a feature name.

Line 10 column 11 in BAD_FEATURE8 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_feature8.e):
   frozen Current
          ^      
------
