****** Fatal Error: An attribute cannot be undefined.

The source lines relevant to this message are the following:

Line 10 column 22 in BAD_INHERIT13 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_inherit13.e):
      undefine foo2, count
                     ^    
Line 24 column 4 in AUX_INHERIT13B (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/aux_inherit13b.e):
   count: INTEGER
   ^             
------
