****** Error: Feature found is not a procedure.

The source lines relevant to this message are the following:

Line 16 column 12 in BAD_LIKE12 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_like12.e):
         b.g
           ^
Line 10 column 4 in AUX_LIKE12A (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/aux_like12a.e):
   g: like f
   ^        
------
****** Fatal Error: This call has a result value (and you must
use it).

Line 16 column 12 in BAD_LIKE12 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_like12.e):
         b.g
           ^
------
