****** Fatal Error: A frozen feature must not be undefined. What
is frozen _is_ frozen.

The source lines involved by the message are the following:

Line 8 column 16 in BAD_UNDEFINE1 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_undefine1.e):
      undefine test
               ^   
Line 8 column 11 in AUX_UNDEFINE1 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_undefine1.e):
   frozen test is
          ^      
------
