****** Fatal Error: Cannot redefine `make' which is actually already
renamed as `make_foo'

The source lines relevant to this message are the following:

Line 9 column 5 in BAD_REDEFINE3 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_redefine3.e):
    make as make_foo
    ^               
Line 11 column 5 in BAD_REDEFINE3 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_redefine3.e):
    make
    ^   
------
