****** Fatal Error: A type mark is not a valid item for a manifest
array. Keep in mind that Liberty Eiffel is case-sensitive and
that G_TYPE_STRING cannot be an expression. End of manifest array
expected.

Line 15 column 30 in BAD_SYNTAX10 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_syntax10.e):
         create text.make (<<G_TYPE_STRING>>)
                             ^               
------
