****** Error: Feature found is a procedure.

The source lines relevant to this message are the following:

Line 13 column 10 in BAD_FEATURE4 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_feature4.e):
         test_1.f
         ^       
Line 17 column 4 in BAD_FEATURE4 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_feature4.e):
   test_1
   ^     
------
****** Fatal Error: This call has no result.

Line 13 column 10 in BAD_FEATURE4 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_feature4.e):
         test_1.f
         ^       
------
