****** Fatal Error: A frozen feature must not be undefined. What
is frozen _is_ frozen.

The source lines relevant to this message are the following:

Line 11 column 16 in BAD_UNDEFINE4 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_undefine4.e):
      undefine test
               ^   
Line 8 column 11 in AUX_UNDEFINE3B (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/aux_undefine3b.e):
   frozen test
          ^   
------
