****** Fatal Error: "SDL_SCREEN_set_videomode" is not valid identifier.
For a better readability Liberty Eiffel _is_ case sensitive. Hence
"SDL_SCREEN_set_videomode" cannot be a valid class name (only
upper case letters are allowed in class names). "SDL_SCREEN_set_videomode"
cannot be a valid feature name or a valid local name (only lower
case letters are allowed here). Furthermore "SDL_SCREEN_set_videomode"
is not valid keyword."

Line 15 column 32 in BAD_SYNTAX08 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_syntax08.e):
         screen_memo.set_item (SDL_SCREEN_set_videomode
                               ^                       
------
