****** Fatal Error: Conflict between local/feature name (VRLE).

The source lines involved by the message are the following:

Line 14 column 3 in BAD_LOCAL_LIST4 (/home/colnet/SmartEiffel/work/lib_test3/bad_local_list4.e):
    bar: INTEGER;
    ^            
Line 7 column 18 in AUX_LOCAL_LIST4B (/home/colnet/SmartEiffel/work/lib_test3/aux_local_list4b.e):
   rename foo as bar end
                 ^      
------
