****** Fatal Error: The feature called has no formal argument
while the actual argument list has 1 argument.

The source lines involved by the message are the following:

Line 12 column 9 in BAD_CONSTANT7 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_constant7.e):
         if f(5).out = Void then
              ^                 
Line 16 column 2 in BAD_CONSTANT7 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_constant7.e):
   f: INTEGER is 3
   ^              
------
