****** Fatal Error:  Bad assignment. Cannot assign `integer_64'
which is of type INTEGER_64 into `integer_32' which is of type
INTEGER_32.

The source lines relevant to this message are the following:

Line 15 columns 10, 24 in BAD_ASSIGNMENT14 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_assignment14.e):
         integer_32 := integer_64
         ^             ^         
------
