****** Fatal Error: Multiple Precursor found (must use Precursor
{...} ancestor selection).

The source lines involved by the message are the following:

Line 10 column 4 in BAD_PRECURSOR11 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_precursor11.e):
   AUX_PRECURSOR11A redefine foo end
   ^                                
Line 12 column 4 in BAD_PRECURSOR11 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_precursor11.e):
   AUX_PRECURSOR11B redefine foo end
   ^                                
Line 26 column 4 in BAD_PRECURSOR11 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_precursor11.e):
     Precursor -- Is really ambiguous !
     ^                                 
------
