****** Fatal Error:  Bad assignment. Error detected while checking
this code in the BAD_PRECURSOR09 context. Cannot assign `create
{AUX_PRECURSOR09}.make_aux' which is of type AUX_PRECURSOR09 into
`Result' which is of type BAD_PRECURSOR09.

The source lines relevant to this message are the following:

Line 16 columns 10, 20 in AUX_PRECURSOR09 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/aux_precursor09.e):
         Result := create {AUX_PRECURSOR09}.make_aux
         ^         ^                                
------
