****** Fatal Error: Wrong number of generic arguments (compare
usage and definition below).

The source lines relevant to this message are the following:

Line 12 column 13 in BAD_GENERIC9 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_generic9.e):
         a: AUX_GENERIC9[INTEGER]
            ^                    
Line 4 column 19 in AUX_GENERIC9 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/aux_generic9.e):
class AUX_GENERIC9[E1_->INTEGER, E2_->INTEGER]
                  ^                           
------
