****** Fatal Error: The feature called has 1 argument while the
actual argument list has no argument.

The source lines relevant to this message are the following:

Line 14 column 14 in BAD_CALL6 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_call6.e):
         aux.foo
             ^  
Line 7 column 8 in AUX_CALL6 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/aux_call6.e):
   foo (arg: STRING)
       ^            
------
