****** Fatal Error: Invalid assignment test. The left-hand side
expression must conforms with the right-hand side. The left-hand
side is of type COMPARABLE while expression `h' is of type HASHABLE.

The source lines involved by the message are the following:

Line 14 columns 11, 17 in BAD_ASSIGNMENT_TEST01 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_assignment_test01.e):
         if not c ?:= h then
                ^     ^     
------
