****** Fatal Error: Class AUX_GENERIC8 is a generic class (missing
actual generic).

The source lines relevant to this message are the following:

Line 12 column 13 in BAD_GENERIC8 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_generic8.e):
         a: AUX_GENERIC8
            ^           
Line 4 column 19 in AUX_GENERIC8 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/aux_generic8.e):
class AUX_GENERIC8[E_]
                  ^   
------
