****** Warning: Added missing "then" keyword.

Line 13 column 10 in BAD_IF1 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_if1.e):
         end
         ^  
------
****** Error: "if" (or "elseif" as well) must be followed by a
BOOLEAN expression.

Line 12 column 10 in BAD_IF1 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_if1.e):
         if 1
         ^   
------
****** Fatal Error: The declaration type of this expression is
INTEGER_8 (this is not BOOLEAN).

Line 12 column 13 in BAD_IF1 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_if1.e):
         if 1
            ^
------
