****** Error: Feature found is not a procedure.

The source lines involved by the message are the following:

Line 13 column 5 in BAD_LIKE12 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_like12.e):
    b.g(x)
      ^   
Line 10 column 4 in AUX_LIKE12A (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_like12a.e):
   g: like f
   ^        
------
****** Fatal Error: This call has a result value (and you must
use it).

Line 13 column 5 in BAD_LIKE12 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_like12.e):
    b.g(x)
      ^   
------
