****** Error: Error while reading fractional part of a real value
(digit expected after the dot).

Line 14 column 17 in BAD_REAL2 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_real2.e):
         r := 1.;
                ^
------
****** Fatal Error: Right hand side expression of := assignment
expected here.

Line 15 column 15 in BAD_REAL2 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_real2.e):
         r := .5;
              ^  
------
