****** Fatal Error: Syntax error while trying to parse the beginning
of a new feature definition. Feature name expected. Class name
MY_FUNCTION cannot be used as a feature name to start a new feature
definition. Parser lost. Sorry. Check before and after that point.

Line 14 column 4 in BAD_FEATURE9 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_feature9.e):
   MY_FUNCTION: STRING
   ^                  
------
