****** Fatal Error: The feature called has no formal argument
while the actual argument list has 1 argument.

The source lines relevant to this message are the following:

Line 12 column 14 in BAD_CONSTANT7 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_constant7.e):
         if f(5).out = Void then
             ^                  
Line 16 column 4 in BAD_CONSTANT7 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_constant7.e):
   f: INTEGER 3
   ^           
------
