****** Warning: Extra blank or tab character removed in multi-line
manifest string.

Line 14 column 22 in BAD_VERBATIM_STRING2 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_verbatim_string2.e):
          s := "jjj%    
                     ^  
------
****** Warning: Extra blank or tab character removed in multi-line
manifest string.

Line 14 column 23 in BAD_VERBATIM_STRING2 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_verbatim_string2.e):
          s := "jjj%    
                      ^ 
------
****** Warning: Extra blank or tab character removed in multi-line
manifest string.

Line 14 column 24 in BAD_VERBATIM_STRING2 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_verbatim_string2.e):
          s := "jjj%    
                       ^
------
****** Fatal Error: Unexpected new line in manifest string.

Line 16 column 21 in BAD_VERBATIM_STRING2 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_verbatim_string2.e):
          s := "[ hi
                    ^------
