****** Fatal Error: Unknown feature `to_real_32' in type REAL_32.
(For this call, the target `real_32' is of type REAL_32.)

The source lines relevant to this message are the following:

Line 17 columns 21, 29 in BAD_TO_REAL_32 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_to_real_32.e):
         real_32 := real_32.to_real_32
                    ^       ^         
------
