****** Error: For inspect statement, the expression type can be
only INTEGER, CHARACTER, STRING, or FIXED_STRING. (Actually `pointer'
is of type POINTER which is not allowed.)

Line 15 column 13 in BAD_INSPECT15 (/home/persocad/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_inspect15.e):
            pointer -- Wrong!
            ^                
------
****** Fatal Error: Such an "inspect" statement is for type STRING
or FIXED_STRING. (The type of `pointer' is POINTER.)

Line 15 column 13 in BAD_INSPECT15 (/home/persocad/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_inspect15.e):
            pointer -- Wrong!
            ^                
------
