****** Warning: Added missing ":" semicolon before this type mark.

Line 12 column 18 in BAD_LOCAL_LIST6 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_local_list6.e):
         clock1 clock2 CLOCK integer INTEGER
                       ^                    
------
****** Warning: Added missing ":" semicolon before this type mark.

Line 12 column 32 in BAD_LOCAL_LIST6 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_local_list6.e):
         clock1 clock2 CLOCK integer INTEGER
                                     ^      
------
****** 2 warnings.
****** 2 warnings.
