****** Fatal Error:  Bad assignment. Cannot assign `integer' which
is of type INTEGER_32 into `comparable' which is of type COMPARABLE.

The source lines involved by the message are the following:

Line 14 columns 4, 18 in BAD_ASSIGNMENT23 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_assignment23.e):
         comparable := integer -- <-- Must be rejected.
         ^             ^                               
------
