****** Fatal Error: Bad redefinition. An attribute must be redefined
as an attribute only (VDRD.6).
Line 3 column 4 in AUX_REDEFINE9 (/home/colnet/SmartEiffel/work/lib_test3/aux_redefine9.e) :
   dummy : BOOLEAN;
   ^
Line 9 column 4 in BAD_REDEFINE9 (/home/colnet/SmartEiffel/work/lib_test3/bad_redefine9.e) :
   dummy : BOOLEAN is
   ^
------
File "bad_redefine9.make" not found. Error(s) during `compile_to_c'.
