****** Warning: Extra blank or tab character removed in multi-line
manifest string.

Line 14 column 14 in BAD_VERBATIM_STRING2 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_verbatim_string2.e):
    s := "jjj%    
               ^  
------
****** Warning: Extra blank or tab character removed in multi-line
manifest string.

Line 14 column 15 in BAD_VERBATIM_STRING2 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_verbatim_string2.e):
    s := "jjj%    
                ^ 
------
****** Warning: Extra blank or tab character removed in multi-line
manifest string.

Line 14 column 16 in BAD_VERBATIM_STRING2 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_verbatim_string2.e):
    s := "jjj%    
                 ^
------
****** Fatal Error: Unexpected new line in manifest string.

Line 16 column 13 in BAD_VERBATIM_STRING2 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_verbatim_string2.e):
    s := "[ hi
              ^------
