****** Warning: It is useless to mark as "redefine" this deferred
feature.

Line 8 column 16 in BAD_PRECURSOR07 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_precursor07.e):
      redefine routine
               ^      
------
****** Fatal Error: All ancestors are deferred, hence making this
Precursor call not valid.

Line 22 column 10 in BAD_PRECURSOR07 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_precursor07.e):
         Precursor;
         ^         
------
