****** Fatal Error: Invalid assignment test. The left-hand side
expression must conforms with the right-hand side. The left-hand
side is of type COMPARABLE while expression `h' is of type HASHABLE.

The source lines relevant to this message are the following:

Line 17 columns 17, 23 in BAD_ASSIGNMENT_TEST01 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_assignment_test01.e):
         if not c ?:= h then
                ^     ^     
------
