****** Warning: Empty argument list (deleted).

Line 14 column 15 in BAD_SYNTAX2 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_syntax2.e):
         foo ()
              ^
------
****** Fatal Error: Empty "when" clause in "inspect" statement.

Line 17 column 15 in BAD_SYNTAX2 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_syntax2.e):
         when then
              ^   
------
