****** Fatal Error: Because of the usual low priority of prefix
minus, `-foo.bar' is actually equivalent to `-(foo.bar)'. In order
to avoid a possible mistake here, it is mandatory for you to add
extra parentheses here. You can wrap `-1' or the whole expression
as well. It's up to you to decide now.

Line 14 column 15 in BAD_PREFIX_MINUS1 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_prefix_minus1.e):
         i := -1.abs
              ^     
------
