****** Fatal Error: Assignment of a reference type into an expanded
type is not allowed.  Cannot assign `Current' which is of type
BAD_INHERIT19 into `foo' which is of type AUX_INHERIT19.

The source lines relevant to this message are the following:

Line 17 columns 10, 17 in BAD_INHERIT19 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_inherit19.e):
         foo := Current
         ^      ^      
------
