****** Fatal Error: Can't join these two concrete features. What's
called a concrete feature here is a feature which is not deferred.
You may consider to undefine one feature. May be.

The source lines involved by the message are the following:

Line 11 column 4 in BAD_INHERIT4 (/home/colnet/SmartEiffel/work/lib_test3/bad_inherit4.e):
   AUX_SELECT
   ^         
Line 10 column 4 in AUX_SELECT (/home/colnet/SmartEiffel/work/lib_test3/aux_select.e):
   foo is
   ^     
Line 15 column 4 in AUX_SELECT (/home/colnet/SmartEiffel/work/lib_test3/aux_select.e):
   bar is
   ^     
------
