****** Warning: Added missing "end" keyword to terminate inherit/insert parent.

Line 11 column 1 in BAD_INHERIT9 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_inherit9.e):
create {}
^        
------
****** Fatal Error: Unknown feature `true_error_here_to_keep_track_of_the_previous_warning'
in type BAD_INHERIT9. (For this call, the target is the implicit
non written `Current' which is of type BAD_INHERIT9.)

Line 17 column 10 in BAD_INHERIT9 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_inherit9.e):
         true_error_here_to_keep_track_of_the_previous_warning
         ^                                                    
------
