****** Fatal Error: To pass arguments of agents, only the explicit
manifest TUPLE notation is allowed (i.e. the square bracketed
tuple notation must be used here). Actually, this is to force
you to show clearly what arguments you are passing to this agent.
(Note: this explicit manifest TUPLE notation will not incurs extra
memory allocation. Keep cool.)

Line 15 column 26 in BAD_SZ550 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_sz550.e):
         foo := agent foo.item([])
                               ^  
------
