****** Fatal Error:  Bad assignment. Cannot assign `actual_expanded'
which is of type AUX_ASSIGNMENT18B into `non_expanded' which is
of type AUX_ASSIGNMENT18A.

The source lines relevant to this message are the following:

Line 15 columns 10, 26 in BAD_ASSIGNMENT18 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_assignment18.e):
         non_expanded := actual_expanded
         ^               ^              
------
