****** Fatal Error: The old "select" option of the "inherit" clause
is now obsolete. You have to update your code with the new "insert"
mechanism. With SmartEiffel, this can be achieve thanks to the
new "insert" clause. The new "insert" clause comes just after
the traditional "inherit" clause with a similar syntax.

Line 9 column 7 in BAD_SELECT3 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_select3.e):
      select aux_foo
      ^             
------
