****** Fatal Error: Can't join these two concrete features. What's
called a concrete feature here is a feature which is not deferred.
You may consider to undefine one feature. May be.

The source lines relevant to this message are the following:

Line 7 column 4 in BAD_INHERIT4 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_inherit4.e):
   AUX_SELECT
   ^         
Line 9 column 4 in AUX_SELECT (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/aux_select.e):
   foo
   ^  
Line 14 column 4 in AUX_SELECT (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/aux_select.e):
   bar
   ^  
------
