****** Error: Feature found is a procedure.

The source lines involved by the message are the following:

Line 15 column 10 in BAD_PROCEDURE1 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_procedure1.e):
    bar := foo
           ^  
Line 18 column 4 in BAD_PROCEDURE1 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_procedure1.e):
   foo is
   ^     
------
****** Fatal Error: This call has no result.

Line 15 column 10 in BAD_PROCEDURE1 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_procedure1.e):
    bar := foo
           ^  
------
