****** Fatal Error: Using a static constant expression just after
the "is" keyword is suitable only for a constant attribute definition.
The constant found (i.e. `0.0') cannot be used as the definition
of the feature `zero'. Actually, feature `zero' has no result
type. Bad constant-attribute definition.

Line 12 column 4 in BAD_CONSTANT2 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_constant2.e):
   zero is 0.0;
   ^           
------
