****** Warning: Added missing ",".

Line 12 column 24 in BAD_COLON (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_colon.e):
         fonction(1, 2 3);
                       ^  
------
****** Fatal Error: Variable `Result' is valid only inside a function.

Line 17 column 10 in BAD_COLON (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_colon.e):
         Result := true;
         ^              
------
