****** Warning: Keyword "ensure then" replaced with "ensure" (There
is no inherited ensure assertion here).

Line 33 column 7 in BAD_ENSURE3 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_ensure3.e):
      ensure then -- 'ensure' is needed
      ^                                
------
****** Warning: Keyword "ensure" replaced with "ensure then" because
there is an inherited ensure assertion.

Line 26 column 7 in BAD_ENSURE3 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_ensure3.e):
      ensure -- 'ensure then' is needed
      ^                                
------
****** 2 warnings.
