****** Fatal Error: Invalid forced assignment ("::="). The left-hand
side expression must conform to the right-hand side. The expression
`c' is of type COMPARABLE while the expression `h' is of type
HASHABLE.

The source lines relevant to this message are the following:

Line 17 columns 10, 16 in BAD_ASSIGNMENT_FORCE01 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_assignment_force01.e):
         c ::= h
         ^     ^
------
