****** Fatal Error: Conflict between local/feature name (VRLE).

The source lines relevant to this message are the following:

Line 12 column 10 in BAD_LOCAL_LIST2 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_local_list2.e):
         bar: INTEGER;
         ^            
Line 17 column 4 in BAD_LOCAL_LIST2 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_local_list2.e):
   bar: INTEGER
   ^           
------
