****** Fatal Error: Incompatible actual argument for agent call.
Cannot pass `6' which is of type INTEGER_8 into formal argument
of type CHARACTER. (The whole type of the agent your are trying
to launch is FUNCTION[TUPLE[CHARACTER],REAL_64].)

Line 15 column 18 in BAD_AGENT06 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_agent06.e):
         p.call([6]);
                 ^   
------
