****** Fatal Error: Incorrect hexadecimal notation. Wrong number
of hexadecimal digits (3 digits). You must use exactly 2, 4,
8 or 16 digits only. A 2 digit value denotes an INTEGER_8, a 4
digit value denotes an INTEGER_16, an 8 digit value denotes an
INTEGER_32, and, finally, a 16 digit value denotes an INTEGER_64.
(See examples in file "tutorial/manifest_notation.e".)

Line 14 column 20 in BAD_HEXADECIMAL1 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_hexadecimal1.e):
         i := 0xfff
                   ^------
