****** Fatal Error:  Bad assignment. Cannot assign `integer_64'
which is of type INTEGER_64 into `integer_32' which is of type
INTEGER_32.

The source lines involved by the message are the following:

Line 15 columns 4, 18 in BAD_ASSIGNMENT14 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_assignment14.e):
         integer_32 := integer_64
         ^             ^         
------
