****** Error: Decimal CHARACTER code out of range.

Line 14 column 21 in BAD_CHARACTER1 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_character1.e):
         c := '%/256/'
                    ^ 
------
****** Fatal Error: Unexpected character in decimal ascii code.

Line 15 column 18 in BAD_CHARACTER1 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_character1.e):
         c := '%//'
                 ^ 
------
