****** Warning: Added missing ":" semicolon before this type mark.

Line 12 column 10 in BAD_LOCAL_LIST5 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_local_list5.e):
         clock CLOCK integer INTEGER
               ^                    
------
****** Warning: Added missing ":" semicolon before this type mark.

Line 12 column 24 in BAD_LOCAL_LIST5 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_local_list5.e):
         clock CLOCK integer INTEGER
                             ^      
------
****** 2 warnings.
****** 2 warnings.
