****** Error: Feature found is not a procedure.

The source lines relevant to this message are the following:

Line 12 column 5 in BAD_FUNCTION1 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_function1.e):
    foo
    ^  
Line 15 column 4 in BAD_FUNCTION1 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_function1.e):
   foo: BOOLEAN
   ^           
------
****** Fatal Error: This call has a result value (and you must
use it).

Line 12 column 5 in BAD_FUNCTION1 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_function1.e):
    foo
    ^  
------
