****** Fatal Error: Unknown feature `to_integer_16' in type INTEGER_16.
(For this call, the target `i16' is of type INTEGER_16.)

The source lines relevant to this message are the following:

Line 17 columns 17, 21 in BAD_TO_INTEGER_16 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_to_integer_16.e):
         i16 := i16.to_integer_16
                ^   ^            
------
