****** Fatal Error: No more "reference" keyword allowed. The obsolete
"reference FOO" notation is no longer accepted. Just use our REFERENCE
class instead.

The source lines involved by the message are the following:

Line 12 columns 7, 17 in BAD_REFERENCE1 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_reference1.e):
    ri: reference INTEGER_GENERAL
        ^         ^              
------
