****** Fatal Error: A frozen feature must not be undefined. What
is frozen _is_ frozen.

The source lines relevant to this message are the following:

Line 8 column 16 in BAD_UNDEFINE1 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_undefine1.e):
      undefine test
               ^   
Line 7 column 11 in AUX_UNDEFINE1 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/aux_undefine1.e):
   frozen test
          ^   
------
