****** Warning: Empty argument list (deleted).

Line 14 column 8 in BAD_SYNTAX2 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_syntax2.e):
    foo ()
         ^
------
****** Fatal Error: Empty "when" clause in "inspect" statement.

Line 17 column 8 in BAD_SYNTAX2 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_syntax2.e):
    when then
         ^   
------
