****** Fatal Error: Multiple Precursor found (must use Precursor
{...} ancestor selection).

The source lines relevant to this message are the following:

Line 10 column 4 in BAD_PRECURSOR11 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_precursor11.e):
   AUX_PRECURSOR11A redefine foo end
   ^                                
Line 12 column 4 in BAD_PRECURSOR11 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_precursor11.e):
   AUX_PRECURSOR11B redefine foo end
   ^                                
Line 25 column 10 in BAD_PRECURSOR11 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_precursor11.e):
         Precursor -- Is really ambiguous !
         ^                                 
------
