****** Error: Decimal CHARACTER code out of range.

Line 14 column 14 in BAD_CHARACTER1 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_character1.e):
    c := '%/256/'
               ^ 
------
****** Fatal Error: Unexpected character in decimal ascii code.

Line 15 column 11 in BAD_CHARACTER1 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_character1.e):
    c := '%//'
            ^ 
------
