****** Fatal Error: You are probably trying to use the new inherit/insert
mechanism. With Liberty Eiffel, this can be achieved thanks to
the new "insert" clause. The new "insert" clause comes just after
the traditional "inherit" clause with a similar syntax.

Line 8 column 4 in BAD_INSERT1 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_insert1.e):
   expanded AUX_INSERT1 -- Obsolete !
   ^                                 
------
