****** Warning: Actually, a creation list must not be empty. You
must have at least the `default_create' procedure inherited from
ANY. The `default_create' indicates that one can also create an
object with no creation procedure. The `default_create' has been
added here automatically.

Line 6 column 1 in AUX_CREATION1 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_creation1.e):
creation 
^        
------
****** 1 warning.
****** 1 warning.
