****** Fatal Error: The feature called has 1 formal argument while
there is no actual argument list in the call.

The source lines involved by the message are the following:

Line 22 column 3 in BAD_PRECURSOR05 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_precursor05.e):
    Precursor;
    ^         
Line 8 column 12 in AUX_PRECURSOR04 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_precursor04.e):
   routine(i: INTEGER) is
           ^             
------
