****** Fatal Error: A frozen feature must not be undefined. What
is frozen _is_ frozen.

The source lines involved by the message are the following:

Line 8 column 16 in BAD_UNDEFINE3 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_undefine3.e):
      undefine test
               ^   
Line 9 column 11 in AUX_UNDEFINE3B (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_undefine3b.e):
   frozen test is
          ^      
------
