****** Error: Unable to find the feature name which is mandatory
just after the "frozen" keyword.

Line 10 column 11 in BAD_FEATURE6 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_feature6.e):
   frozen MY_FUNCTION: INTEGER
          ^                   
------
****** Fatal Error: This is not a feature name, but a class name.

Line 10 column 11 in BAD_FEATURE6 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_feature6.e):
   frozen MY_FUNCTION: INTEGER
          ^                   
------
