****** Fatal Error: Unknown feature `The' in type BAD_UNIQUE3.
(For this call, the target is the implicit non written `Current'
which is of type BAD_UNIQUE3.)

Line 16 column 26 in BAD_UNIQUE3 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_unique3.e):
         if u1 < u2 then The compiler should choke on this wrong code
                         ^                                           
------
