****** Fatal Error: Cannot use such a strange create expression
for type INTEGER_32 which is a simple and predefined expanded
type. Actually, just replace this create expression with `0' and
you are done.

Line 14 column 21 in BAD_CREATE7 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_create7.e):
         integer := create {INTEGER}
                    ^               
------
