****** Fatal Error: Keyword "end" expected at the end of check
clause.

The source lines relevant to this message are the following:

Line 14 column 10 in BAD_ASSERTION1 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_assertion1.e):
         check
         ^    
Line 15 column 16 in BAD_ASSERTION1 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_assertion1.e):
            x := 3;
               ^   
------
