****** Fatal Error: Such an expression cannot be on the left-hand
side of an assignment operator. A dot can never be used for the
left-hand side part of an assignment operator. Valid left-hand
side can be Result, some local or the name of an attribute of
Current. See also http://SmartEiffel/wiki/en/Syntax_diagrams#Writable.php
for details.

Line 15 column 23 in BAD_ASSIGNMENT25 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_assignment25.e):
         aux25.an_attribute := 1
                            ^   
------
