****** Warning: Probably infinite or too long generic derivation
of this type mark (see next warnings to find the cause of the
problem... and good luck).

Line 11 column 15 in AUX_GENERIC6 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_generic6.e):
         aa : AUX_GENERIC6[AUX_GENERIC6[T]]
              ^                            
------
****** Warning: The huge generic derivation related to the previous
warning is: AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[INTEGER_32]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]

------
****** Warning: Probably infinite or too long generic derivation
of this type mark (see next warnings to find the cause of the
problem... and good luck).

Line 380 column 9 in ANY (/home/colnet/SmartEiffel/lib/kernel/any.e):
   frozen to_internals: INTERNALS is
          ^                         
------
****** Warning: The huge generic derivation related to the previous
warning is: TYPED_INTERNALS[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[INTEGER_32]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]

------
****** Warning: Probably infinite or too long generic derivation
of this type mark (see next warnings to find the cause of the
problem... and good luck).

Line 11 column 15 in AUX_GENERIC6 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_generic6.e):
         aa : AUX_GENERIC6[AUX_GENERIC6[T]]
              ^                            
------
****** Warning: The huge generic derivation related to the previous
warning is: AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[ANY]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]

------
****** Warning: Probably infinite or too long generic derivation
of this type mark (see next warnings to find the cause of the
problem... and good luck).

Line 380 column 9 in ANY (/home/colnet/SmartEiffel/lib/kernel/any.e):
   frozen to_internals: INTERNALS is
          ^                         
------
****** Warning: The huge generic derivation related to the previous
warning is: TYPED_INTERNALS[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[ANY]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]

------
****** Warning: Probably infinite or too long generic derivation
of this type mark (see next warnings to find the cause of the
problem... and good luck).

Line 11 column 15 in AUX_GENERIC6 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_generic6.e):
         aa : AUX_GENERIC6[AUX_GENERIC6[T]]
              ^                            
------
****** Warning: The huge generic derivation related to the previous
warning is: AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[INTEGER_32]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]

------
****** Warning: Probably infinite or too long generic derivation
of this type mark (see next warnings to find the cause of the
problem... and good luck).

Line 380 column 9 in ANY (/home/colnet/SmartEiffel/lib/kernel/any.e):
   frozen to_internals: INTERNALS is
          ^                         
------
****** Warning: The huge generic derivation related to the previous
warning is: TYPED_INTERNALS[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[INTEGER_32]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]

------
****** Warning: Probably infinite or too long generic derivation
of this type mark (see next warnings to find the cause of the
problem... and good luck).

Line 11 column 15 in AUX_GENERIC6 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_generic6.e):
         aa : AUX_GENERIC6[AUX_GENERIC6[T]]
              ^                            
------
****** Warning: The huge generic derivation related to the previous
warning is: AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[ANY]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]

------
****** Warning: Probably infinite or too long generic derivation
of this type mark (see next warnings to find the cause of the
problem... and good luck).

Line 380 column 9 in ANY (/home/colnet/SmartEiffel/lib/kernel/any.e):
   frozen to_internals: INTERNALS is
          ^                         
------
****** Warning: The huge generic derivation related to the previous
warning is: TYPED_INTERNALS[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[ANY]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]

------
****** Warning: Probably infinite or too long generic derivation
of this type mark (see next warnings to find the cause of the
problem... and good luck).

Line 11 column 15 in AUX_GENERIC6 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_generic6.e):
         aa : AUX_GENERIC6[AUX_GENERIC6[T]]
              ^                            
------
****** Warning: The huge generic derivation related to the previous
warning is: AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[INTEGER_32]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]

------
****** Warning: Probably infinite or too long generic derivation
of this type mark (see next warnings to find the cause of the
problem... and good luck).

Line 380 column 9 in ANY (/home/colnet/SmartEiffel/lib/kernel/any.e):
   frozen to_internals: INTERNALS is
          ^                         
------
****** Warning: The huge generic derivation related to the previous
warning is: TYPED_INTERNALS[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[INTEGER_32]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]

------
****** Warning: Probably infinite or too long generic derivation
of this type mark (see next warnings to find the cause of the
problem... and good luck).

Line 11 column 15 in AUX_GENERIC6 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_generic6.e):
         aa : AUX_GENERIC6[AUX_GENERIC6[T]]
              ^                            
------
****** Warning: The huge generic derivation related to the previous
warning is: AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[ANY]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]

------
****** Warning: Probably infinite or too long generic derivation
of this type mark (see next warnings to find the cause of the
problem... and good luck).

Line 380 column 9 in ANY (/home/colnet/SmartEiffel/lib/kernel/any.e):
   frozen to_internals: INTERNALS is
          ^                         
------
****** Warning: The huge generic derivation related to the previous
warning is: TYPED_INTERNALS[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[ANY]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]

------
****** Warning: Probably infinite or too long generic derivation
of this type mark (see next warnings to find the cause of the
problem... and good luck).

Line 11 column 15 in AUX_GENERIC6 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_generic6.e):
         aa : AUX_GENERIC6[AUX_GENERIC6[T]]
              ^                            
------
****** Warning: The huge generic derivation related to the previous
warning is: AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[INTEGER_32]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]

------
****** Warning: Probably infinite or too long generic derivation
of this type mark (see next warnings to find the cause of the
problem... and good luck).

Line 380 column 9 in ANY (/home/colnet/SmartEiffel/lib/kernel/any.e):
   frozen to_internals: INTERNALS is
          ^                         
------
****** Warning: The huge generic derivation related to the previous
warning is: TYPED_INTERNALS[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[INTEGER_32]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]

------
****** Warning: Probably infinite or too long generic derivation
of this type mark (see next warnings to find the cause of the
problem... and good luck).

Line 11 column 15 in AUX_GENERIC6 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_generic6.e):
         aa : AUX_GENERIC6[AUX_GENERIC6[T]]
              ^                            
------
****** Warning: The huge generic derivation related to the previous
warning is: AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[ANY]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]

------
****** Warning: Probably infinite or too long generic derivation
of this type mark (see next warnings to find the cause of the
problem... and good luck).

Line 380 column 9 in ANY (/home/colnet/SmartEiffel/lib/kernel/any.e):
   frozen to_internals: INTERNALS is
          ^                         
------
****** Warning: The huge generic derivation related to the previous
warning is: TYPED_INTERNALS[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[ANY]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]

------
****** Warning: Probably infinite or too long generic derivation
of this type mark (see next warnings to find the cause of the
problem... and good luck).

Line 11 column 15 in AUX_GENERIC6 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_generic6.e):
         aa : AUX_GENERIC6[AUX_GENERIC6[T]]
              ^                            
------
****** Warning: The huge generic derivation related to the previous
warning is: AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[INTEGER_32]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]

------
****** Warning: Probably infinite or too long generic derivation
of this type mark (see next warnings to find the cause of the
problem... and good luck).

Line 380 column 9 in ANY (/home/colnet/SmartEiffel/lib/kernel/any.e):
   frozen to_internals: INTERNALS is
          ^                         
------
****** Warning: The huge generic derivation related to the previous
warning is: TYPED_INTERNALS[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[INTEGER_32]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]

------
****** Warning: Probably infinite or too long generic derivation
of this type mark (see next warnings to find the cause of the
problem... and good luck).

Line 11 column 15 in AUX_GENERIC6 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_generic6.e):
         aa : AUX_GENERIC6[AUX_GENERIC6[T]]
              ^                            
------
****** Warning: The huge generic derivation related to the previous
warning is: AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[ANY]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]

------
****** Warning: Probably infinite or too long generic derivation
of this type mark (see next warnings to find the cause of the
problem... and good luck).

Line 380 column 9 in ANY (/home/colnet/SmartEiffel/lib/kernel/any.e):
   frozen to_internals: INTERNALS is
          ^                         
------
****** Warning: The huge generic derivation related to the previous
warning is: TYPED_INTERNALS[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[ANY]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]

------
****** Warning: Probably infinite or too long generic derivation
of this type mark (see next warnings to find the cause of the
problem... and good luck).

Line 11 column 15 in AUX_GENERIC6 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_generic6.e):
         aa : AUX_GENERIC6[AUX_GENERIC6[T]]
              ^                            
------
****** Warning: The huge generic derivation related to the previous
warning is: AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[INTEGER_32]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]

------
****** Warning: Probably infinite or too long generic derivation
of this type mark (see next warnings to find the cause of the
problem... and good luck).

Line 380 column 9 in ANY (/home/colnet/SmartEiffel/lib/kernel/any.e):
   frozen to_internals: INTERNALS is
          ^                         
------
****** Warning: The huge generic derivation related to the previous
warning is: TYPED_INTERNALS[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[INTEGER_32]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]

------
****** Warning: Probably infinite or too long generic derivation
of this type mark (see next warnings to find the cause of the
problem... and good luck).

Line 11 column 15 in AUX_GENERIC6 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_generic6.e):
         aa : AUX_GENERIC6[AUX_GENERIC6[T]]
              ^                            
------
****** Warning: The huge generic derivation related to the previous
warning is: AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[ANY]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]

------
****** Warning: Probably infinite or too long generic derivation
of this type mark (see next warnings to find the cause of the
problem... and good luck).

Line 380 column 9 in ANY (/home/colnet/SmartEiffel/lib/kernel/any.e):
   frozen to_internals: INTERNALS is
          ^                         
------
****** Warning: The huge generic derivation related to the previous
warning is: TYPED_INTERNALS[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[ANY]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]

------
****** Warning: Probably infinite or too long generic derivation
of this type mark (see next warnings to find the cause of the
problem... and good luck).

Line 11 column 15 in AUX_GENERIC6 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_generic6.e):
         aa : AUX_GENERIC6[AUX_GENERIC6[T]]
              ^                            
------
****** Warning: The huge generic derivation related to the previous
warning is: AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[INTEGER_32]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]

------
****** Warning: Probably infinite or too long generic derivation
of this type mark (see next warnings to find the cause of the
problem... and good luck).

Line 380 column 9 in ANY (/home/colnet/SmartEiffel/lib/kernel/any.e):
   frozen to_internals: INTERNALS is
          ^                         
------
****** Error: The huge generic derivation related to the previous
warning is: TYPED_INTERNALS[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[INTEGER_32]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]

------
****** Warning: Probably infinite or too long generic derivation
of this type mark (see next warnings to find the cause of the
problem... and good luck).

Line 11 column 15 in AUX_GENERIC6 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_generic6.e):
         aa : AUX_GENERIC6[AUX_GENERIC6[T]]
              ^                            
------
****** Error: The huge generic derivation related to the previous
warning is: AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[ANY]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]

------
****** Warning: Probably infinite or too long generic derivation
of this type mark (see next warnings to find the cause of the
problem... and good luck).

Line 380 column 9 in ANY (/home/colnet/SmartEiffel/lib/kernel/any.e):
   frozen to_internals: INTERNALS is
          ^                         
------
****** Error: The huge generic derivation related to the previous
warning is: TYPED_INTERNALS[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[ANY]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]

------
****** Warning: Probably infinite or too long generic derivation
of this type mark (see next warnings to find the cause of the
problem... and good luck).

Line 11 column 15 in AUX_GENERIC6 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_generic6.e):
         aa : AUX_GENERIC6[AUX_GENERIC6[T]]
              ^                            
------
****** Error: The huge generic derivation related to the previous
warning is: AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[INTEGER_32]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]

------
****** Warning: Probably infinite or too long generic derivation
of this type mark (see next warnings to find the cause of the
problem... and good luck).

Line 380 column 9 in ANY (/home/colnet/SmartEiffel/lib/kernel/any.e):
   frozen to_internals: INTERNALS is
          ^                         
------
****** Error: The huge generic derivation related to the previous
warning is: TYPED_INTERNALS[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[INTEGER_32]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]

------
****** Warning: Probably infinite or too long generic derivation
of this type mark (see next warnings to find the cause of the
problem... and good luck).

Line 11 column 15 in AUX_GENERIC6 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_generic6.e):
         aa : AUX_GENERIC6[AUX_GENERIC6[T]]
              ^                            
------
****** Error: The huge generic derivation related to the previous
warning is: AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[AUX_GENERIC6[ANY]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]

------
****** Too many errors.
