****** Fatal Error: Can't join these two attribute definitions.
Because an attribute cannot be undefined (using an undefine clause),
you may consider to modify parents themselves. May be.

The source lines relevant to this message are the following:

Line 7 column 4 in BAD_INHERIT18 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_inherit18.e):
   AUX_INHERIT18A
   ^             
Line 7 column 4 in AUX_INHERIT18A (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/aux_inherit18a.e):
   an_attribute: INTEGER
   ^                    
Line 7 column 4 in AUX_INHERIT18B (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/aux_inherit18b.e):
   an_attribute: INTEGER
   ^                    
------
