****** Warning: It is useless to mark as "redefine" this deferred
feature.

Line 8 column 16 in BAD_PRECURSOR07 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_precursor07.e):
      redefine routine
               ^      
------
****** Fatal Error: All ancestors are deferred, hence making this
Precursor call not valid.

Line 22 column 3 in BAD_PRECURSOR07 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_precursor07.e):
    Precursor;
    ^         
------
