****** Error: Invalid creation procedure. A "once" procedure is
not allowed as a creation procedure.

The source lines relevant to this message are the following:

Line 8 column 4 in BAD_ROOT6 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_root6.e):
   main
   ^   
Line 11 column 4 in BAD_ROOT6 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_root6.e):
   main
   ^   
------
****** Fatal Error: Correct the previous error first.

------
