****** Fatal Error: Second occurrence for this value in the same
inspect. (Wrong inspect statement.)

The source lines relevant to this message are the following:

Line 16 column 15 in BAD_INSPECT7 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_inspect7.e):
         when 1, 2 then
              ^        
Line 17 column 15 in BAD_INSPECT7 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_inspect7.e):
         when 1 then -- Second occurrence !
              ^                            
------
