****** Fatal Error:  Bad assignment. Cannot assign `integer' which
is of type INTEGER_32 into `comparable' which is of type COMPARABLE.

The source lines relevant to this message are the following:

Line 14 columns 10, 24 in BAD_ASSIGNMENT23 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_assignment23.e):
         comparable := integer -- <-- Must be rejected.
         ^             ^                               
------
