****** Fatal Error: INTEGER is expanded. The generic argument
of WEAK_REFERENCE must not be expanded. (It does not makes sense
to do so.)

The source lines relevant to this message are the following:

Line 12 columns 15, 30 in BAD_WEAK_REFERENCE01 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_weak_reference01.e):
         bwr: WEAK_REFERENCE[INTEGER]
              ^              ^       
------
