****** Warning: Added missing ":" before this type mark.

Line 12 column 24 in BAD_LOCAL_LIST6 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_local_list6.e):
         clock1 clock2 CLOCK integer INTEGER
                       ^                    
------
****** Warning: Added missing ":" before this type mark.

Line 12 column 38 in BAD_LOCAL_LIST6 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_local_list6.e):
         clock1 clock2 CLOCK integer INTEGER
                                     ^      
------
****** 2 warnings.
