****** Error: Slash "/" character expected after hexadecimal value
in CHARACTER constant.

Line 15 column 15 in BAD_CHARACTER2 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_character2.e):
    c := '%/0xFFF/'
                ^  
------
****** Fatal Error: Slash ("/") expected (inside CHARACTER constant).

Line 15 column 15 in BAD_CHARACTER2 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_character2.e):
    c := '%/0xFFF/'
                ^  
------
