****** Warning: Extra blank or tab character removed in multi-line
manifest string.

Line 14 column 19 in BAD_VERBATIM_STRING1 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_verbatim_string1.e):
          s := "[ 
                  ^------
****** Warning: Extra blank or tab character removed in multi-line
manifest string.

Line 18 column 19 in BAD_VERBATIM_STRING1 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_verbatim_string1.e):
          s := "[	
                 	^------
****** Fatal Error: Error inside multi-line manifest string.

The source lines relevant to this message are the following:

Line 18 column 16 in BAD_VERBATIM_STRING1 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_verbatim_string1.e):
          s := "[	
               ^ 	
Line 21 column 7 in BAD_VERBATIM_STRING1 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_verbatim_string1.e):
      end;
      ^   
------
