****** Fatal Error: No more "reference" keyword allowed. The obsolete
"reference FOO" notation is no longer accepted. Just use the REFERENCE
class instead.

The source lines relevant to this message are the following:

Line 12 columns 14, 24 in BAD_REFERENCE1 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_reference1.e):
         ri: reference INTEGER_GENERAL
             ^         ^              
------
