****** Warning: Actually, a creation list must not be empty. You
must have at least the `default_create' procedure inherited from
ANY. The `default_create' indicates that one can also create an
object with no creation procedure. The `default_create' has been
added here automatically.

Line 6 column 1 in AUX_CREATION1 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/aux_creation1.e):
create {ANY}
^           
------
****** 1 warning.
