****** Fatal Error: "SDL_ShowCursor" is not valid identifier.
For a better readability SmartEiffel _is_ case sensitive. Hence
"SDL_ShowCursor" cannot be a valid class name (only upper case
letters are allowed in class names). "SDL_ShowCursor" cannot be
a valid feature name or a valid local name (only lower case letters
are allowed here). Furthermore "SDL_ShowCursor" is not valid keyword."

Line 17 column 18 in BAD_IDENTIFIER2 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_identifier2.e):
         showcursor := SDL_ShowCursor (0)
                       ^                 
------
