****** Error: Expression of the loop variant must be of INTEGER
type. (The actual BOOLEAN type is not allowed as a variant type.)

Line 14 column 6 in BAD_LOOP2 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_loop2.e):
       True
       ^   
------
****** Fatal Error: Error in variant part of loop definition.

The source lines involved by the message are the following:

Line 14 column 6 in BAD_LOOP2 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_loop2.e):
       True
       ^   
------
