****** Fatal Error: The feature called has no formal argument
while the actual argument list has 1 argument.

The source lines involved by the message are the following:

Line 22 column 20 in BAD_PRECURSOR06 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_precursor06.e):
         Precursor(1);
                   ^  
Line 7 column 4 in AUX_PRECURSOR06 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/aux_precursor06.e):
   routine is
   ^         
------
