****** Fatal Error: Using a static constant expression just after
the "is" keyword is suitable only for a constant attribute definition.
The constant found (i.e. `3') cannot be used as the definition
of the feature `f'. Actually, feature `f' has an argument list.
Bad constant-attribute definition.

Line 12 column 2 in BAD_CONSTANT9 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_constant9.e):
   f (i:INTEGER): INTEGER is 3
   ^                          
------
