****** Warning: Added missing ":" before this type mark.

Line 12 column 16 in BAD_LOCAL_LIST5 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_local_list5.e):
         clock CLOCK integer INTEGER
               ^                    
------
****** Warning: Added missing ":" before this type mark.

Line 12 column 30 in BAD_LOCAL_LIST5 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_local_list5.e):
         clock CLOCK integer INTEGER
                             ^      
------
****** 2 warnings.
