****** Fatal Error: The feature called has 1 formal argument while
there is no actual argument list in the call.

The source lines involved by the message are the following:

Line 14 column 7 in BAD_CALL6 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_call6.e):
    aux.foo
        ^  
Line 8 column 9 in AUX_CALL6 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_call6.e):
   foo (arg: STRING) is
        ^              
------
