****** Error: This is not an INTEGER expression.(The corresponding
feature definition is in the next error message.)

Line 18 column 15 in BAD_INSPECT6 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_inspect6.e):
         when wrong then
              ^         
------
****** Fatal Error: The corresponding feature definition.

Line 10 column 16 in BAD_INSPECT6 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_inspect6.e):
   wrong: REAL 3.5
               ^  
------
