****** Fatal Error: No more "expanded" keyword allowed here. The
obsolete "expanded FOO" notation is no longer accepted.

The source lines involved by the message are the following:

Line 12 columns 23, 32 in BAD_WEAK_REFERENCE03 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_weak_reference03.e):
    bwr: WEAK_REFERENCE[expanded BAD_WEAK_REFERENCE03]
                        ^        ^                    
------
