****** Fatal Error: Bad constant-attribute definition. Using a manifest
constant for the feature value is suitable only for a constant-attribute
definition. The constant found (i.e. `0.0') cannot be used as the definition of
the feature `zero'. Actually, feature `zero' has no result type.

Line 13 column 4 in BAD_CONSTANT2 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_constant2.e):
   zero 0.0;
   ^        
------
