****** Fatal Error: An attribute cannot be undefined.

The source lines involved by the message are the following:

Line 10 column 22 in BAD_INHERIT13 (/home/colnet/SmartEiffel/work/lib_test3/bad_inherit13.e):
      undefine foo2, count
                     ^    
Line 25 column 4 in AUX_INHERIT13B (/home/colnet/SmartEiffel/work/lib_test3/aux_inherit13b.e):
   count: INTEGER
   ^             
------
