****** Fatal Error: Conflict between local/feature name (VRLE).

The source lines relevant to this message are the following:

Line 14 column 10 in BAD_LOCAL_LIST3 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_local_list3.e):
         bar: INTEGER;
         ^            
Line 7 column 4 in AUX_LOCAL_LIST3 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/aux_local_list3.e):
   bar: INTEGER;
   ^            
------
