****** Error: Feature found is not writable (i.e. not an attribute).

Line 12 column 17 in BAD_CREATE1 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_create1.e):
         create t.make(100)
                ^          
------
****** Error:  See also the next message for more information.

------
****** Fatal Error: Here is the corresponding feature definition
(not an attribute).

Line 10 column 4 in BAD_CREATE1 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_create1.e):
   t: STRING
   ^        
------
