****** Fatal Error:  Bad assignment. Cannot assign `integer_32'
which is of type INTEGER_32 into `integer_16' which is of type
INTEGER_16.

The source lines relevant to this message are the following:

Line 15 columns 10, 24 in BAD_ASSIGNMENT12 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_assignment12.e):
         integer_16 := integer_32
         ^             ^         
------
