****** Warning: A routine must be ended with "end".

Line 18 column 13 in BAD_ENSURE1 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_ensure1.e):
         t := 0
            ^  
------
****** Fatal Error: Keyword "end" expected at the end of a class.

Line 18 column 13 in BAD_ENSURE1 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_ensure1.e):
         t := 0
            ^  
------
