****** Fatal Error: Empty list not allowed for manifest generic
creation.

The source lines involved by the message are the following:

Line 14 columns 11, 31 in BAD_MANIFEST_GENERIC1 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_manifest_generic1.e):
         set := {SET[INTEGER] << >> } -- Not the right way to make an empty set !
                ^                   ^                                            
------
