****** Fatal Error: To pass arguments of agents, only the explicit
manifest TUPLE notation is allowed (i.e. the square bracketed
tuple notation must be used here). Actually, this is to force
you to show clearly what arguments you are passing to this agent.
(Note: this explicit manifest TUPLE notation will not incurs extra
memory allocation. Keep cool.)

Line 17 column 17 in BAD_AGENT03 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_agent03.e):
    my_agent.call(tuple);
                  ^      
------
