****** Error: Expression of until must be of BOOLEAN type. (The
actual INTEGER_8 type is not allowed.)

Line 12 column 21 in BAD_LOOP1 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_loop1.e):
         from until 1
                    ^
------
****** Fatal Error: Error in until part of loop definition.

The source lines relevant to this message are the following:

Line 12 columns 10, 21 in BAD_LOOP1 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_loop1.e):
         from until 1
         ^          ^
------
