****** Fatal Error: Assignment of a reference type into an expanded
type is not allowed.  Cannot assign `ref' which is of type AUX_ASSIGNMENT2_REF
into `exp' which is of type AUX_ASSIGNMENT2EXP.

The source lines relevant to this message are the following:

Line 18 columns 10, 17 in BAD_ASSIGNMENT2B (/home/persocad/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_assignment2b.e):
         exp := ref -- This one is not allowed !
         ^      ^                               
------
