****** Error: Unable to find the feature name which is mandatory
just after the "frozen" keyword.

Line 10 column 9 in BAD_FEATURE8 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_feature8.e):
   frozen Current is
          ^         
------
****** Fatal Error: Expression `Current' is not a feature name.

Line 10 column 9 in BAD_FEATURE8 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_feature8.e):
   frozen Current is
          ^         
------
