****** Error: You must use an even number of hexadecimal digits
to denote a sequence of CHARACTERs.

Line 14 column 19 in BAD_STRING1 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_string1.e):
    s := "Hi %/0x456/"
                    ^ 
------
****** Fatal Error: Unexpected character in hexadecimal ascii
code.

Line 15 column 19 in BAD_STRING1 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_string1.e):
    s := "Hi %/0x456G/"
                    ^  
------
