****** Warning: Added ",".

Line 12 column 17 in BAD_COLON (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_colon.e):
    fonction(1, 2 3);
                  ^  
------
****** Fatal Error: Variable `Result' is valid only inside a function.

Line 17 column 3 in BAD_COLON (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_colon.e):
    Result := true;
    ^              
------
