****** Fatal Error: Second occurrence for this value in the same
inspect. (Wrong inspect statement.)

The source lines involved by the message are the following:

Line 14 column 8 in BAD_INSPECT7 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_inspect7.e):
    when 1, 2 then
         ^        
Line 15 column 8 in BAD_INSPECT7 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_inspect7.e):
    when 1 then -- Second occurrence !
         ^                            
------
