****** Error: Invalid creation procedure. A function is not allowed
as a creation procedure.

The source lines relevant to this message are the following:

Line 8 column 4 in BAD_ROOT7 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_root7.e):
   main
   ^   
Line 11 column 4 in BAD_ROOT7 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_root7.e):
   main: INTEGER
   ^            
------
****** Fatal Error: Correct the previous error first.

------
