****** Fatal Error: Bad constant-attribute definition. Using a manifest
constant for the feature value is suitable only for a constant-attribute
definition. The constant found (i.e. `3') cannot be used as the definition of
the feature `f'. Actually, feature `f' has an argument list.


Line 15 column 4 in BAD_CONSTANT9 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_constant9.e):
   f (i:INTEGER): INTEGER 3
   ^                       
------
