****** Fatal Error: Invalid assignment attempt ("?="). The left-hand
side expression must conform to the right-hand side. The expression
`b' is of type AUX_CA1_B while the expression `a' is of type AUX_CA1_A.

The source lines relevant to this message are the following:

Line 16 columns 10, 15 in BAD_ASSIGNMENT_ATTEMPT1 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_assignment_attempt1.e):
         b ?= a
         ^    ^
------
