****** Error: Feature found is not a procedure.

The source lines relevant to this message are the following:

Line 14 column 21 in BAD_CREATE2 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_create2.e):
         create aux.make;
                    ^    
Line 10 column 4 in AUX_CREATE2 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/aux_create2.e):
   make: INTEGER 1;
   ^               
------
****** Fatal Error: This call has a result value (and you must
use it).

Line 14 column 21 in BAD_CREATE2 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_create2.e):
         create aux.make;
                    ^    
------
