****** Warning: Added missing ",".

Line 13 column 17 in BAD_ALIAS_05BIS (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_alias_05bis.e):
                () = 42)
                ^       
------
****** Fatal Error: Expression expected.

Line 13 column 18 in BAD_ALIAS_05BIS (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_alias_05bis.e):
                () = 42)
                 ^      
------
