****** Fatal Error:  Bad assignment. Cannot assign `integer_16'
which is of type INTEGER_16 into `integer_8' which is of type
INTEGER_8.

The source lines relevant to this message are the following:

Line 15 columns 10, 23 in BAD_ASSIGNMENT9 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_assignment9.e):
         integer_8 := integer_16
         ^            ^         
------
