****** Error: Feature found is a procedure.

The source lines involved by the message are the following:

Line 13 column 4 in BAD_FEATURE4 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_feature4.e):
         test_1.f
         ^       
Line 17 column 4 in BAD_FEATURE4 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_feature4.e):
   test_1 is
   ^        
------
****** Fatal Error: This call has no result.

Line 13 column 4 in BAD_FEATURE4 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_feature4.e):
         test_1.f
         ^       
------
