****** Fatal Error: Cannot pass `'A'' which is of type CHARACTER
into formal type INTEGER_32.

The source lines involved by the message are the following:

Line 22 column 13 in BAD_PRECURSOR04 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_precursor04.e):
    Precursor('A');
              ^    
Line 8 column 15 in AUX_PRECURSOR04 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_precursor04.e):
   routine(i: INTEGER) is
              ^          
------
