****** Error: Same identifier appears twice (local/closure).

The source lines relevant to this message are the following:

Line 9 column 10 in BAD_CLOSURE02 (/home/persocad/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_closure02.e):
         a: INTEGER
         ^         
Line 14 column 19 in BAD_CLOSURE02 (/home/persocad/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_closure02.e):
                  a: INTEGER
                  ^         
------
****** 1 error.
Load class "/home/persocad/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_closure02.e" aborted.
****** Fatal Error: Unable to load class "BAD_CLOSURE02".

------
