****** Fatal Error: The feature called has no formal argument
while the actual argument list has 2 arguments.

The source lines relevant to this message are the following:

Line 15 column 22 in BAD_AGENT09 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_agent09.e):
         r := agent f(?,2)
                     ^    
Line 19 column 4 in BAD_AGENT09 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_agent09.e):
   f
   ^
------
