****** Error: This is not an INTEGER expression.(The corresponding
feature definition is in the next error message.)

Line 16 column 8 in BAD_INSPECT6 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_inspect6.e):
    when wrong then
         ^         
------
****** Fatal Error: The corresponding feature definition.

Line 8 column 19 in BAD_INSPECT6 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_inspect6.e):
   wrong: REAL is 3.5
                  ^  
------
