****** Fatal Error: Invalid forced assignment ("::="). The left-hand
side expression must conforms with the right-hand side. Expression
`c' is of type COMPARABLE while expression `h' is of type HASHABLE.

The source lines involved by the message are the following:

Line 14 columns 4, 10 in BAD_ASSIGNMENT_FORCE01 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_assignment_force01.e):
         c ::= h
         ^     ^
------
