****** Fatal Error: Unable to solve cyclic anchored types.

The source lines relevant to this message are the following:

Line 20 column 4 in BAD_LIKE1 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_like1.e):
   a: like b
   ^        
Line 25 column 4 in BAD_LIKE1 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_like1.e):
   b: like a
   ^        
------
