****** Fatal Error: No such TUPLE definition in file "/home/cadrian/Workspace/Dev/Liberty/src/lib/kernel/tuple.e".
Too long TUPLE (the TUPLE you want has 18 formal generic arguments
while the maximum allowed is 10).


Line 14 column 15 in BAD_TUPLE_TOO_LONG2 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_tuple_too_long2.e):
         t := [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]
              ^                                             
------
