****** Error: Actual argument list of Precursor call doesn't match the procedures signature.

The source lines relevant to this message are the following:

Line 23 column 10 in BAD_PRECURSOR06 (/home/r/Liberty/test/language/error_warning_msg/bad_precursor06.e):
         Precursor(1);
         ^            
Line 7 column 4 in AUX_PRECURSOR06 (/home/r/Liberty/test/language/error_warning_msg/aux_precursor06.e):
   routine
   ^      
------
****** Fatal Error: Correct the previous error first.

------
