****** Error: For inspect statement, the expression type can be
only INTEGER, CHARACTER or STRING. (Actually `pointer' is of type
POINTER which is not allowed.)

Line 13 column 5 in BAD_INSPECT15 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_inspect15.e):
            pointer -- Wrong!
            ^                
------
****** Fatal Error: Such an "inspect" statement is for type STRING.
(The type of `pointer' is POINTER.)

Line 13 column 5 in BAD_INSPECT15 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_inspect15.e):
            pointer -- Wrong!
            ^                
------
