****** Error: Invalid creation procedure. A function is not allowed
as a creation procedure.

The source lines involved by the message are the following:

Line 8 column 2 in BAD_ROOT7 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_root7.e):
   main
   ^   
Line 11 column 2 in BAD_ROOT7 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_root7.e):
   main: INTEGER is
   ^               
------
****** Fatal Error: Correct the previous error first.

------
