****** Warning: You are using a case sensitive language in which
all class names must use only upper case letters. This decision
was made to make the code more readable and to allow better error
messages as well as syntax error recovery. The name "bad_class5"
has been automatically replaced with "BAD_CLASS5".

Line 4 column 7 in BAD_CLASS5 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_class5.e):
class bad_class5 -- Wrong class name here.
      ^                                   
------
****** 1 warning.
