****** Error: Actual argument list of Precursor call doesn't match the procedures signature.

The source lines involved by the message are the following:

Line 24 column 10 in BAD_PRECURSOR05 (/home/r/Liberty/test/language/error_warning_msg/bad_precursor05.e):
         Precursor;
         ^         
Line 7 column 4 in AUX_PRECURSOR04 (/home/r/Liberty/test/language/error_warning_msg/aux_precursor04.e):
   routine(i: INTEGER)
   ^                  
------
****** Fatal Error: Correct the previous error first.

------
