****** Fatal Error: The feature called has 1 formal argument while
there is no actual argument list in the call.

The source lines involved by the message are the following:

Line 22 column 10 in BAD_PRECURSOR05 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_precursor05.e):
         Precursor;
         ^         
Line 7 column 12 in AUX_PRECURSOR04 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/aux_precursor04.e):
   routine(i: INTEGER) is
           ^             
------
