****** Error: Feature found is not a procedure.

The source lines involved by the message are the following:

Line 14 column 21 in BAD_CREATE2 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_create2.e):
         create aux.make;
                    ^    
Line 10 column 4 in AUX_CREATE2 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_create2.e):
   make: INTEGER is 1;
   ^                  
------
****** Fatal Error: This call has a result value (and you must
use it).

Line 14 column 21 in BAD_CREATE2 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_create2.e):
         create aux.make;
                    ^    
------
