****** Fatal Error:  Bad assignment. Cannot assign `integer_32'
which is of type INTEGER_32 into `integer_16' which is of type
INTEGER_16.

The source lines involved by the message are the following:

Line 15 columns 4, 18 in BAD_ASSIGNMENT12 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_assignment12.e):
         integer_16 := integer_32
         ^             ^         
------
