****** Fatal Error: Invalid assignment attempt ("?="). The left-hand
side expression must conforms with the right-hand side. Expression
`b' is of type AUX_CA1_B while expression `a' is of type AUX_CA1_A.

The source lines involved by the message are the following:

Line 17 columns 10, 15 in BAD_ASSIGNMENT_ATTEMPT1 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_assignment_attempt1.e):
         b ?= a
         ^    ^
------
