****** Error: TUPLE type expected for open arguments of agent
type.

The source lines involved by the message are the following:

Line 4 column 7 in BAD_AGENT13 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_agent13.e):
class BAD_AGENT13
      ^          
Line 14 column 6 in BAD_AGENT13 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_agent13.e):
    p: PROCEDURE[like bad_type]
       ^                       
------
****** Error: TUPLE type expected for open arguments of agent
type.

The source lines involved by the message are the following:

Line 4 column 7 in BAD_AGENT13 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_agent13.e):
class BAD_AGENT13
      ^          
Line 9 column 2 in PROCEDURE (/home/colnet/SmartEiffel/lib/kernel/procedure.e):
   ROUTINE[O_]
   ^          
------
****** Error: TUPLE type expected for open arguments of agent
type. (See also the next fatal error message.)

Line 9 column 10 in PROCEDURE (/home/colnet/SmartEiffel/lib/kernel/procedure.e):
   ROUTINE[O_]
           ^  
------
****** Fatal Error: When the context of the validation is PROCEDURE[BAD_AGENT13],
this type mark is not a TUPLE. (This is actually BAD_AGENT13.)

Line 9 column 10 in PROCEDURE (/home/colnet/SmartEiffel/lib/kernel/procedure.e):
   ROUTINE[O_]
           ^  
------
