****** Fatal Error:  Bad assignment. Cannot assign `store2' which
is of type NATIVE_ARRAY[INTEGER_32] into `store1' which is of
type NATIVE_ARRAY[REAL_64].

The source lines relevant to this message are the following:

Line 16 columns 10, 20 in BAD_NATIVE_ARRAY1 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_native_array1.e):
         store1 := store2;
         ^         ^      
------
