****** Error: Feature found is not a procedure.

The source lines involved by the message are the following:

Line 13 column 3 in BAD_FUNCTION1 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_function1.e):
    foo
    ^  
Line 16 column 4 in BAD_FUNCTION1 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_function1.e):
   foo: BOOLEAN is
   ^              
------
****** Fatal Error: This call has a result value (and you must
use it).

Line 13 column 3 in BAD_FUNCTION1 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_function1.e):
    foo
    ^  
------
