****** Fatal Error: No such TUPLE definition in file "/home/cadrian/Workspace/Dev/Liberty/src/lib/kernel/tuple.e".
Too long TUPLE (the TUPLE you want has 25 formal generic arguments
while the maximum allowed is 10).


Line 12 column 8 in BAD_TUPLE_TOO_LONG1 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_tuple_too_long1.e):
    t: TUPLE[INTEGER, INTEGER, INTEGER, INTEGER, INTEGER, INTEGER, INTEGER, INTEGER, INTEGER, INTEGER, INTEGER, INTEGER, INTEGER, INTEGER, INTEGER, INTEGER, INTEGER, INTEGER, INTEGER, INTEGER, INTEGER, INTEGER, INTEGER, INTEGER, INTEGER]
       ^                                                                                                                                                                                                                                     
------
