****** Fatal Error: Empty list not allowed for manifest generic
creation.

The source lines relevant to this message are the following:

Line 14 columns 17, 37 in BAD_MANIFEST_GENERIC1 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_manifest_generic1.e):
         set := {SET[INTEGER] << >> } -- Not the right way to make an empty set !
                ^                   ^                                            
------
