****** Error: Bad redefinition. Result types must be both expanded
or both non-expanded (VDRD.6).
Line 10 column 9 in AUX_REDEFINE13B (/home/colnet/SmartEiffel/work/lib_test3/aux_redefine13b.e) :
   foo: like Current is
        ^
Line 5 column 9 in AUX_REDEFINE13A (/home/colnet/SmartEiffel/work/lib_test3/aux_redefine13a.e) :
   foo: like Current is
        ^
------
****** Fatal Error: Signature of the redefined feature is not
valid.
Line 4 column 4 in AUX_REDEFINE13B (/home/colnet/SmartEiffel/work/lib_test3/aux_redefine13b.e) :
   AUX_REDEFINE13A
   ^
Line 10 column 4 in AUX_REDEFINE13B (/home/colnet/SmartEiffel/work/lib_test3/aux_redefine13b.e) :
   foo: like Current is
   ^
Line 5 column 4 in AUX_REDEFINE13A (/home/colnet/SmartEiffel/work/lib_test3/aux_redefine13a.e) :
   foo: like Current is
   ^
------
File "bad_redefine13.make" not found. Error(s) during `compile_to_c'.
