****** Fatal Error:  Bad assignment. Cannot assign `integer_32'
which is of type INTEGER_32 into `integer_8' which is of type
INTEGER_8.

The source lines relevant to this message are the following:

Line 15 columns 10, 23 in BAD_ASSIGNMENT10 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_assignment10.e):
         integer_8 := integer_32
         ^            ^         
------
