****** Fatal Error: Can't join these two attribute definitions.
Because an attribute cannot be undefined (using an undefine clause),
you may consider to modify parents themselves. May be.

The source lines involved by the message are the following:

Line 10 column 2 in BAD_INHERIT18 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_inherit18.e):
   AUX_INHERIT18B
   ^             
Line 7 column 2 in AUX_INHERIT18A (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_inherit18a.e):
   an_attribute: INTEGER
   ^                    
Line 7 column 2 in AUX_INHERIT18B (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_inherit18b.e):
   an_attribute: INTEGER
   ^                    
------
