****** Fatal Error: Class PLATFORM is not generic.

The source lines involved by the message are the following:

Line 6 column 9 in BAD_INHERIT6 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_inherit6.e):
inherit PLATFORM[INTEGER]
        ^                
Line 3 column 16 in PLATFORM (/home/colnet/SmartEiffel/lib/kernel/platform.e):
expanded class PLATFORM
               ^       
------
