****** Fatal Error: The feature called has no formal argument
while the actual argument list has 2 arguments.

The source lines involved by the message are the following:

Line 12 column 16 in BAD_AGENT09 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_agent09.e):
    r := agent f(?,2)
                 ^   
Line 16 column 4 in BAD_AGENT09 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_agent09.e):
   f is
   ^   
------
