****** Warning: The client list computed from the "export" clauses
is narrower than the one from the conforming parent(s) for AUX_EXPORT3B.`print_on'.
This can lead to catcalls! The final export list is {}.

The source lines involved by the message are the following:

Line 205 column 9 in ANY (/home/colnet/SmartEiffel/lib/kernel/any.e):
feature {ANY} -- Object Printing:
        ^                        
Line 7 column 14 in AUX_EXPORT3B (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_export3b.e):
      export {NONE} all
             ^         
------
****** Warning: The client list computed from the "export" clauses
is narrower than the one from the conforming parent(s) for AUX_EXPORT3B.`standard_copy'.
This can lead to catcalls! The final export list is {}.

The source lines involved by the message are the following:

Line 78 column 9 in ANY (/home/colnet/SmartEiffel/lib/kernel/any.e):
feature {ANY} -- Duplication:
        ^                    
Line 7 column 14 in AUX_EXPORT3B (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_export3b.e):
      export {NONE} all
             ^         
------
****** Warning: The client list computed from the "export" clauses
is narrower than the one from the conforming parent(s) for AUX_EXPORT3B.`out'.
This can lead to catcalls! The final export list is {}.

The source lines involved by the message are the following:

Line 205 column 9 in ANY (/home/colnet/SmartEiffel/lib/kernel/any.e):
feature {ANY} -- Object Printing:
        ^                        
Line 7 column 14 in AUX_EXPORT3B (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_export3b.e):
      export {NONE} all
             ^         
------
****** Warning: The client list computed from the "export" clauses
is narrower than the one from the conforming parent(s) for AUX_EXPORT3B.`deep_twin'.
This can lead to catcalls! The final export list is {}.

The source lines involved by the message are the following:

Line 116 column 9 in ANY (/home/colnet/SmartEiffel/lib/kernel/any.e):
feature {ANY} -- Deep Duplication:
        ^                         
Line 7 column 14 in AUX_EXPORT3B (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_export3b.e):
      export {NONE} all
             ^         
------
****** Warning: The client list computed from the "export" clauses
is narrower than the one from the conforming parent(s) for AUX_EXPORT3B.`generator'.
This can lead to catcalls! The final export list is {}.

The source lines involved by the message are the following:

Line 30 column 9 in ANY (/home/colnet/SmartEiffel/lib/kernel/any.e):
feature {ANY} -- Access:
        ^               
Line 7 column 14 in AUX_EXPORT3B (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_export3b.e):
      export {NONE} all
             ^         
------
****** Warning: The client list computed from the "export" clauses
is narrower than the one from the conforming parent(s) for AUX_EXPORT3B.`internals_can_be_retrieved'.
This can lead to catcalls! The final export list is {}.

The source lines involved by the message are the following:

Line 386 column 9 in ANY (/home/colnet/SmartEiffel/lib/kernel/any.e):
feature {TYPED_INTERNALS}
        ^                
Line 7 column 14 in AUX_EXPORT3B (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_export3b.e):
      export {NONE} all
             ^         
------
****** Warning: The client list computed from the "export" clauses
is narrower than the one from the conforming parent(s) for AUX_EXPORT3B.`object_size'.
This can lead to catcalls! The final export list is {}.

The source lines involved by the message are the following:

Line 323 column 9 in ANY (/home/colnet/SmartEiffel/lib/kernel/any.e):
feature {ANY} -- The Guru section:
        ^                         
Line 7 column 14 in AUX_EXPORT3B (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_export3b.e):
      export {NONE} all
             ^         
------
****** Warning: The client list computed from the "export" clauses
is narrower than the one from the conforming parent(s) for AUX_EXPORT3B.`to_internals'.
This can lead to catcalls! The final export list is {}.

The source lines involved by the message are the following:

Line 379 column 9 in ANY (/home/colnet/SmartEiffel/lib/kernel/any.e):
feature {INTERNALS_HANDLER}
        ^                  
Line 7 column 14 in AUX_EXPORT3B (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_export3b.e):
      export {NONE} all
             ^         
------
****** Warning: The client list computed from the "export" clauses
is narrower than the one from the conforming parent(s) for AUX_EXPORT3B.`tagged_out'.
This can lead to catcalls! The final export list is {}.

The source lines involved by the message are the following:

Line 205 column 9 in ANY (/home/colnet/SmartEiffel/lib/kernel/any.e):
feature {ANY} -- Object Printing:
        ^                        
Line 7 column 14 in AUX_EXPORT3B (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_export3b.e):
      export {NONE} all
             ^         
------
****** Warning: The client list computed from the "export" clauses
is narrower than the one from the conforming parent(s) for AUX_EXPORT3B.`standard_twin'.
This can lead to catcalls! The final export list is {}.

The source lines involved by the message are the following:

Line 78 column 9 in ANY (/home/colnet/SmartEiffel/lib/kernel/any.e):
feature {ANY} -- Duplication:
        ^                    
Line 7 column 14 in AUX_EXPORT3B (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_export3b.e):
      export {NONE} all
             ^         
------
****** Warning: The client list computed from the "export" clauses
is narrower than the one from the conforming parent(s) for AUX_EXPORT3B.`is_equal'.
This can lead to catcalls! The final export list is {}.

The source lines involved by the message are the following:

Line 50 column 9 in ANY (/home/colnet/SmartEiffel/lib/kernel/any.e):
feature {ANY} -- Comparison:
        ^                   
Line 7 column 14 in AUX_EXPORT3B (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_export3b.e):
      export {NONE} all
             ^         
------
****** Warning: The client list computed from the "export" clauses
is narrower than the one from the conforming parent(s) for AUX_EXPORT3B.`same_dynamic_type'.
This can lead to catcalls! The final export list is {}.

The source lines involved by the message are the following:

Line 42 column 9 in ANY (/home/colnet/SmartEiffel/lib/kernel/any.e):
feature {ANY} -- Status report:
        ^                      
Line 7 column 14 in AUX_EXPORT3B (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_export3b.e):
      export {NONE} all
             ^         
------
****** Warning: The client list computed from the "export" clauses
is narrower than the one from the conforming parent(s) for AUX_EXPORT3B.`copy'.
This can lead to catcalls! The final export list is {}.

The source lines involved by the message are the following:

Line 78 column 9 in ANY (/home/colnet/SmartEiffel/lib/kernel/any.e):
feature {ANY} -- Duplication:
        ^                    
Line 7 column 14 in AUX_EXPORT3B (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_export3b.e):
      export {NONE} all
             ^         
------
****** Warning: The client list computed from the "export" clauses
is narrower than the one from the conforming parent(s) for AUX_EXPORT3B.`is_basic_expanded_type'.
This can lead to catcalls! The final export list is {}.

The source lines involved by the message are the following:

Line 323 column 9 in ANY (/home/colnet/SmartEiffel/lib/kernel/any.e):
feature {ANY} -- The Guru section:
        ^                         
Line 7 column 14 in AUX_EXPORT3B (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_export3b.e):
      export {NONE} all
             ^         
------
****** Warning: The client list computed from the "export" clauses
is narrower than the one from the conforming parent(s) for AUX_EXPORT3B.`out_in_tagged_out_memory'.
This can lead to catcalls! The final export list is {}.

The source lines involved by the message are the following:

Line 205 column 9 in ANY (/home/colnet/SmartEiffel/lib/kernel/any.e):
feature {ANY} -- Object Printing:
        ^                        
Line 7 column 14 in AUX_EXPORT3B (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_export3b.e):
      export {NONE} all
             ^         
------
****** Warning: The client list computed from the "export" clauses
is narrower than the one from the conforming parent(s) for AUX_EXPORT3B.`twin'.
This can lead to catcalls! The final export list is {}.

The source lines involved by the message are the following:

Line 78 column 9 in ANY (/home/colnet/SmartEiffel/lib/kernel/any.e):
feature {ANY} -- Duplication:
        ^                    
Line 7 column 14 in AUX_EXPORT3B (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_export3b.e):
      export {NONE} all
             ^         
------
****** Warning: The client list computed from the "export" clauses
is narrower than the one from the conforming parent(s) for AUX_EXPORT3B.`generating_type'.
This can lead to catcalls! The final export list is {}.

The source lines involved by the message are the following:

Line 30 column 9 in ANY (/home/colnet/SmartEiffel/lib/kernel/any.e):
feature {ANY} -- Access:
        ^               
Line 7 column 14 in AUX_EXPORT3B (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_export3b.e):
      export {NONE} all
             ^         
------
****** Warning: The client list computed from the "export" clauses
is narrower than the one from the conforming parent(s) for AUX_EXPORT3B.`to_pointer'.
This can lead to catcalls! The final export list is {}.

The source lines involved by the message are the following:

Line 323 column 9 in ANY (/home/colnet/SmartEiffel/lib/kernel/any.e):
feature {ANY} -- The Guru section:
        ^                         
Line 7 column 14 in AUX_EXPORT3B (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_export3b.e):
      export {NONE} all
             ^         
------
****** Warning: The client list computed from the "export" clauses
is narrower than the one from the conforming parent(s) for AUX_EXPORT3B.`fill_tagged_out_memory'.
This can lead to catcalls! The final export list is {}.

The source lines involved by the message are the following:

Line 205 column 9 in ANY (/home/colnet/SmartEiffel/lib/kernel/any.e):
feature {ANY} -- Object Printing:
        ^                        
Line 7 column 14 in AUX_EXPORT3B (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_export3b.e):
      export {NONE} all
             ^         
------
****** Warning: The client list computed from the "export" clauses
is narrower than the one from the conforming parent(s) for AUX_EXPORT3B.`default'.
This can lead to catcalls! The final export list is {}.

The source lines involved by the message are the following:

Line 124 column 9 in ANY (/home/colnet/SmartEiffel/lib/kernel/any.e):
feature {ANY} -- Basic operations:
        ^                         
Line 7 column 14 in AUX_EXPORT3B (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_export3b.e):
      export {NONE} all
             ^         
------
****** Warning: The client list computed from the "export" clauses
is narrower than the one from the conforming parent(s) for AUX_EXPORT3B.`standard_is_equal'.
This can lead to catcalls! The final export list is {}.

The source lines involved by the message are the following:

Line 50 column 9 in ANY (/home/colnet/SmartEiffel/lib/kernel/any.e):
feature {ANY} -- Comparison:
        ^                   
Line 7 column 14 in AUX_EXPORT3B (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_export3b.e):
      export {NONE} all
             ^         
------
****** Warning: The client list computed from the "export" clauses
is narrower than the one from the conforming parent(s) for AUX_EXPORT3B.`foo'.
This can lead to catcalls! The final export list is {}.

The source lines involved by the message are the following:

Line 7 column 14 in AUX_EXPORT3B (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_export3b.e):
      export {NONE} all
             ^         
Line 5 column 9 in AUX_EXPORT3A (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_export3a.e):
feature {ANY}
        ^    
------
****** Warning: The client list computed from the "export" clauses
is narrower than the one from the conforming parent(s) for AUX_EXPORT3B.`is_deep_equal'.
This can lead to catcalls! The final export list is {}.

The source lines involved by the message are the following:

Line 70 column 9 in ANY (/home/colnet/SmartEiffel/lib/kernel/any.e):
feature {ANY} -- Deep Comparison:
        ^                        
Line 7 column 14 in AUX_EXPORT3B (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_export3b.e):
      export {NONE} all
             ^         
------
****** Warning: The client list computed from the "export" clauses
is narrower than the one from the conforming parent(s) for AUX_EXPORT3B.`is_default'.
This can lead to catcalls! The final export list is {}.

The source lines involved by the message are the following:

Line 124 column 9 in ANY (/home/colnet/SmartEiffel/lib/kernel/any.e):
feature {ANY} -- Basic operations:
        ^                         
Line 7 column 14 in AUX_EXPORT3B (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_export3b.e):
      export {NONE} all
             ^         
------
****** Warning: The client list computed from the "export" clauses
is narrower than the one from the conforming parent(s) for AUX_EXPORT3B.`tagged_out_memory'.
This can lead to catcalls! The final export list is {}.

The source lines involved by the message are the following:

Line 205 column 9 in ANY (/home/colnet/SmartEiffel/lib/kernel/any.e):
feature {ANY} -- Object Printing:
        ^                        
Line 7 column 14 in AUX_EXPORT3B (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_export3b.e):
      export {NONE} all
             ^         
------
****** Error: Forbidden call (i.e. exportation rules violated)
when the type of Current is BAD_EXPORT3. (See the next error report
for details.)

Line 12 column 7 in BAD_EXPORT3 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_export3.e):
    aux.foo
        ^  
------
****** Fatal Error: This feature is only exported to {}.

The source lines involved by the message are the following:

Line 7 column 14 in AUX_EXPORT3B (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_export3b.e):
      export {NONE} all
             ^         
Line 6 column 4 in AUX_EXPORT3A (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_export3a.e):
   foo is do end
   ^            
------
