****** Fatal Error: Unknown feature `to_integer_64' in type INTEGER_64.
(For this call, the target `i64' is of type INTEGER_64.)

The source lines relevant to this message are the following:

Line 17 columns 17, 21 in BAD_TO_INTEGER_64 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_to_integer_64.e):
         i64 := i64.to_integer_64
                ^   ^            
------
