****** Error: Feature name expected here.

Line 7 column 10 in BAD_FEATURE_NAME_LIST1 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_feature_name_list1.e):
   main, BAR
         ^  
------
****** Fatal Error: This is not a feature name, but a class name.

Line 7 column 10 in BAD_FEATURE_NAME_LIST1 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_feature_name_list1.e):
   main, BAR
         ^  
------
