****** Fatal Error: "SDL_ShowCursor" is not valid identifier.
For a better readability Liberty Eiffel _is_ case sensitive. Hence
"SDL_ShowCursor" cannot be a valid class name (only upper case
letters are allowed in class names). "SDL_ShowCursor" cannot be
a valid feature name or a valid local name (only lower case letters
are allowed here). Furthermore "SDL_ShowCursor" is not valid keyword."

Line 17 column 24 in BAD_IDENTIFIER2 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_identifier2.e):
         showcursor := SDL_ShowCursor (0)
                       ^                 
------
