****** Fatal Error: The feature called has 1 formal argument while
the actual argument list has 2 arguments.

The source lines relevant to this message are the following:

Line 12 column 13 in BAD_CALL5 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_call5.e):
         bar(1, 2)
            ^     
Line 15 column 8 in BAD_CALL5 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_call5.e):
   bar (x: INTEGER)
       ^           
------
