****** Warning: Add undefine or redefine to all inherited version
of feature path in BAD_REDEFINE8 because there is a local definition
in this class. Redefine has been automatically added. Please check.

The source lines involved by the message are the following:

Line 7 column 4 in BAD_REDEFINE8 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_redefine8.e):
   AUX_REDEFINE7A;
   ^              
Line 14 column 5 in BAD_REDEFINE8 (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/bad_redefine8.e):
    path: STRING;
    ^            
Line 6 column 4 in AUX_REDEFINE7A (/home/colnet/SmartEiffel/test_suite/language/error_warning_msg/aux_redefine7a.e):
   path: STRING;
   ^            
------
****** 1 warning.
