****** Fatal Error: Bad prototype for C struture set external.

The source lines relevant to this message are the following:

Line 19 column 4 in BAD_EXTERNAL_C1 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_external_c1.e):
   set_x(point_star: POINTER)
   ^                         
Line 20 column 16 in BAD_EXTERNAL_C1 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_external_c1.e):
      external "[
               ^ 
------
