****** Fatal Error: Wrong number of generic arguments (compare
usage and definition below).

The source lines involved by the message are the following:

Line 12 column 9 in BAD_GENERIC1 (/home/colnet/SmartEiffel/work/lib_test3/bad_generic1.e):
    dctn: DICTIONARY[INTEGER];
          ^                   
Line 3 column 26 in DICTIONARY (/home/colnet/SmartEiffel/lib/storage/dictionary.e):
deferred class DICTIONARY[V_, K_]
                         ^       
------
