****** Fatal Error: "SDL_showCursor" is not valid identifier.
For a better readability Liberty Eiffel _is_ case sensitive. Hence
"SDL_showCursor" cannot be a valid class name (only upper case
letters are allowed in class names). "SDL_showCursor" cannot be
a valid feature name or a valid local name (only lower case letters
are allowed here). Furthermore "SDL_showCursor" is not valid keyword."

Line 17 column 4 in BAD_IDENTIFIER3 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_identifier3.e):
   SDL_showCursor (status: INTEGER): INTEGER
   ^                                        
------
