****** Fatal Error: Class PLATFORM is not generic.

The source lines relevant to this message are the following:

Line 6 column 9 in BAD_INHERIT6 (/home/cadrian/Workspace/Dev/Liberty/test/language/error_warning_msg/bad_inherit6.e):
inherit PLATFORM[INTEGER]
        ^                
Line 4 column 16 in PLATFORM (/home/cadrian/Workspace/Dev/Liberty/src/lib/kernel/platform.e):
expanded class PLATFORM
               ^       
------
