#ifdef __cplusplus
extern "C" {
#endif
/*
ANSI C code generated by 
Liberty Eiffel The GNU Eiffel Compiler, Eiffel tools and libraries
    release 2013.11 (Charles Adler, Jr.)

Copyright (C), 2011-2013 - C.ADRIAN, P.REDAELLI, R.MACK
    http://www.liberty-eiffel.org

Original SmartEiffel code:
Copyright (C), 1994-2002 - INRIA - LORIA - ESIAL UHP Nancy 1 - FRANCE
Copyright (C), 2003-2005 - INRIA - LORIA - IUT Charlemagne Nancy 2 - FRANCE
D.COLNET, P.RIBET, C.ADRIAN, V.CROIZIER, F.MERIZEN
    http://smarteiffel.loria.fr
C Compiler options used: -pipe -O2 -fno-gcse
*/

#ifdef __cplusplus
}
#endif
#include "compile_to_c.h"
#ifdef __cplusplus
extern "C" {
#endif

T0* se_manifest1179(T2 initial_lower,int argc,...){
/*ARRAY[ARRAY[INTEGER_8]]*/
T1179*C;
va_list pa;
int i=0;
int imax;
va_start(pa,argc);
C=se_malloc(sizeof(T1179));
*C=M1179;
r1179manifest_make(C,argc,initial_lower);
imax=argc;
while (i < imax) {
T0* element=((T0*)(va_arg(pa,T0*)));
r1179manifest_put(C,i++,element);
}
va_end(pa);
return ((T0*)C);
}/*--*/

T0* se_manifest1039(T2 initial_lower,int argc,...){
/*ARRAY[TYPE_MARK]*/
T1039*C;
va_list pa;
int i=0;
int imax;
va_start(pa,argc);
C=se_malloc(sizeof(T1039));
*C=M1039;
r1039manifest_make(C,argc,initial_lower);
imax=argc;
while (i < imax) {
T0* element=((T0*)(va_arg(pa,T0*)));
r1039manifest_put(C,i++,element);
}
va_end(pa);
return ((T0*)C);
}/*--*/

T0* se_manifest1098(T2 initial_lower,int argc,...){
/*ARRAY[DECLARATION]*/
T1098*C;
va_list pa;
int i=0;
int imax;
va_start(pa,argc);
C=se_malloc(sizeof(T1098));
*C=M1098;
r1098manifest_make(C,argc,initial_lower);
imax=argc;
while (i < imax) {
T0* element=((T0*)(va_arg(pa,T0*)));
r1098manifest_put(C,i++,element);
}
va_end(pa);
return ((T0*)C);
}/*--*/

T0* se_manifest1026(int argc,...){
/*FAST_ARRAY[STRING]*/
T1026*C;
va_list pa;
int i=0;
int imax;
va_start(pa,argc);
C=se_malloc(sizeof(T1026));
*C=M1026;
r1026manifest_make(C,argc);
imax=argc;
while (i < imax) {
T0* element=((T0*)(va_arg(pa,T0*)));
r1026manifest_put(C,i++,element);
}
va_end(pa);
return ((T0*)C);
}/*--*/

T0* se_manifest1486(int argc,...){
/*FAST_ARRAY[POINTER]*/
T1486*C;
va_list pa;
int i=0;
int imax;
va_start(pa,argc);
C=se_malloc(sizeof(T1486));
*C=M1486;
r1486manifest_make(C,argc);
imax=argc;
while (i < imax) {
T8 element=((T8)(va_arg(pa,T8)));
r1486manifest_put(C,i++,element);
}
va_end(pa);
return ((T0*)C);
}/*--*/

T0* se_manifest1180(T2 initial_lower,int argc,...){
/*ARRAY[INTEGER_8]*/
T1180*C;
va_list pa;
int i=0;
int imax;
va_start(pa,argc);
C=se_malloc(sizeof(T1180));
*C=M1180;
r1180manifest_make(C,argc,initial_lower);
imax=argc;
while (i < imax) {
T1 element=((T1)(va_arg(pa,int)));
r1180manifest_put(C,i++,element);
}
va_end(pa);
return ((T0*)C);
}/*--*/

T0* se_manifest1048(int argc,...){
/*HASHED_SET[HASHED_STRING]*/
T1048*C;
va_list pa;
int i=0;
int imax;
va_start(pa,argc);
C=se_malloc(sizeof(T1048));
*C=M1048;
r1048manifest_make(C,argc);
imax=argc;
while (i < imax) {
T0* element=((T0*)(va_arg(pa,T0*)));
r1048manifest_put(C,i++,element);
}
va_end(pa);
return ((T0*)C);
}/*--*/

T0* se_manifest1145(int argc,...){
/*HASHED_SET[STRING]*/
T1145*C;
va_list pa;
int i=0;
int imax;
va_start(pa,argc);
C=se_malloc(sizeof(T1145));
*C=M1145;
r1145manifest_make(C,argc);
imax=argc;
while (i < imax) {
T0* element=((T0*)(va_arg(pa,T0*)));
r1145manifest_put(C,i++,element);
}
va_end(pa);
return ((T0*)C);
}/*--*/

int can_assign_to387_from386(T0* expression){
/* WHEN_ITEM_1 ?:= WHEN_ITEM */
if (expression == NULL) return 1;
switch (expression->id) {
case 387/*WHEN_ITEM_1*/: return 1;
}
return 0;
}/*--*/

int can_assign_to807_from691(T0* expression){
/* LOADPATH ?:= CLASSES */
if (expression == NULL) return 1;
switch (expression->id) {
case 807/*LOADPATH*/: return 1;
}
return 0;
}/*--*/

int can_assign_to681_from343(T0* expression){
/* CST_ATT ?:= ANONYMOUS_FEATURE */
if (expression == NULL) return 1;
switch (expression->id) {
case 686/*CST_ATT_CHARACTER*/: return 1;
case 683/*CST_ATT_STRING*/: return 1;
case 687/*CST_ATT_REAL*/: return 1;
case 680/*CST_ATT_BOOLEAN*/: return 1;
case 685/*CST_ATT_INTEGER*/: return 1;
case 684/*CST_ATT_UNIQUE*/: return 1;
}
return 0;
}/*--*/

int can_assign_toATTRIBUTE_from343(T0* expression){
/* ATTRIBUTE ?:= ANONYMOUS_FEATURE */
if (expression == NULL) return 1;
switch (expression->id) {
case 688/*WRITABLE_ATTRIBUTE*/: return 1;
case 686/*CST_ATT_CHARACTER*/: return 1;
case 683/*CST_ATT_STRING*/: return 1;
case 687/*CST_ATT_REAL*/: return 1;
case 680/*CST_ATT_BOOLEAN*/: return 1;
case 685/*CST_ATT_INTEGER*/: return 1;
case 684/*CST_ATT_UNIQUE*/: return 1;
}
return 0;
}/*--*/

int can_assign_to679_from343(T0* expression){
/* E_FUNCTION ?:= ANONYMOUS_FEATURE */
if (expression == NULL) return 1;
switch (expression->id) {
case 679/*E_FUNCTION*/: return 1;
}
return 0;
}/*--*/

int can_assign_to573_from343(T0* expression){
/* ONCE_FUNCTION ?:= ANONYMOUS_FEATURE */
if (expression == NULL) return 1;
switch (expression->id) {
case 573/*ONCE_FUNCTION*/: return 1;
}
return 0;
}/*--*/

int can_assign_to685_from343(T0* expression){
/* CST_ATT_INTEGER ?:= ANONYMOUS_FEATURE */
if (expression == NULL) return 1;
switch (expression->id) {
case 685/*CST_ATT_INTEGER*/: return 1;
}
return 0;
}/*--*/

int can_assign_to688_from343(T0* expression){
/* WRITABLE_ATTRIBUTE ?:= ANONYMOUS_FEATURE */
if (expression == NULL) return 1;
switch (expression->id) {
case 688/*WRITABLE_ATTRIBUTE*/: return 1;
}
return 0;
}/*--*/

int can_assign_to678_from343(T0* expression){
/* E_PROCEDURE ?:= ANONYMOUS_FEATURE */
if (expression == NULL) return 1;
switch (expression->id) {
case 678/*E_PROCEDURE*/: return 1;
}
return 0;
}/*--*/

int can_assign_to677_from343(T0* expression){
/* ONCE_PROCEDURE ?:= ANONYMOUS_FEATURE */
if (expression == NULL) return 1;
switch (expression->id) {
case 677/*ONCE_PROCEDURE*/: return 1;
}
return 0;
}/*--*/

int can_assign_to680_from343(T0* expression){
/* CST_ATT_BOOLEAN ?:= ANONYMOUS_FEATURE */
if (expression == NULL) return 1;
switch (expression->id) {
case 680/*CST_ATT_BOOLEAN*/: return 1;
}
return 0;
}/*--*/

int can_assign_to462_from394(T0* expression){
/* E_FALSE ?:= BOOLEAN_CONSTANT */
if (expression == NULL) return 1;
switch (expression->id) {
case 462/*E_FALSE*/: return 1;
}
return 0;
}/*--*/

int can_assign_to369_from351(T0* expression){
/* OTHER_INSPECT_STATEMENT ?:= INSTRUCTION */
if (expression == NULL) return 1;
switch (expression->id) {
case 369/*OTHER_INSPECT_STATEMENT*/: return 1;
}
return 0;
}/*--*/

int can_assign_to403_from351(T0* expression){
/* COMPOUND ?:= INSTRUCTION */
if (expression == NULL) return 1;
switch (expression->id) {
case 403/*COMPOUND*/: return 1;
}
return 0;
}/*--*/

int can_assign_to430_from351(T0* expression){
/* COMMENT ?:= INSTRUCTION */
if (expression == NULL) return 1;
switch (expression->id) {
case 430/*COMMENT*/: return 1;
}
return 0;
}/*--*/

int can_assign_to374_from351(T0* expression){
/* ASSIGNMENT ?:= INSTRUCTION */
if (expression == NULL) return 1;
switch (expression->id) {
case 374/*ASSIGNMENT*/: return 1;
}
return 0;
}/*--*/

int can_assign_to669_from351(T0* expression){
/* SEDB ?:= INSTRUCTION */
if (expression == NULL) return 1;
switch (expression->id) {
case 669/*SEDB*/: return 1;
}
return 0;
}/*--*/

int can_assign_to756_from338(T0* expression){
/* RUN_FEATURE_7 ?:= RUN_FEATURE */
if (expression == NULL) return 1;
switch (expression->id) {
case 756/*RUN_FEATURE_7*/: return 1;
}
return 0;
}/*--*/

int can_assign_to414_from338(T0* expression){
/* RUN_FEATURE_2 ?:= RUN_FEATURE */
if (expression == NULL) return 1;
switch (expression->id) {
case 414/*RUN_FEATURE_2*/: return 1;
}
return 0;
}/*--*/

int can_assign_to38_from39(T0* expression){
/* NATIVELY_STORED_STRING ?:= ABSTRACT_STRING */
if (expression == NULL) return 1;
switch (expression->id) {
case 7/*STRING*/: return 1;
case 300/*FIXED_STRING*/: return 1;
}
return 0;
}/*--*/

int can_assign_to300_from38(T0* expression){
/* FIXED_STRING ?:= NATIVELY_STORED_STRING */
if (expression == NULL) return 1;
switch (expression->id) {
case 300/*FIXED_STRING*/: return 1;
}
return 0;
}/*--*/

int can_assign_to351_from348(T0* expression){
/* INSTRUCTION ?:= CODE */
if (expression == NULL) return 1;
switch (expression->id) {
case 430/*COMMENT*/: return 1;
case 349/*PROCEDURE_CALL_0*/: return 1;
case 353/*PROCEDURE_CALL_1*/: return 1;
case 354/*PROCEDURE_CALL_N*/: return 1;
case 671/*REQUIRE_ASSERTION*/: return 1;
case 525/*CHECK_COMPOUND*/: return 1;
case 484/*DEBUG_COMPOUND*/: return 1;
case 420/*IFTHEN*/: return 1;
case 406/*IFTHENELSE*/: return 1;
case 364/*WHEN_CLAUSE*/: return 1;
case 369/*OTHER_INSPECT_STATEMENT*/: return 1;
case 486/*MANIFEST_STRING_INSPECT_STATEMENT*/: return 1;
case 436/*ASSERTION_LIST*/: return 1;
case 473/*LOOP_INSTRUCTION*/: return 1;
case 412/*CREATE_INSTRUCTION*/: return 1;
case 470/*C_INLINE*/: return 1;
case 501/*PRECURSOR_INSTRUCTION*/: return 1;
case 374/*ASSIGNMENT*/: return 1;
case 402/*ASSIGNMENT_ATTEMPT*/: return 1;
case 471/*ASSIGNMENT_CALL_ASSIGNER*/: return 1;
case 465/*RETRY_INSTRUCTION*/: return 1;
case 403/*COMPOUND*/: return 1;
case 667/*ENSURE_ASSERTION*/: return 1;
case 435/*CLASS_INVARIANT*/: return 1;
case 421/*NO_INVARIANT_WRAPPER*/: return 1;
case 669/*SEDB*/: return 1;
case 668/*UNUSED_EXPRESSION*/: return 1;
case 670/*RUN_TIME_ERROR_INSTRUCTION*/: return 1;
case 567/*VOID_PROC_CALL*/: return 1;
case 672/*AGENT_INSTRUCTION*/: return 1;
case 419/*RAW_CREATE_INSTRUCTION*/: return 1;
}
return 0;
}/*--*/

int can_assign_to660_from348(T0* expression){
/* COMPOUND_EXPRESSION ?:= CODE */
if (expression == NULL) return 1;
switch (expression->id) {
case 660/*COMPOUND_EXPRESSION*/: return 1;
}
return 0;
}/*--*/

int can_assign_to350_from348(T0* expression){
/* PROCEDURE_CALL ?:= CODE */
if (expression == NULL) return 1;
switch (expression->id) {
case 349/*PROCEDURE_CALL_0*/: return 1;
case 353/*PROCEDURE_CALL_1*/: return 1;
case 354/*PROCEDURE_CALL_N*/: return 1;
}
return 0;
}/*--*/

int can_assign_to403_from348(T0* expression){
/* COMPOUND ?:= CODE */
if (expression == NULL) return 1;
switch (expression->id) {
case 403/*COMPOUND*/: return 1;
}
return 0;
}/*--*/

int can_assign_to357_from348(T0* expression){
/* FUNCTION_CALL ?:= CODE */
if (expression == NULL) return 1;
switch (expression->id) {
case 495/*CALL_PREFIX_NOT*/: return 1;
case 355/*FUNCTION_CALL_0*/: return 1;
case 358/*FUNCTION_CALL_1*/: return 1;
case 360/*FUNCTION_CALL_N*/: return 1;
case 497/*CALL_PREFIX_PLUS*/: return 1;
case 498/*CALL_PREFIX_MINUS*/: return 1;
case 499/*CALL_PREFIX_FREEOP*/: return 1;
case 522/*CALL_INFIX_FREEOP*/: return 1;
case 521/*CALL_INFIX_POWER*/: return 1;
case 517/*CALL_INFIX_TIMES*/: return 1;
case 518/*CALL_INFIX_INT_DIV*/: return 1;
case 519/*CALL_INFIX_INT_REM*/: return 1;
case 520/*CALL_INFIX_DIV*/: return 1;
case 516/*CALL_INFIX_PLUS*/: return 1;
case 382/*CALL_INFIX_MINUS*/: return 1;
case 512/*CALL_INFIX_LE*/: return 1;
case 513/*CALL_INFIX_GE*/: return 1;
case 514/*CALL_INFIX_LT*/: return 1;
case 515/*CALL_INFIX_GT*/: return 1;
case 410/*CALL_INFIX_AND_THEN*/: return 1;
case 511/*CALL_INFIX_AND*/: return 1;
case 508/*CALL_INFIX_OR_ELSE*/: return 1;
case 509/*CALL_INFIX_OR*/: return 1;
case 510/*CALL_INFIX_XOR*/: return 1;
case 507/*CALL_INFIX_IMPLIES*/: return 1;
case 422/*STATIC_CALL_0_C*/: return 1;
}
return 0;
}/*--*/

int can_assign_to412_from348(T0* expression){
/* CREATE_INSTRUCTION ?:= CODE */
if (expression == NULL) return 1;
switch (expression->id) {
case 412/*CREATE_INSTRUCTION*/: return 1;
case 419/*RAW_CREATE_INSTRUCTION*/: return 1;
}
return 0;
}/*--*/

int can_assign_to347_from348(T0* expression){
/* EXPRESSION ?:= CODE */
if (expression == NULL) return 1;
switch (expression->id) {
case 388/*MANIFEST_STRING*/: return 1;
case 526/*OLD_MANIFEST_ARRAY*/: return 1;
case 495/*CALL_PREFIX_NOT*/: return 1;
case 409/*ASSIGNMENT_TEST*/: return 1;
case 481/*OPEN_OPERAND*/: return 1;
case 379/*INTEGER_CONSTANT*/: return 1;
case 482/*REAL_CONSTANT*/: return 1;
case 483/*MANIFEST_GENERIC*/: return 1;
case 355/*FUNCTION_CALL_0*/: return 1;
case 358/*FUNCTION_CALL_1*/: return 1;
case 360/*FUNCTION_CALL_N*/: return 1;
case 497/*CALL_PREFIX_PLUS*/: return 1;
case 498/*CALL_PREFIX_MINUS*/: return 1;
case 499/*CALL_PREFIX_FREEOP*/: return 1;
case 487/*MANIFEST_TUPLE*/: return 1;
case 393/*E_TRUE*/: return 1;
case 462/*E_FALSE*/: return 1;
case 469/*CHARACTER_CONSTANT*/: return 1;
case 488/*PRECURSOR_EXPRESSION*/: return 1;
case 523/*FAKE_TARGET*/: return 1;
case 524/*CREATE_EXPRESSION*/: return 1;
case 428/*ASSERTION*/: return 1;
case 377/*IMPLICIT_CURRENT*/: return 1;
case 472/*LOOP_VARIANT*/: return 1;
case 371/*RESULT*/: return 1;
case 491/*WRITTEN_CURRENT*/: return 1;
case 490/*AGENT_CREATION*/: return 1;
case 463/*EXPRESSION_WITH_COMMENT*/: return 1;
case 404/*E_VOID*/: return 1;
case 500/*E_OLD*/: return 1;
case 522/*CALL_INFIX_FREEOP*/: return 1;
case 521/*CALL_INFIX_POWER*/: return 1;
case 517/*CALL_INFIX_TIMES*/: return 1;
case 518/*CALL_INFIX_INT_DIV*/: return 1;
case 519/*CALL_INFIX_INT_REM*/: return 1;
case 520/*CALL_INFIX_DIV*/: return 1;
case 516/*CALL_INFIX_PLUS*/: return 1;
case 382/*CALL_INFIX_MINUS*/: return 1;
case 405/*BUILT_IN_EQ_NEQ*/: return 1;
case 512/*CALL_INFIX_LE*/: return 1;
case 513/*CALL_INFIX_GE*/: return 1;
case 514/*CALL_INFIX_LT*/: return 1;
case 515/*CALL_INFIX_GT*/: return 1;
case 410/*CALL_INFIX_AND_THEN*/: return 1;
case 511/*CALL_INFIX_AND*/: return 1;
case 508/*CALL_INFIX_OR_ELSE*/: return 1;
case 509/*CALL_INFIX_OR*/: return 1;
case 510/*CALL_INFIX_XOR*/: return 1;
case 507/*CALL_INFIX_IMPLIES*/: return 1;
case 464/*ADDRESS_OF*/: return 1;
case 365/*ARGUMENT_NAME_REF*/: return 1;
case 418/*WRITABLE_ATTRIBUTE_NAME*/: return 1;
case 401/*LOCAL_NAME_REF*/: return 1;
case 535/*NON_VOID_NO_DISPATCH*/: return 1;
case 660/*COMPOUND_EXPRESSION*/: return 1;
case 662/*CREATE_WRITABLE*/: return 1;
case 663/*CLOSED_OPERAND*/: return 1;
case 363/*FAKE_ARGUMENT*/: return 1;
case 654/*NO_DISPATCH*/: return 1;
case 658/*DYNAMIC_DISPATCH_TEMPORARY1*/: return 1;
case 657/*DYNAMIC_DISPATCH_TEMPORARY2*/: return 1;
case 569/*VOID_CALL*/: return 1;
case 659/*DYNAMIC_DISPATCH_TEMPORARY1_ID*/: return 1;
case 656/*INTERNAL_LOCAL2*/: return 1;
case 652/*NATURAL_CONSTANT*/: return 1;
case 653/*NULL_POINTER*/: return 1;
case 532/*IMPLICIT_CAST*/: return 1;
case 664/*AGENT_EXPRESSION*/: return 1;
case 422/*STATIC_CALL_0_C*/: return 1;
case 373/*GENERATOR_GENERATING_TYPE*/: return 1;
case 655/*NATIVE_ARRAY_ITEM*/: return 1;
case 661/*FAKE_TUPLE*/: return 1;
}
return 0;
}/*--*/

int can_assign_to379_from381(T0* expression){
/* INTEGER_CONSTANT ?:= MANIFEST_EXPRESSION */
if (expression == NULL) return 1;
switch (expression->id) {
case 379/*INTEGER_CONSTANT*/: return 1;
}
return 0;
}/*--*/

int can_assign_to547_from548(T0* expression){
/* PATH_NAME_NOTATION ?:= DIRECTORY_NOTATION */
if (expression == NULL) return 1;
switch (expression->id) {
case 546/*UNIX_DIRECTORY_NOTATION*/: return 1;
case 550/*WINDOWS_DIRECTORY_NOTATION*/: return 1;
}
return 0;
}/*--*/

int can_assign_to551_from548(T0* expression){
/* MACINTOSH_DIRECTORY_NOTATION ?:= DIRECTORY_NOTATION */
if (expression == NULL) return 1;
switch (expression->id) {
case 551/*MACINTOSH_DIRECTORY_NOTATION*/: return 1;
}
return 0;
}/*--*/

int can_assign_to553_from548(T0* expression){
/* OPENVMS_DIRECTORY_NOTATION ?:= DIRECTORY_NOTATION */
if (expression == NULL) return 1;
switch (expression->id) {
case 553/*OPENVMS_DIRECTORY_NOTATION*/: return 1;
}
return 0;
}/*--*/

int can_assign_to550_from548(T0* expression){
/* WINDOWS_DIRECTORY_NOTATION ?:= DIRECTORY_NOTATION */
if (expression == NULL) return 1;
switch (expression->id) {
case 550/*WINDOWS_DIRECTORY_NOTATION*/: return 1;
}
return 0;
}/*--*/

int can_assign_to546_from548(T0* expression){
/* UNIX_DIRECTORY_NOTATION ?:= DIRECTORY_NOTATION */
if (expression == NULL) return 1;
switch (expression->id) {
case 546/*UNIX_DIRECTORY_NOTATION*/: return 1;
}
return 0;
}/*--*/

int can_assign_to552_from548(T0* expression){
/* AMIGA_DIRECTORY_NOTATION ?:= DIRECTORY_NOTATION */
if (expression == NULL) return 1;
switch (expression->id) {
case 552/*AMIGA_DIRECTORY_NOTATION*/: return 1;
}
return 0;
}/*--*/

int can_assign_to554_from548(T0* expression){
/* CYGWIN_DIRECTORY_NOTATION ?:= DIRECTORY_NOTATION */
if (expression == NULL) return 1;
switch (expression->id) {
case 554/*CYGWIN_DIRECTORY_NOTATION*/: return 1;
}
return 0;
}/*--*/

int can_assign_to505_from372(T0* expression){
/* LIKE_ARGUMENT_TYPE_MARK ?:= TYPE_MARK */
if (expression == NULL) return 1;
switch (expression->id) {
case 505/*LIKE_ARGUMENT_TYPE_MARK*/: return 1;
}
return 0;
}/*--*/

int can_assign_to442_from372(T0* expression){
/* REAL_TYPE_MARK ?:= TYPE_MARK */
if (expression == NULL) return 1;
switch (expression->id) {
case 442/*REAL_TYPE_MARK*/: return 1;
}
return 0;
}/*--*/

int can_assign_to468_from372(T0* expression){
/* WEAK_REFERENCE_TYPE_MARK ?:= TYPE_MARK */
if (expression == NULL) return 1;
switch (expression->id) {
case 468/*WEAK_REFERENCE_TYPE_MARK*/: return 1;
}
return 0;
}/*--*/

int can_assign_to411_from372(T0* expression){
/* CLASS_TYPE_MARK ?:= TYPE_MARK */
if (expression == NULL) return 1;
switch (expression->id) {
case 411/*CLASS_TYPE_MARK*/: return 1;
}
return 0;
}/*--*/

int can_assign_to415_from372(T0* expression){
/* INTEGER_TYPE_MARK ?:= TYPE_MARK */
if (expression == NULL) return 1;
switch (expression->id) {
case 415/*INTEGER_TYPE_MARK*/: return 1;
}
return 0;
}/*--*/

int can_assign_to477_from475(T0* expression){
/* NATIVE_C_PLUS_PLUS ?:= NATIVE */
if (expression == NULL) return 1;
switch (expression->id) {
case 477/*NATIVE_C_PLUS_PLUS*/: return 1;
}
return 0;
}/*--*/

int can_assign_to462_from347(T0* expression){
/* E_FALSE ?:= EXPRESSION */
if (expression == NULL) return 1;
switch (expression->id) {
case 462/*E_FALSE*/: return 1;
}
return 0;
}/*--*/

int can_assign_to482_from347(T0* expression){
/* REAL_CONSTANT ?:= EXPRESSION */
if (expression == NULL) return 1;
switch (expression->id) {
case 482/*REAL_CONSTANT*/: return 1;
}
return 0;
}/*--*/

int can_assign_to487_from347(T0* expression){
/* MANIFEST_TUPLE ?:= EXPRESSION */
if (expression == NULL) return 1;
switch (expression->id) {
case 487/*MANIFEST_TUPLE*/: return 1;
}
return 0;
}/*--*/

int can_assign_to532_from347(T0* expression){
/* IMPLICIT_CAST ?:= EXPRESSION */
if (expression == NULL) return 1;
switch (expression->id) {
case 532/*IMPLICIT_CAST*/: return 1;
}
return 0;
}/*--*/

int can_assign_to357_from347(T0* expression){
/* FUNCTION_CALL ?:= EXPRESSION */
if (expression == NULL) return 1;
switch (expression->id) {
case 495/*CALL_PREFIX_NOT*/: return 1;
case 355/*FUNCTION_CALL_0*/: return 1;
case 358/*FUNCTION_CALL_1*/: return 1;
case 360/*FUNCTION_CALL_N*/: return 1;
case 497/*CALL_PREFIX_PLUS*/: return 1;
case 498/*CALL_PREFIX_MINUS*/: return 1;
case 499/*CALL_PREFIX_FREEOP*/: return 1;
case 522/*CALL_INFIX_FREEOP*/: return 1;
case 521/*CALL_INFIX_POWER*/: return 1;
case 517/*CALL_INFIX_TIMES*/: return 1;
case 518/*CALL_INFIX_INT_DIV*/: return 1;
case 519/*CALL_INFIX_INT_REM*/: return 1;
case 520/*CALL_INFIX_DIV*/: return 1;
case 516/*CALL_INFIX_PLUS*/: return 1;
case 382/*CALL_INFIX_MINUS*/: return 1;
case 512/*CALL_INFIX_LE*/: return 1;
case 513/*CALL_INFIX_GE*/: return 1;
case 514/*CALL_INFIX_LT*/: return 1;
case 515/*CALL_INFIX_GT*/: return 1;
case 410/*CALL_INFIX_AND_THEN*/: return 1;
case 511/*CALL_INFIX_AND*/: return 1;
case 508/*CALL_INFIX_OR_ELSE*/: return 1;
case 509/*CALL_INFIX_OR*/: return 1;
case 510/*CALL_INFIX_XOR*/: return 1;
case 507/*CALL_INFIX_IMPLIES*/: return 1;
case 422/*STATIC_CALL_0_C*/: return 1;
}
return 0;
}/*--*/

int can_assign_to535_from347(T0* expression){
/* NON_VOID_NO_DISPATCH ?:= EXPRESSION */
if (expression == NULL) return 1;
switch (expression->id) {
case 535/*NON_VOID_NO_DISPATCH*/: return 1;
}
return 0;
}/*--*/

int can_assign_to481_from347(T0* expression){
/* OPEN_OPERAND ?:= EXPRESSION */
if (expression == NULL) return 1;
switch (expression->id) {
case 481/*OPEN_OPERAND*/: return 1;
}
return 0;
}/*--*/

int can_assign_to469_from347(T0* expression){
/* CHARACTER_CONSTANT ?:= EXPRESSION */
if (expression == NULL) return 1;
switch (expression->id) {
case 469/*CHARACTER_CONSTANT*/: return 1;
}
return 0;
}/*--*/

int can_assign_to401_from347(T0* expression){
/* LOCAL_NAME_REF ?:= EXPRESSION */
if (expression == NULL) return 1;
switch (expression->id) {
case 401/*LOCAL_NAME_REF*/: return 1;
}
return 0;
}/*--*/

int can_assign_to463_from347(T0* expression){
/* EXPRESSION_WITH_COMMENT ?:= EXPRESSION */
if (expression == NULL) return 1;
switch (expression->id) {
case 463/*EXPRESSION_WITH_COMMENT*/: return 1;
}
return 0;
}/*--*/

int can_assign_to523_from347(T0* expression){
/* FAKE_TARGET ?:= EXPRESSION */
if (expression == NULL) return 1;
switch (expression->id) {
case 523/*FAKE_TARGET*/: return 1;
}
return 0;
}/*--*/

int can_assign_to393_from347(T0* expression){
/* E_TRUE ?:= EXPRESSION */
if (expression == NULL) return 1;
switch (expression->id) {
case 393/*E_TRUE*/: return 1;
}
return 0;
}/*--*/

int can_assign_to379_from347(T0* expression){
/* INTEGER_CONSTANT ?:= EXPRESSION */
if (expression == NULL) return 1;
switch (expression->id) {
case 379/*INTEGER_CONSTANT*/: return 1;
}
return 0;
}/*--*/

int can_assign_to394_from347(T0* expression){
/* BOOLEAN_CONSTANT ?:= EXPRESSION */
if (expression == NULL) return 1;
switch (expression->id) {
case 393/*E_TRUE*/: return 1;
case 462/*E_FALSE*/: return 1;
}
return 0;
}/*--*/

int can_assign_to388_from347(T0* expression){
/* MANIFEST_STRING ?:= EXPRESSION */
if (expression == NULL) return 1;
switch (expression->id) {
case 388/*MANIFEST_STRING*/: return 1;
}
return 0;
}/*--*/

int can_assign_to653_from347(T0* expression){
/* NULL_POINTER ?:= EXPRESSION */
if (expression == NULL) return 1;
switch (expression->id) {
case 653/*NULL_POINTER*/: return 1;
}
return 0;
}/*--*/

#ifdef __cplusplus
}
#endif
