# Beginning of parallelizable section
gcc -pipe -O2 -c -x c compile_to_c135.c
gcc -pipe -O2 -c -x c compile_to_c134.c
gcc -pipe -O2 -c -x c compile_to_c133.c
gcc -pipe -O2 -c -x c compile_to_c132.c
gcc -pipe -O2 -c -x c compile_to_c131.c
gcc -pipe -O2 -c -x c compile_to_c130.c
gcc -pipe -O2 -c -x c compile_to_c129.c
gcc -pipe -O2 -c -x c compile_to_c128.c
gcc -pipe -O2 -c -x c compile_to_c127.c
gcc -pipe -O2 -c -x c compile_to_c126.c
gcc -pipe -O2 -c -x c compile_to_c125.c
gcc -pipe -O2 -c -x c compile_to_c124.c
gcc -pipe -O2 -c -x c compile_to_c123.c
gcc -pipe -O2 -c -x c compile_to_c122.c
gcc -pipe -O2 -c -x c compile_to_c121.c
gcc -pipe -O2 -c -x c compile_to_c120.c
gcc -pipe -O2 -c -x c compile_to_c119.c
gcc -pipe -O2 -c -x c compile_to_c118.c
gcc -pipe -O2 -c -x c compile_to_c117.c
gcc -pipe -O2 -c -x c compile_to_c116.c
gcc -pipe -O2 -c -x c compile_to_c115.c
gcc -pipe -O2 -c -x c compile_to_c114.c
gcc -pipe -O2 -c -x c compile_to_c113.c
gcc -pipe -O2 -c -x c compile_to_c112.c
gcc -pipe -O2 -c -x c compile_to_c111.c
gcc -pipe -O2 -c -x c compile_to_c110.c
gcc -pipe -O2 -c -x c compile_to_c109.c
gcc -pipe -O2 -c -x c compile_to_c108.c
gcc -pipe -O2 -c -x c compile_to_c107.c
gcc -pipe -O2 -c -x c compile_to_c106.c
gcc -pipe -O2 -c -x c compile_to_c105.c
gcc -pipe -O2 -c -x c compile_to_c104.c
gcc -pipe -O2 -c -x c compile_to_c103.c
gcc -pipe -O2 -c -x c compile_to_c102.c
gcc -pipe -O2 -c -x c compile_to_c101.c
gcc -pipe -O2 -c -x c compile_to_c100.c
gcc -pipe -O2 -c -x c compile_to_c99.c
gcc -pipe -O2 -c -x c compile_to_c98.c
gcc -pipe -O2 -c -x c compile_to_c97.c
gcc -pipe -O2 -c -x c compile_to_c96.c
gcc -pipe -O2 -c -x c compile_to_c95.c
gcc -pipe -O2 -c -x c compile_to_c94.c
gcc -pipe -O2 -c -x c compile_to_c93.c
gcc -pipe -O2 -c -x c compile_to_c92.c
gcc -pipe -O2 -c -x c compile_to_c91.c
gcc -pipe -O2 -c -x c compile_to_c90.c
gcc -pipe -O2 -c -x c compile_to_c89.c
gcc -pipe -O2 -c -x c compile_to_c88.c
gcc -pipe -O2 -c -x c compile_to_c87.c
gcc -pipe -O2 -c -x c compile_to_c86.c
gcc -pipe -O2 -c -x c compile_to_c85.c
gcc -pipe -O2 -c -x c compile_to_c84.c
gcc -pipe -O2 -c -x c compile_to_c83.c
gcc -pipe -O2 -c -x c compile_to_c82.c
gcc -pipe -O2 -c -x c compile_to_c81.c
gcc -pipe -O2 -c -x c compile_to_c80.c
gcc -pipe -O2 -c -x c compile_to_c79.c
gcc -pipe -O2 -c -x c compile_to_c78.c
gcc -pipe -O2 -c -x c compile_to_c77.c
gcc -pipe -O2 -c -x c compile_to_c76.c
gcc -pipe -O2 -c -x c compile_to_c75.c
gcc -pipe -O2 -c -x c compile_to_c74.c
gcc -pipe -O2 -c -x c compile_to_c73.c
gcc -pipe -O2 -c -x c compile_to_c72.c
gcc -pipe -O2 -c -x c compile_to_c71.c
gcc -pipe -O2 -c -x c compile_to_c70.c
gcc -pipe -O2 -c -x c compile_to_c69.c
gcc -pipe -O2 -c -x c compile_to_c68.c
gcc -pipe -O2 -c -x c compile_to_c67.c
gcc -pipe -O2 -c -x c compile_to_c66.c
gcc -pipe -O2 -c -x c compile_to_c65.c
gcc -pipe -O2 -c -x c compile_to_c64.c
gcc -pipe -O2 -c -x c compile_to_c63.c
gcc -pipe -O2 -c -x c compile_to_c62.c
gcc -pipe -O2 -c -x c compile_to_c61.c
gcc -pipe -O2 -c -x c compile_to_c60.c
gcc -pipe -O2 -c -x c compile_to_c59.c
gcc -pipe -O2 -c -x c compile_to_c58.c
gcc -pipe -O2 -c -x c compile_to_c57.c
gcc -pipe -O2 -c -x c compile_to_c56.c
gcc -pipe -O2 -c -x c compile_to_c55.c
gcc -pipe -O2 -c -x c compile_to_c54.c
gcc -pipe -O2 -c -x c compile_to_c53.c
gcc -pipe -O2 -c -x c compile_to_c52.c
gcc -pipe -O2 -c -x c compile_to_c51.c
gcc -pipe -O2 -c -x c compile_to_c50.c
gcc -pipe -O2 -c -x c compile_to_c49.c
gcc -pipe -O2 -c -x c compile_to_c48.c
gcc -pipe -O2 -c -x c compile_to_c47.c
gcc -pipe -O2 -c -x c compile_to_c46.c
gcc -pipe -O2 -c -x c compile_to_c45.c
gcc -pipe -O2 -c -x c compile_to_c44.c
gcc -pipe -O2 -c -x c compile_to_c43.c
gcc -pipe -O2 -c -x c compile_to_c42.c
gcc -pipe -O2 -c -x c compile_to_c41.c
gcc -pipe -O2 -c -x c compile_to_c40.c
gcc -pipe -O2 -c -x c compile_to_c39.c
gcc -pipe -O2 -c -x c compile_to_c38.c
gcc -pipe -O2 -c -x c compile_to_c37.c
gcc -pipe -O2 -c -x c compile_to_c36.c
gcc -pipe -O2 -c -x c compile_to_c35.c
gcc -pipe -O2 -c -x c compile_to_c34.c
gcc -pipe -O2 -c -x c compile_to_c33.c
gcc -pipe -O2 -c -x c compile_to_c32.c
gcc -pipe -O2 -c -x c compile_to_c31.c
gcc -pipe -O2 -c -x c compile_to_c30.c
gcc -pipe -O2 -c -x c compile_to_c29.c
gcc -pipe -O2 -c -x c compile_to_c28.c
gcc -pipe -O2 -c -x c compile_to_c27.c
gcc -pipe -O2 -c -x c compile_to_c26.c
gcc -pipe -O2 -c -x c compile_to_c25.c
gcc -pipe -O2 -c -x c compile_to_c24.c
gcc -pipe -O2 -c -x c compile_to_c23.c
gcc -pipe -O2 -c -x c compile_to_c22.c
gcc -pipe -O2 -c -x c compile_to_c21.c
gcc -pipe -O2 -c -x c compile_to_c20.c
gcc -pipe -O2 -c -x c compile_to_c19.c
gcc -pipe -O2 -c -x c compile_to_c18.c
gcc -pipe -O2 -c -x c compile_to_c17.c
gcc -pipe -O2 -c -x c compile_to_c16.c
gcc -pipe -O2 -c -x c compile_to_c15.c
gcc -pipe -O2 -c -x c compile_to_c14.c
gcc -pipe -O2 -c -x c compile_to_c13.c
gcc -pipe -O2 -c -x c compile_to_c12.c
gcc -pipe -O2 -c -x c compile_to_c11.c
gcc -pipe -O2 -c -x c compile_to_c10.c
gcc -pipe -O2 -c -x c compile_to_c9.c
gcc -pipe -O2 -c -x c compile_to_c8.c
gcc -pipe -O2 -c -x c compile_to_c7.c
gcc -pipe -O2 -c -x c compile_to_c6.c
gcc -pipe -O2 -c -x c compile_to_c5.c
gcc -pipe -O2 -c -x c compile_to_c4.c
gcc -pipe -O2 -c -x c compile_to_c3.c
gcc -pipe -O2 -c -x c compile_to_c2.c
gcc -pipe -O2 -c -x c compile_to_c1.c
# End of parallelizable section
gcc -Xlinker -no-as-needed compile_to_c1.o compile_to_c2.o compile_to_c3.o compile_to_c4.o compile_to_c5.o compile_to_c6.o compile_to_c7.o compile_to_c8.o compile_to_c9.o compile_to_c10.o compile_to_c11.o compile_to_c12.o compile_to_c13.o compile_to_c14.o compile_to_c15.o compile_to_c16.o compile_to_c17.o compile_to_c18.o compile_to_c19.o compile_to_c20.o compile_to_c21.o compile_to_c22.o compile_to_c23.o compile_to_c24.o compile_to_c25.o compile_to_c26.o compile_to_c27.o compile_to_c28.o compile_to_c29.o compile_to_c30.o compile_to_c31.o compile_to_c32.o compile_to_c33.o compile_to_c34.o compile_to_c35.o compile_to_c36.o compile_to_c37.o compile_to_c38.o compile_to_c39.o compile_to_c40.o compile_to_c41.o compile_to_c42.o compile_to_c43.o compile_to_c44.o compile_to_c45.o compile_to_c46.o compile_to_c47.o compile_to_c48.o compile_to_c49.o compile_to_c50.o compile_to_c51.o compile_to_c52.o compile_to_c53.o compile_to_c54.o compile_to_c55.o compile_to_c56.o compile_to_c57.o compile_to_c58.o compile_to_c59.o compile_to_c60.o compile_to_c61.o compile_to_c62.o compile_to_c63.o compile_to_c64.o compile_to_c65.o compile_to_c66.o compile_to_c67.o compile_to_c68.o compile_to_c69.o compile_to_c70.o compile_to_c71.o compile_to_c72.o compile_to_c73.o compile_to_c74.o compile_to_c75.o compile_to_c76.o compile_to_c77.o compile_to_c78.o compile_to_c79.o compile_to_c80.o compile_to_c81.o compile_to_c82.o compile_to_c83.o compile_to_c84.o compile_to_c85.o compile_to_c86.o compile_to_c87.o compile_to_c88.o compile_to_c89.o compile_to_c90.o compile_to_c91.o compile_to_c92.o compile_to_c93.o compile_to_c94.o compile_to_c95.o compile_to_c96.o compile_to_c97.o compile_to_c98.o compile_to_c99.o compile_to_c100.o compile_to_c101.o compile_to_c102.o compile_to_c103.o compile_to_c104.o compile_to_c105.o compile_to_c106.o compile_to_c107.o compile_to_c108.o compile_to_c109.o compile_to_c110.o compile_to_c111.o compile_to_c112.o compile_to_c113.o compile_to_c114.o compile_to_c115.o compile_to_c116.o compile_to_c117.o compile_to_c118.o compile_to_c119.o compile_to_c120.o compile_to_c121.o compile_to_c122.o compile_to_c123.o compile_to_c124.o compile_to_c125.o compile_to_c126.o compile_to_c127.o compile_to_c128.o compile_to_c129.o compile_to_c130.o compile_to_c131.o compile_to_c132.o compile_to_c133.o compile_to_c134.o compile_to_c135.o -x none
strip a.out
