#ifdef __cplusplus
extern "C" {
#endif
/*
ANSI C code generated by 
Liberty Eiffel The GNU Eiffel Compiler, Eiffel tools and libraries
    release 2013.11 (Charles Adler, Jr.)

Copyright (C), 2011-2013 - C.ADRIAN, P.REDAELLI, R.MACK
    http://www.liberty-eiffel.org

Original SmartEiffel code:
Copyright (C), 1994-2002 - INRIA - LORIA - ESIAL UHP Nancy 1 - FRANCE
Copyright (C), 2003-2005 - INRIA - LORIA - IUT Charlemagne Nancy 2 - FRANCE
D.COLNET, P.RIBET, C.ADRIAN, V.CROIZIER, F.MERIZEN
    http://smarteiffel.loria.fr
C Compiler options used: -pipe -O2 -fno-gcse
*/

#ifdef __cplusplus
}
#endif
#include "compile_to_c.h"
#ifdef __cplusplus
extern "C" {
#endif

/*ECHO*/void r124put_line(T124*C,T0*a1){
if((/*RF2:is_verbose*/(C)->_is_verbose/*3pip*//*:RF2*/)){
/*[inspectDynamicDispatch*/
switch((((T0*)((/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)))->id)){
case 68:
/*RF3:put_line*/r68put_line(((T68*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),a1);
/*:RF3*/break;
case 77:
/*RF3:put_line*/r77put_line(((T77*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),a1);
/*:RF3*/break;
case 80:
/*RF3:put_line*/r80put_line(((T80*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),a1);
/*:RF3*/break;
case 457:
/*RF3:put_line*/r457put_line(((T457*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),a1);
/*:RF3*/break;
case 651:
/*RF3:put_line*/r651put_line(((T651*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),a1);
/*:RF3*/break;
case 852:
/*RF3:put_line*/r852put_line(((T852*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),a1);
/*:RF3*/break;
default:;
/*RF3:put_line*/r855put_line(((T855*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),a1);
/*:RF3*/}
/*inspect]*/
/*[inspectDynamicDispatch*/
switch((((T0*)((/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)))->id)){
case 68:
/*RF3:filtered_flush*/r68filtered_flush(((T68*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
case 77:
/*RF3:filtered_flush*/r68filtered_flush((T68*)(/*RF6:std_output*/r77std_output()/*:RF6*/));
/*:RF3*/break;
case 80:
/*RF3:filtered_flush*/r80filtered_flush();
/*:RF3*/break;
case 457:
/*RF3:filtered_flush*/r457filtered_flush(((T457*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
case 651:
/*RF3:filtered_flush*/r651filtered_flush(((T651*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
case 852:
/*RF3:filtered_flush*/r852filtered_flush(((T852*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
default:;
/*RF3:filtered_flush*/r855filtered_flush(((T855*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)));
/*:RF3*/}
/*inspect]*/
}
}/*--*/

/*ECHO*/void r124make(T124*C){
/*SFN*/(C->_output_stream/*3pip*/)=/*RF6:std_output*/r124std_output()/*:RF6*/;
/*SFN*/(C->_error_stream/*3pip*/)=oBC17std_error;
}/*--*/

/*ECHO*/void r124tfr_connect_or_exit(T124*C,T0*a1,T0*a2){
/*RF3:tfr_connect*/r124tfr_connect(C,a1,a2);
/*:RF3*/if((((/*RF2:path*/(((T100*)a1))->_path/*iiipnpcpp*//*:RF2*/))!=((void*)((void*)0)))==(0)){
/*RF3:w_put_string*/r124w_put_string(C,ms121_300594Abc124A);
/*:RF3*//*RF3:w_put_string*/r124w_put_string(C,a2);
/*:RF3*//*RF3:w_put_string*/r124w_put_string(C,se_string(13,s124_1680762272A));
/*:RF3*//*RF7:die_with_code*/se_die(INT32_C(1));
/*:RF7*/}
}/*--*/

/*ECHO*/void r124before_exit_close(T124*C){
int _file_tools=0;
/*[inspectDynamicDispatch*/
switch((((T0*)((/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)))->id)){
case 68:
/*RF3:filtered_flush*/r68filtered_flush(((T68*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
case 77:
/*RF3:filtered_flush*/r68filtered_flush((T68*)(/*RF6:std_output*/r77std_output()/*:RF6*/));
/*:RF3*/break;
case 80:
/*RF3:filtered_flush*/r80filtered_flush();
/*:RF3*/break;
case 457:
/*RF3:filtered_flush*/r457filtered_flush(((T457*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
case 651:
/*RF3:filtered_flush*/r651filtered_flush(((T651*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
case 852:
/*RF3:filtered_flush*/r852filtered_flush(((T852*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
default:;
/*RF3:filtered_flush*/r855filtered_flush(((T855*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)));
/*:RF3*/}
/*inspect]*/
/*[inspectDynamicDispatch*/
switch((((T0*)((/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)))->id)){
case 68:
/*RF3:filtered_flush*/r68filtered_flush(((T68*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
case 77:
/*RF3:filtered_flush*/r68filtered_flush((T68*)(/*RF6:std_output*/r77std_output()/*:RF6*/));
/*:RF3*/break;
case 80:
/*RF3:filtered_flush*/r80filtered_flush();
/*:RF3*/break;
case 457:
/*RF3:filtered_flush*/r457filtered_flush(((T457*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
case 651:
/*RF3:filtered_flush*/r651filtered_flush(((T651*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
case 852:
/*RF3:filtered_flush*/r852filtered_flush(((T852*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
default:;
/*RF3:filtered_flush*/r855filtered_flush(((T855*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)));
/*:RF3*/}
/*inspect]*/
if(((/*RF2:output_state*/(C)->_output_state/*3pip*//*:RF2*/))==(INT32_C(2))){
/*[inspectDynamicDispatch*/
switch((((T0*)((/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)))->id)){
case 68:
(/*RF2:filter*/(((T68*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)))->_filter/*Tinip*//*:RF2*/)=(void*)0;
break;
case 77:
/*RF3:disconnect*/r77disconnect();
/*:RF3*/break;
case 80:
(/*RF2:filter*/(((T80*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)))->_filter/*Tp*//*:RF2*/)=(void*)0;
break;
case 457:
/*RF3:disconnect*/r457disconnect(((T457*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
case 651:
/*RF3:disconnect*/r651disconnect(((T651*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
case 852:
/*RF3:disconnect*/r852disconnect(((T852*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
default:;
/*RF3:disconnect*/r855disconnect(((T855*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)));
/*:RF3*/}
/*inspect]*/
/*SFN*/(C->_output_stream/*3pip*/)=/*RF6:std_output*/r124std_output()/*:RF6*/;
if(/*RF4:is_empty*/r289is_empty((/*RF2:output_path*/(C)->_output_path/*3pip*//*:RF2*/))/*:RF4*/){
/*RF3:delete*/r289delete((/*RF2:output_path*/(C)->_output_path/*3pip*//*:RF2*/));
/*:RF3*/}
/*SFN*/(C->_output_state/*3pip*/)=INT32_C(0);
/*SFN*/(C->_output_stream/*3pip*/)=/*RF6:std_output*/r124std_output()/*:RF6*/;
/*SFN*/(C->_error_stream/*3pip*/)=oBC17std_error;
}
}/*--*/

/*ECHO*/void r124w_put_string(T124*C,T0*a1){
/*[inspectDynamicDispatch*/
switch((((T0*)((/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)))->id)){
case 68:
/*RF3:put_string*/r68put_string(((T68*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)),a1);
/*:RF3*/break;
case 77:
/*RF3:put_string*/r77put_string(((T77*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)),a1);
/*:RF3*/break;
case 80:
/*RF3:put_string*/r80put_string(((T80*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)),a1);
/*:RF3*/break;
case 457:
/*RF3:put_string*/r457put_string(((T457*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)),a1);
/*:RF3*/break;
case 651:
/*RF3:put_string*/r651put_string(((T651*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)),a1);
/*:RF3*/break;
case 852:
/*RF3:put_string*/r852put_string(((T852*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)),a1);
/*:RF3*/break;
default:;
/*RF3:put_string*/r855put_string(((T855*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)),a1);
/*:RF3*/}
/*inspect]*/
/*[inspectDynamicDispatch*/
switch((((T0*)((/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)))->id)){
case 68:
/*RF3:filtered_flush*/r68filtered_flush(((T68*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
case 77:
/*RF3:filtered_flush*/r68filtered_flush((T68*)(/*RF6:std_output*/r77std_output()/*:RF6*/));
/*:RF3*/break;
case 80:
/*RF3:filtered_flush*/r80filtered_flush();
/*:RF3*/break;
case 457:
/*RF3:filtered_flush*/r457filtered_flush(((T457*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
case 651:
/*RF3:filtered_flush*/r651filtered_flush(((T651*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
case 852:
/*RF3:filtered_flush*/r852filtered_flush(((T852*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
default:;
/*RF3:filtered_flush*/r855filtered_flush(((T855*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)));
/*:RF3*/}
/*inspect]*/
}/*--*/

/*ECHO*/void r124file_renaming(T124*C,T0*a1,T0*a2){
/*RF3:put_string*/r124put_string(C,ms124_210141519Abc124A);
/*:RF3*//*RF3:put_string*/r124put_string(C,a1);
/*:RF3*//*RF3:put_string*/r124put_string(C,ms124_141444Abc124A);
/*:RF3*//*RF3:put_string*/r124put_string(C,a2);
/*:RF3*//*RF3:put_string*/r124put_string(C,ms30_1090Abc124D);
/*:RF3*//*RF3:rename_to*/((/*UT*/(void)(create289())),r289rename_to(a1,a2));
/*:RF3*/}/*--*/

/*ECHO*/void r124tfr_connect(T124*C,T0*a1,T0*a2){
/*RF3:put_string*/r124put_string(C,ms124_27561173Abc124A);
/*:RF3*//*RF3:put_string*/r124put_string(C,a2);
/*:RF3*//*RF3:put_string*/r124put_string(C,ms30_1090Abc124B);
/*:RF3*//*RF3:connect_to*/r100connect_to(((T100*)a1),a2);
/*:RF3*/}/*--*/

/*ECHO*/void r124put_time(T124*C,T11 a1){
T11 _ts=0;
T11 _d=0;
T11 _h=0;
T11 _m=0;
T11 _s=0;
T11 _u=0;
if((/*RF2:is_verbose*/(C)->_is_verbose/*3pip*//*:RF2*/)){
_ts=a1;
_h=/*RF4://*/r11_ix_4747(_ts,INT64_C(3600000000))/*:RF4*/;
_ts=/*RF8:-*/((int64_t)(_ts))-(/*RF8:**/((int64_t)(_h))*(INT64_C(3600000000))/*:RF8*/)/*:RF8*/;
_m=/*RF4://*/r11_ix_4747(_ts,INT64_C(60000000))/*:RF4*/;
_ts=/*RF8:-*/((int64_t)(_ts))-(/*RF8:**/((int64_t)(_m))*(INT64_C(60000000))/*:RF8*/)/*:RF8*/;
_s=/*RF4://*/r11_ix_4747(_ts,INT64_C(1000000))/*:RF4*/;
_ts=/*RF8:-*/((int64_t)(_ts))-(/*RF8:**/((int64_t)(_s))*(INT64_C(1000000))/*:RF8*/)/*:RF8*/;
_u=_ts;
if(/*RF8:>*/((int64_t)(_h))>(INT64_C(0))/*:RF8*/){
if(/*RF8:>*/((int64_t)(_h))>(INT64_C(24))/*:RF8*/){
_d=/*RF4://*/r11_ix_4747(_h,INT64_C(24))/*:RF4*/;
_h=/*RF4:\\*/r11_ix_9292(_h,INT64_C(24))/*:RF4*/;
/*RF3:put_padded_num*/r124put_padded_num(C,_d,INT32_C(1));
/*:RF3*//*[inspectDynamicDispatch*/
switch((((T0*)((/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)))->id)){
case 68:
/*RF3:put_string*/r68put_string(((T68*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),ms124_7106Abc124A);
/*:RF3*/break;
case 77:
/*RF3:put_string*/r77put_string(((T77*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),ms124_7106Abc124A);
/*:RF3*/break;
case 80:
/*RF3:put_string*/r80put_string(((T80*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),ms124_7106Abc124A);
/*:RF3*/break;
case 457:
/*RF3:put_string*/r457put_string(((T457*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),ms124_7106Abc124A);
/*:RF3*/break;
case 651:
/*RF3:put_string*/r651put_string(((T651*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),ms124_7106Abc124A);
/*:RF3*/break;
case 852:
/*RF3:put_string*/r852put_string(((T852*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),ms124_7106Abc124A);
/*:RF3*/break;
default:;
/*RF3:put_string*/r855put_string(((T855*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),ms124_7106Abc124A);
/*:RF3*/}
/*inspect]*/
if(/*RF8:>*/((int64_t)(_d))>(INT64_C(1))/*:RF8*/){
/*[inspectDynamicDispatch*/
switch((((T0*)((/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)))->id)){
case 68:
/*RF3:filtered_put_character*/r68filtered_put_character(((T68*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),((T3)'s'));
/*:RF3*/break;
case 77:
/*RF3:filtered_put_character*/r68filtered_put_character((T68*)(/*RF6:std_output*/r77std_output()/*:RF6*/),((T3)'s'));
/*:RF3*/break;
case 80:
/*RF7:io_putc*/io_putc(((T3)'s'),/*NVND*/(stderr));
/*:RF7*/break;
case 457:
/*RF3:filtered_put_character*/r457filtered_put_character(((T457*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),((T3)'s'));
/*:RF3*/break;
case 651:
/*RF3:filtered_put_character*/r651filtered_put_character(((T651*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),((T3)'s'));
/*:RF3*/break;
case 852:
/*RF3:filtered_put_character*/r852filtered_put_character(((T852*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),((T3)'s'));
/*:RF3*/break;
default:;
/*RF3:filtered_put_character*/r855filtered_put_character(((T855*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),((T3)'s'));
/*:RF3*/}
/*inspect]*/
}
/*[inspectDynamicDispatch*/
switch((((T0*)((/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)))->id)){
case 68:
/*RF3:filtered_put_character*/r68filtered_put_character(((T68*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),((T3)'\040'));
/*:RF3*/break;
case 77:
/*RF3:filtered_put_character*/r68filtered_put_character((T68*)(/*RF6:std_output*/r77std_output()/*:RF6*/),((T3)'\040'));
/*:RF3*/break;
case 80:
/*RF7:io_putc*/io_putc(((T3)'\040'),/*NVND*/(stderr));
/*:RF7*/break;
case 457:
/*RF3:filtered_put_character*/r457filtered_put_character(((T457*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),((T3)'\040'));
/*:RF3*/break;
case 651:
/*RF3:filtered_put_character*/r651filtered_put_character(((T651*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),((T3)'\040'));
/*:RF3*/break;
case 852:
/*RF3:filtered_put_character*/r852filtered_put_character(((T852*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),((T3)'\040'));
/*:RF3*/break;
default:;
/*RF3:filtered_put_character*/r855filtered_put_character(((T855*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),((T3)'\040'));
/*:RF3*/}
/*inspect]*/
}
/*RF3:put_padded_num*/r124put_padded_num(C,_h,INT32_C(2));
/*:RF3*//*[inspectDynamicDispatch*/
switch((((T0*)((/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)))->id)){
case 68:
/*RF3:filtered_put_character*/r68filtered_put_character(((T68*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),((T3)'\072'));
/*:RF3*/break;
case 77:
/*RF3:filtered_put_character*/r68filtered_put_character((T68*)(/*RF6:std_output*/r77std_output()/*:RF6*/),((T3)'\072'));
/*:RF3*/break;
case 80:
/*RF7:io_putc*/io_putc(((T3)'\072'),/*NVND*/(stderr));
/*:RF7*/break;
case 457:
/*RF3:filtered_put_character*/r457filtered_put_character(((T457*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),((T3)'\072'));
/*:RF3*/break;
case 651:
/*RF3:filtered_put_character*/r651filtered_put_character(((T651*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),((T3)'\072'));
/*:RF3*/break;
case 852:
/*RF3:filtered_put_character*/r852filtered_put_character(((T852*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),((T3)'\072'));
/*:RF3*/break;
default:;
/*RF3:filtered_put_character*/r855filtered_put_character(((T855*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),((T3)'\072'));
/*:RF3*/}
/*inspect]*/
}
/*RF3:put_padded_num*/r124put_padded_num(C,_m,INT32_C(2));
/*:RF3*//*[inspectDynamicDispatch*/
switch((((T0*)((/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)))->id)){
case 68:
/*RF3:filtered_put_character*/r68filtered_put_character(((T68*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),((T3)'\072'));
/*:RF3*/break;
case 77:
/*RF3:filtered_put_character*/r68filtered_put_character((T68*)(/*RF6:std_output*/r77std_output()/*:RF6*/),((T3)'\072'));
/*:RF3*/break;
case 80:
/*RF7:io_putc*/io_putc(((T3)'\072'),/*NVND*/(stderr));
/*:RF7*/break;
case 457:
/*RF3:filtered_put_character*/r457filtered_put_character(((T457*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),((T3)'\072'));
/*:RF3*/break;
case 651:
/*RF3:filtered_put_character*/r651filtered_put_character(((T651*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),((T3)'\072'));
/*:RF3*/break;
case 852:
/*RF3:filtered_put_character*/r852filtered_put_character(((T852*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),((T3)'\072'));
/*:RF3*/break;
default:;
/*RF3:filtered_put_character*/r855filtered_put_character(((T855*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),((T3)'\072'));
/*:RF3*/}
/*inspect]*/
/*RF3:put_padded_num*/r124put_padded_num(C,_s,INT32_C(2));
/*:RF3*//*[inspectDynamicDispatch*/
switch((((T0*)((/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)))->id)){
case 68:
/*RF3:filtered_put_character*/r68filtered_put_character(((T68*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),((T3)'\056'));
/*:RF3*/break;
case 77:
/*RF3:filtered_put_character*/r68filtered_put_character((T68*)(/*RF6:std_output*/r77std_output()/*:RF6*/),((T3)'\056'));
/*:RF3*/break;
case 80:
/*RF7:io_putc*/io_putc(((T3)'\056'),/*NVND*/(stderr));
/*:RF7*/break;
case 457:
/*RF3:filtered_put_character*/r457filtered_put_character(((T457*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),((T3)'\056'));
/*:RF3*/break;
case 651:
/*RF3:filtered_put_character*/r651filtered_put_character(((T651*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),((T3)'\056'));
/*:RF3*/break;
case 852:
/*RF3:filtered_put_character*/r852filtered_put_character(((T852*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),((T3)'\056'));
/*:RF3*/break;
default:;
/*RF3:filtered_put_character*/r855filtered_put_character(((T855*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),((T3)'\056'));
/*:RF3*/}
/*inspect]*/
/*RF3:put_padded_num*/r124put_padded_num(C,_u,INT32_C(6));
/*:RF3*//*[inspectDynamicDispatch*/
switch((((T0*)((/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)))->id)){
case 68:
/*RF3:filtered_flush*/r68filtered_flush(((T68*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
case 77:
/*RF3:filtered_flush*/r68filtered_flush((T68*)(/*RF6:std_output*/r77std_output()/*:RF6*/));
/*:RF3*/break;
case 80:
/*RF3:filtered_flush*/r80filtered_flush();
/*:RF3*/break;
case 457:
/*RF3:filtered_flush*/r457filtered_flush(((T457*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
case 651:
/*RF3:filtered_flush*/r651filtered_flush(((T651*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
case 852:
/*RF3:filtered_flush*/r852filtered_flush(((T852*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
default:;
/*RF3:filtered_flush*/r855filtered_flush(((T855*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)));
/*:RF3*/}
/*inspect]*/
}
}/*--*/
T0*oBC17std_output=(void*)0;
int fBC17std_output=0;

/*ECHO*/T0*r124std_output(void){
/*[INTERNAL_C_LOCAL list*/
T0* tmp0;
/*INTERNAL_C_LOCAL list]*/
if(fBC17std_output==0){fBC17std_output=1;{
tmp0/*new*/=/*alloc*/((T0*)(se_malloc(sizeof(T68))));
*((T68*)tmp0/*new*/)=M68;
/*RF3:make*/r68make(((T68*)tmp0/*new*/));
/*:RF3*/oBC17std_output=tmp0/*new*/;
/*tmp0.unlock*/
}}
return oBC17std_output;
}/*--*/

/*ECHO*/void r124put_padded_num(T124*C,T11 a1,T2 a2){
T0*_s=(void*)0;
_s=ms124_124992Abc124A;
/*RF3:clear_count*/r7clear_count(((T7*)_s));
/*:RF3*//*RF3:append_in*/r11append_in(a1,_s);
/*:RF3*/while(1){
/*until*/if(/*RF8:>=*/((int32_t)((/*RF2:count*/(((T7*)_s))->_count/*Tiiiini*//*:RF2*/)))>=(a2)/*:RF8*/) break;
/*RF3:insert_character*/r7insert_character(((T7*)_s),((T3)'0'),INT32_C(1));
/*:RF3*/}
/*[inspectDynamicDispatch*/
switch((((T0*)((/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)))->id)){
case 68:
/*RF3:put_string*/r68put_string(((T68*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),_s);
/*:RF3*/break;
case 77:
/*RF3:put_string*/r77put_string(((T77*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),_s);
/*:RF3*/break;
case 80:
/*RF3:put_string*/r80put_string(((T80*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),_s);
/*:RF3*/break;
case 457:
/*RF3:put_string*/r457put_string(((T457*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),_s);
/*:RF3*/break;
case 651:
/*RF3:put_string*/r651put_string(((T651*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),_s);
/*:RF3*/break;
case 852:
/*RF3:put_string*/r852put_string(((T852*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),_s);
/*:RF3*/break;
default:;
/*RF3:put_string*/r855put_string(((T855*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),_s);
/*:RF3*/}
/*inspect]*/
}/*--*/

/*ECHO*/void r124print_count(T124*C,T0*a1,T2 a2){
if((/*RF2:is_verbose*/(C)->_is_verbose/*3pip*//*:RF2*/)){
if(/*RF8:>*/((int32_t)(a2))>(INT32_C(0))/*:RF8*/){
/*RF3:put_string*/r124put_string(C,ms124_349372Abc124A);
/*:RF3*//*RF3:put_string*/r124put_string(C,a1);
/*:RF3*/if((a2)!=(INT8_C(1))){
/*RF3:put_character*/r124put_character(C,((T3)'s'));
/*:RF3*/}
/*RF3:put_string*/r124put_string(C,ms124_322Abc124A);
/*:RF3*//*RF3:put_integer*/r124put_integer(C,a2);
/*:RF3*//*RF3:put_string*/r124put_string(C,ms111_240Abc124A);
/*:RF3*/}
else{
/*RF3:put_string*/r124put_string(C,ms124_2537Abc124A);
/*:RF3*//*RF3:put_string*/r124put_string(C,a1);
/*:RF3*//*RF3:put_string*/r124put_string(C,ms111_240Abc124B);
/*:RF3*/}
}
}/*--*/

/*ECHO*/T0*r124getenv(T124*C,T0*a1,T0*a2){
/*[INTERNAL_C_LOCAL list*/
T6 tmp0;
T6 tmp1;
/*INTERNAL_C_LOCAL list]*/
T0* R=(void*)0;
int _s=0;
tmp0/*or else*/=((T6)(/*RF4:same_as*/r7same_as(((T7*)ms124_1071750288Abc124A),a1)/*:RF4*/));
if(tmp0/*or else*/){
}
else{
tmp0/*or else*/=((T6)(/*RF4:same_as*/r7same_as(((T7*)ms124_1662662954Abc124A),a1)/*:RF4*/));
}
if(tmp0/*or else*/){
/*RF3:w_put_string*/r124w_put_string(C,ms124_203714719Abc124A);
/*:RF3*//*RF3:w_put_string*/r124w_put_string(C,a1);
/*:RF3*//*RF3:w_put_string*/r124w_put_string(C,ms124_1974940930Abc124A);
/*:RF3*/if((a2)!=((void*)((void*)0))){
/*RF3:w_put_string*/r124w_put_string(C,ms124_113009969Abc124A);
/*:RF3*//*RF3:w_put_string*/r124w_put_string(C,a2);
/*:RF3*//*RF3:w_put_character*/r124w_put_character(C,((T3)'\042'));
/*:RF3*/}
else{
/*RF3:w_put_character*/r124w_put_character(C,((T3)'\056'));
/*:RF3*/}
/*RF3:w_put_character*/r124w_put_character(C,((T3)'\n'));
/*:RF3*/}
R=/*RF4:get_environment_variable*/r533get_environment_variable(a1)/*:RF4*/;
/*auto-unlock tmp0*/tmp0/*and then*/=((T6)((R)==((void*)((void*)0))));
if(tmp0/*and then*/){
tmp0/*and then*/=((T6)(/*RF4:same_as*/r7same_as(((T7*)ms124_1635864124Abc124A),a1)/*:RF4*/));
}
if(tmp0/*and then*/){
R=/*RF4:getenv*/r124getenv(C,ms34_1072344038Abc34B,a2)/*:RF4*/;
tmp1/*and then*/=((T6)((R)!=((void*)((void*)0))));
if(tmp1/*and then*/){
tmp1/*and then*/=((T6)(/*RF8:>*/((int32_t)((/*RF2:count*/(((T7*)R))->_count/*Tiiiini*//*:RF2*/)))>(INT32_C(9))/*:RF8*/));
}
if(tmp1/*and then*/){
/*RF3:parent_directory*/r111parent_directory((T111*)(/*RF6:system_tools*/r124system_tools()/*:RF6*/),R);
/*:RF3*/if(/*RF8:>*/((int32_t)((/*RF2:count*/(((T7*)R))->_count/*Tiiiini*//*:RF2*/)))>(INT32_C(3))/*:RF8*/){
/*RF3:parent_directory*/r111parent_directory((T111*)(/*RF6:system_tools*/r124system_tools()/*:RF6*/),R);
/*:RF3*/}
}
}
if((R)==((void*)((void*)0))){
if(/*RF4:same_as*/r7same_as(((T7*)ms124_1071750288Abc124A),a1)/*:RF4*/){
R=/*RF4:get_environment_variable*/r533get_environment_variable(ms124_1071750288Abc124A)/*:RF4*/;
if((R)!=((void*)((void*)0))){
/*RF3:w_put_string*/r124w_put_string(C,se_string(80,s124_1972884945A));
/*:RF3*/}
}
else{
if(/*RF4:same_as*/r7same_as(((T7*)ms124_1662662954Abc124A),a1)/*:RF4*/){
R=/*RF4:getenv*/r124getenv(C,ms124_1071750288Abc124A,a2)/*:RF4*/;
if((R)!=((void*)((void*)0))){
/*RF3:w_put_string*/r124w_put_string(C,se_string(133,s124_461074983A));
/*:RF3*/if(/*RF8:>*/((int32_t)((/*RF2:count*/(((T7*)R))->_count/*Tiiiini*//*:RF2*/)))>(INT32_C(9))/*:RF8*/){
/*RF3:parent_directory*/r111parent_directory((T111*)(/*RF6:system_tools*/r124system_tools()/*:RF6*/),R);
/*:RF3*/if(/*RF8:>*/((int32_t)((/*RF2:count*/(((T7*)R))->_count/*Tiiiini*//*:RF2*/)))>(INT32_C(3))/*:RF8*/){
/*RF3:parent_directory*/r111parent_directory((T111*)(/*RF6:system_tools*/r124system_tools()/*:RF6*/),R);
/*:RF3*/}
}
}
}
}
}
if((R)==((void*)((void*)0))){
R=/*RF4:environment*/r111environment((T111*)(/*RF6:system_tools*/r124system_tools()/*:RF6*/),a1)/*:RF4*/;
}
if((R)==((void*)((void*)0))){
/*RF3:w_put_string*/r124w_put_string(C,ms124_354654986Abc124A);
/*:RF3*//*RF3:w_put_string*/r124w_put_string(C,a1);
/*:RF3*//*RF3:w_put_character*/r124w_put_character(C,((T3)'\175'));
/*:RF3*/if((a2)!=((void*)((void*)0))){
/*RF3:w_put_string*/r124w_put_string(C,ms124_1430004157Abc124A);
/*:RF3*//*RF3:w_put_string*/r124w_put_string(C,a2);
/*:RF3*//*RF3:w_put_character*/r124w_put_character(C,((T3)'\042'));
/*:RF3*/}
/*RF3:w_put_string*/r124w_put_string(C,ms124_1293738877Abc124A);
/*:RF3*/}
return R;
}/*--*/

/*ECHO*/void r124tfw_connect(T124*C,T0*a1,T0*a2){
/*RF3:connect_to*/r457connect_to(((T457*)a1),a2);
/*:RF3*/if(((/*RF2:path*/(((T457*)a1))->_path/*TpiinI2p*//*:RF2*/))!=((void*)((void*)0))){
/*RF3:put_string*/r124put_string(C,ms124_44975894Abc124A);
/*:RF3*//*RF3:put_string*/r124put_string(C,a2);
/*:RF3*//*RF3:put_string*/r124put_string(C,ms124_3556890Abc124A);
/*:RF3*/}
else{
/*RF3:w_put_string*/r124w_put_string(C,ms124_1711985232Abc124A);
/*:RF3*//*RF3:w_put_string*/r124w_put_string(C,a2);
/*:RF3*//*RF3:w_put_string*/r124w_put_string(C,ms30_1090Abc124A);
/*:RF3*//*RF7:die_with_code*/se_die(INT32_C(1));
/*:RF7*/}
}/*--*/

/*ECHO*/void r124w_put_character(T124*C,T3 a1){
/*[inspectDynamicDispatch*/
switch((((T0*)((/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)))->id)){
case 68:
/*RF3:filtered_put_character*/r68filtered_put_character(((T68*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)),a1);
/*:RF3*/break;
case 77:
/*RF3:filtered_put_character*/r68filtered_put_character((T68*)(/*RF6:std_output*/r77std_output()/*:RF6*/),a1);
/*:RF3*/break;
case 80:
/*RF7:io_putc*/io_putc(a1,/*NVND*/(stderr));
/*:RF7*/break;
case 457:
/*RF3:filtered_put_character*/r457filtered_put_character(((T457*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)),a1);
/*:RF3*/break;
case 651:
/*RF3:filtered_put_character*/r651filtered_put_character(((T651*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)),a1);
/*:RF3*/break;
case 852:
/*RF3:filtered_put_character*/r852filtered_put_character(((T852*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)),a1);
/*:RF3*/break;
default:;
/*RF3:filtered_put_character*/r855filtered_put_character(((T855*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)),a1);
/*:RF3*/}
/*inspect]*/
/*[inspectDynamicDispatch*/
switch((((T0*)((/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)))->id)){
case 68:
/*RF3:filtered_flush*/r68filtered_flush(((T68*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
case 77:
/*RF3:filtered_flush*/r68filtered_flush((T68*)(/*RF6:std_output*/r77std_output()/*:RF6*/));
/*:RF3*/break;
case 80:
/*RF3:filtered_flush*/r80filtered_flush();
/*:RF3*/break;
case 457:
/*RF3:filtered_flush*/r457filtered_flush(((T457*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
case 651:
/*RF3:filtered_flush*/r651filtered_flush(((T651*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
case 852:
/*RF3:filtered_flush*/r852filtered_flush(((T852*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
default:;
/*RF3:filtered_flush*/r855filtered_flush(((T855*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)));
/*:RF3*/}
/*inspect]*/
}/*--*/

/*ECHO*/void r124put_new_line(T124*C){
if((/*RF2:is_verbose*/(C)->_is_verbose/*3pip*//*:RF2*/)){
/*[inspectDynamicDispatch*/
switch((((T0*)((/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)))->id)){
case 68:
/*RF3:filtered_put_character*/r68filtered_put_character(((T68*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),((T3)'\n'));
/*:RF3*/break;
case 77:
/*RF3:filtered_put_character*/r68filtered_put_character((T68*)(/*RF6:std_output*/r77std_output()/*:RF6*/),((T3)'\n'));
/*:RF3*/break;
case 80:
/*RF7:io_putc*/io_putc(((T3)'\n'),/*NVND*/(stderr));
/*:RF7*/break;
case 457:
/*RF3:filtered_put_character*/r457filtered_put_character(((T457*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),((T3)'\n'));
/*:RF3*/break;
case 651:
/*RF3:filtered_put_character*/r651filtered_put_character(((T651*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),((T3)'\n'));
/*:RF3*/break;
case 852:
/*RF3:filtered_put_character*/r852filtered_put_character(((T852*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),((T3)'\n'));
/*:RF3*/break;
default:;
/*RF3:filtered_put_character*/r855filtered_put_character(((T855*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),((T3)'\n'));
/*:RF3*/}
/*inspect]*/
/*[inspectDynamicDispatch*/
switch((((T0*)((/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)))->id)){
case 68:
/*RF3:filtered_flush*/r68filtered_flush(((T68*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
case 77:
/*RF3:filtered_flush*/r68filtered_flush((T68*)(/*RF6:std_output*/r77std_output()/*:RF6*/));
/*:RF3*/break;
case 80:
/*RF3:filtered_flush*/r80filtered_flush();
/*:RF3*/break;
case 457:
/*RF3:filtered_flush*/r457filtered_flush(((T457*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
case 651:
/*RF3:filtered_flush*/r651filtered_flush(((T651*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
case 852:
/*RF3:filtered_flush*/r852filtered_flush(((T852*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
default:;
/*RF3:filtered_flush*/r855filtered_flush(((T855*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)));
/*:RF3*/}
/*inspect]*/
}
}/*--*/

/*ECHO*/void r124put_string(T124*C,T0*a1){
if((/*RF2:is_verbose*/(C)->_is_verbose/*3pip*//*:RF2*/)){
/*[inspectDynamicDispatch*/
switch((((T0*)((/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)))->id)){
case 68:
/*RF3:put_string*/r68put_string(((T68*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),a1);
/*:RF3*/break;
case 77:
/*RF3:put_string*/r77put_string(((T77*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),a1);
/*:RF3*/break;
case 80:
/*RF3:put_string*/r80put_string(((T80*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),a1);
/*:RF3*/break;
case 457:
/*RF3:put_string*/r457put_string(((T457*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),a1);
/*:RF3*/break;
case 651:
/*RF3:put_string*/r651put_string(((T651*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),a1);
/*:RF3*/break;
case 852:
/*RF3:put_string*/r852put_string(((T852*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),a1);
/*:RF3*/break;
default:;
/*RF3:put_string*/r855put_string(((T855*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),a1);
/*:RF3*/}
/*inspect]*/
/*[inspectDynamicDispatch*/
switch((((T0*)((/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)))->id)){
case 68:
/*RF3:filtered_flush*/r68filtered_flush(((T68*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
case 77:
/*RF3:filtered_flush*/r68filtered_flush((T68*)(/*RF6:std_output*/r77std_output()/*:RF6*/));
/*:RF3*/break;
case 80:
/*RF3:filtered_flush*/r80filtered_flush();
/*:RF3*/break;
case 457:
/*RF3:filtered_flush*/r457filtered_flush(((T457*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
case 651:
/*RF3:filtered_flush*/r651filtered_flush(((T651*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
case 852:
/*RF3:filtered_flush*/r852filtered_flush(((T852*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
default:;
/*RF3:filtered_flush*/r855filtered_flush(((T855*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)));
/*:RF3*/}
/*inspect]*/
}
}/*--*/

/*ECHO*/T0*r124system_tools(void){
/*[INTERNAL_C_LOCAL list*/
T0* tmp0;
/*INTERNAL_C_LOCAL list]*/
if(fBC32system_tools==0){fBC32system_tools=1;{
tmp0/*new*/=/*alloc*/((T0*)(se_malloc(sizeof(T111))));
*((T111*)tmp0/*new*/)=M111;
/*RF3:make*/r111make(((T111*)tmp0/*new*/));
/*:RF3*/oBC32system_tools=tmp0/*new*/;
/*tmp0.unlock*/
}}
return oBC32system_tools;
}/*--*/

/*ECHO*/void r124put_real_format(T124*C,T5 a1,T2 a2){
if((/*RF2:is_verbose*/(C)->_is_verbose/*3pip*//*:RF2*/)){
/*[inspectDynamicDispatch*/
switch((((T0*)((/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)))->id)){
case 68:
/*RF3:put_real_format*/r68put_real_format(((T68*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),a1,a2);
/*:RF3*/break;
case 77:
/*RF3:put_real_format*/r77put_real_format(((T77*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),a1,a2);
/*:RF3*/break;
case 80:
/*RF3:put_real_format*/r80put_real_format(((T80*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),a1,a2);
/*:RF3*/break;
case 457:
/*RF3:put_real_format*/r457put_real_format(((T457*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),a1,a2);
/*:RF3*/break;
case 651:
/*RF3:put_real_format*/r651put_real_format(((T651*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),a1,a2);
/*:RF3*/break;
case 852:
/*RF3:put_real_format*/r852put_real_format(((T852*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),a1,a2);
/*:RF3*/break;
default:;
/*RF3:put_real_format*/r855put_real_format(((T855*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),a1,a2);
/*:RF3*/}
/*inspect]*/
/*[inspectDynamicDispatch*/
switch((((T0*)((/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)))->id)){
case 68:
/*RF3:filtered_flush*/r68filtered_flush(((T68*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
case 77:
/*RF3:filtered_flush*/r68filtered_flush((T68*)(/*RF6:std_output*/r77std_output()/*:RF6*/));
/*:RF3*/break;
case 80:
/*RF3:filtered_flush*/r80filtered_flush();
/*:RF3*/break;
case 457:
/*RF3:filtered_flush*/r457filtered_flush(((T457*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
case 651:
/*RF3:filtered_flush*/r651filtered_flush(((T651*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
case 852:
/*RF3:filtered_flush*/r852filtered_flush(((T852*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
default:;
/*RF3:filtered_flush*/r855filtered_flush(((T855*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)));
/*:RF3*/}
/*inspect]*/
}
}/*--*/

/*ECHO*/void r124w_put_line(T124*C,T0*a1){
/*[inspectDynamicDispatch*/
switch((((T0*)((/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)))->id)){
case 68:
/*RF3:put_line*/r68put_line(((T68*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)),a1);
/*:RF3*/break;
case 77:
/*RF3:put_line*/r77put_line(((T77*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)),a1);
/*:RF3*/break;
case 80:
/*RF3:put_line*/r80put_line(((T80*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)),a1);
/*:RF3*/break;
case 457:
/*RF3:put_line*/r457put_line(((T457*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)),a1);
/*:RF3*/break;
case 651:
/*RF3:put_line*/r651put_line(((T651*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)),a1);
/*:RF3*/break;
case 852:
/*RF3:put_line*/r852put_line(((T852*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)),a1);
/*:RF3*/break;
default:;
/*RF3:put_line*/r855put_line(((T855*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)),a1);
/*:RF3*/}
/*inspect]*/
/*[inspectDynamicDispatch*/
switch((((T0*)((/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)))->id)){
case 68:
/*RF3:filtered_flush*/r68filtered_flush(((T68*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
case 77:
/*RF3:filtered_flush*/r68filtered_flush((T68*)(/*RF6:std_output*/r77std_output()/*:RF6*/));
/*:RF3*/break;
case 80:
/*RF3:filtered_flush*/r80filtered_flush();
/*:RF3*/break;
case 457:
/*RF3:filtered_flush*/r457filtered_flush(((T457*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
case 651:
/*RF3:filtered_flush*/r651filtered_flush(((T651*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
case 852:
/*RF3:filtered_flush*/r852filtered_flush(((T852*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
default:;
/*RF3:filtered_flush*/r855filtered_flush(((T855*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)));
/*:RF3*/}
/*inspect]*/
}/*--*/

/*ECHO*/void r124put_integer(T124*C,T2 a1){
if((/*RF2:is_verbose*/(C)->_is_verbose/*3pip*//*:RF2*/)){
/*[inspectDynamicDispatch*/
switch((((T0*)((/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)))->id)){
case 68:
/*RF3:put_integer*/r68put_integer(((T68*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),/*IC*/(T11)(a1));
/*:RF3*/break;
case 77:
/*RF3:put_integer*/r77put_integer(((T77*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),/*IC*/(T11)(a1));
/*:RF3*/break;
case 80:
/*RF3:put_integer*/r80put_integer(((T80*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),/*IC*/(T11)(a1));
/*:RF3*/break;
case 457:
/*RF3:put_integer*/r457put_integer(((T457*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),/*IC*/(T11)(a1));
/*:RF3*/break;
case 651:
/*RF3:put_integer*/r651put_integer(((T651*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),/*IC*/(T11)(a1));
/*:RF3*/break;
case 852:
/*RF3:put_integer*/r852put_integer(((T852*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),/*IC*/(T11)(a1));
/*:RF3*/break;
default:;
/*RF3:put_integer*/r855put_integer(((T855*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),/*IC*/(T11)(a1));
/*:RF3*/}
/*inspect]*/
/*[inspectDynamicDispatch*/
switch((((T0*)((/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)))->id)){
case 68:
/*RF3:filtered_flush*/r68filtered_flush(((T68*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
case 77:
/*RF3:filtered_flush*/r68filtered_flush((T68*)(/*RF6:std_output*/r77std_output()/*:RF6*/));
/*:RF3*/break;
case 80:
/*RF3:filtered_flush*/r80filtered_flush();
/*:RF3*/break;
case 457:
/*RF3:filtered_flush*/r457filtered_flush(((T457*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
case 651:
/*RF3:filtered_flush*/r651filtered_flush(((T651*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
case 852:
/*RF3:filtered_flush*/r852filtered_flush(((T852*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
default:;
/*RF3:filtered_flush*/r855filtered_flush(((T855*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)));
/*:RF3*/}
/*inspect]*/
}
}/*--*/
T0*oBC17std_error=(void*)0;

/*ECHO*/void r124file_removing(T124*C,T0*a1){
if(/*RF4:is_readable*/((/*UT*/(void)(create289())),r289is_readable(a1))/*:RF4*/){
/*RF3:put_string*/r124put_string(C,ms124_210310269Abc124A);
/*:RF3*//*RF3:put_string*/r124put_string(C,a1);
/*:RF3*//*RF3:put_string*/r124put_string(C,ms30_1090Abc124C);
/*:RF3*//*RF3:delete*/((/*UT*/(void)(create289())),r289delete(a1));
/*:RF3*/}
}/*--*/

/*ECHO*/void r124w_put_integer(T124*C,T2 a1){
/*[inspectDynamicDispatch*/
switch((((T0*)((/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)))->id)){
case 68:
/*RF3:put_integer*/r68put_integer(((T68*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)),/*IC*/(T11)(a1));
/*:RF3*/break;
case 77:
/*RF3:put_integer*/r77put_integer(((T77*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)),/*IC*/(T11)(a1));
/*:RF3*/break;
case 80:
/*RF3:put_integer*/r80put_integer(((T80*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)),/*IC*/(T11)(a1));
/*:RF3*/break;
case 457:
/*RF3:put_integer*/r457put_integer(((T457*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)),/*IC*/(T11)(a1));
/*:RF3*/break;
case 651:
/*RF3:put_integer*/r651put_integer(((T651*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)),/*IC*/(T11)(a1));
/*:RF3*/break;
case 852:
/*RF3:put_integer*/r852put_integer(((T852*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)),/*IC*/(T11)(a1));
/*:RF3*/break;
default:;
/*RF3:put_integer*/r855put_integer(((T855*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)),/*IC*/(T11)(a1));
/*:RF3*/}
/*inspect]*/
/*[inspectDynamicDispatch*/
switch((((T0*)((/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)))->id)){
case 68:
/*RF3:filtered_flush*/r68filtered_flush(((T68*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
case 77:
/*RF3:filtered_flush*/r68filtered_flush((T68*)(/*RF6:std_output*/r77std_output()/*:RF6*/));
/*:RF3*/break;
case 80:
/*RF3:filtered_flush*/r80filtered_flush();
/*:RF3*/break;
case 457:
/*RF3:filtered_flush*/r457filtered_flush(((T457*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
case 651:
/*RF3:filtered_flush*/r651filtered_flush(((T651*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
case 852:
/*RF3:filtered_flush*/r852filtered_flush(((T852*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
default:;
/*RF3:filtered_flush*/r855filtered_flush(((T855*)(/*RF2:error_stream*/(C)->_error_stream/*3pip*//*:RF2*/)));
/*:RF3*/}
/*inspect]*/
}/*--*/

/*ECHO*/void r124redirect_output_on(T124*C,T0*a1){
/*[INTERNAL_C_LOCAL list*/
T0* tmp0;
/*INTERNAL_C_LOCAL list]*/
T0*_text_file_write=(void*)0;
tmp0/*new*/=/*alloc*/((T0*)(se_malloc(sizeof(T457))));
*((T457*)tmp0/*new*/)=M457;
/*RF3:connect_to*/r457connect_to(((T457*)tmp0/*new*/),a1);
/*:RF3*/_text_file_write=tmp0/*new*/;
/*tmp0.unlock*/
if(((/*RF2:path*/(((T457*)_text_file_write))->_path/*TpiinI2p*//*:RF2*/))!=((void*)((void*)0))){
/*SFN*/(C->_output_state/*3pip*/)=INT32_C(2);
/*reusing tmp0*/tmp0/*new*/=/*alloc*/((T0*)(se_malloc(sizeof(T651))));
*((T651*)tmp0/*new*/)=M651;
/*RF3:connect_to*/r651connect_to(((T651*)tmp0/*new*/),_text_file_write);
/*:RF3*//*SFN*/(C->_output_stream/*3pip*/)=tmp0/*new*/;
/*tmp0.unlock*/
/*SFN*/(C->_error_stream/*3pip*/)=(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/);
/*SFN*/(C->_output_path/*3pip*/)=ms124_1723571071Abc124A;
/*RF3:make_from_string*/r7make_from_string((T7*)((/*RF2:output_path*/(C)->_output_path/*3pip*//*:RF2*/)),a1);
/*:RF3*/}
else{
/*RF3:w_put_string*/r124w_put_string(C,ms124_195766720Abc124A);
/*:RF3*//*RF3:w_put_string*/r124w_put_string(C,a1);
/*:RF3*//*RF3:w_put_string*/r124w_put_string(C,ms124_809686569Abc124A);
/*:RF3*//*RF7:die_with_code*/se_die(INT32_C(1));
/*:RF7*/}
}/*--*/

/*ECHO*/void r124put_character(T124*C,T3 a1){
if((/*RF2:is_verbose*/(C)->_is_verbose/*3pip*//*:RF2*/)){
/*[inspectDynamicDispatch*/
switch((((T0*)((/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)))->id)){
case 68:
/*RF3:filtered_put_character*/r68filtered_put_character(((T68*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),a1);
/*:RF3*/break;
case 77:
/*RF3:filtered_put_character*/r68filtered_put_character((T68*)(/*RF6:std_output*/r77std_output()/*:RF6*/),a1);
/*:RF3*/break;
case 80:
/*RF7:io_putc*/io_putc(a1,/*NVND*/(stderr));
/*:RF7*/break;
case 457:
/*RF3:filtered_put_character*/r457filtered_put_character(((T457*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),a1);
/*:RF3*/break;
case 651:
/*RF3:filtered_put_character*/r651filtered_put_character(((T651*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),a1);
/*:RF3*/break;
case 852:
/*RF3:filtered_put_character*/r852filtered_put_character(((T852*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),a1);
/*:RF3*/break;
default:;
/*RF3:filtered_put_character*/r855filtered_put_character(((T855*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)),a1);
/*:RF3*/}
/*inspect]*/
/*[inspectDynamicDispatch*/
switch((((T0*)((/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)))->id)){
case 68:
/*RF3:filtered_flush*/r68filtered_flush(((T68*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
case 77:
/*RF3:filtered_flush*/r68filtered_flush((T68*)(/*RF6:std_output*/r77std_output()/*:RF6*/));
/*:RF3*/break;
case 80:
/*RF3:filtered_flush*/r80filtered_flush();
/*:RF3*/break;
case 457:
/*RF3:filtered_flush*/r457filtered_flush(((T457*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
case 651:
/*RF3:filtered_flush*/r651filtered_flush(((T651*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
case 852:
/*RF3:filtered_flush*/r852filtered_flush(((T852*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)));
/*:RF3*/break;
default:;
/*RF3:filtered_flush*/r855filtered_flush(((T855*)(/*RF2:output_stream*/(C)->_output_stream/*3pip*//*:RF2*/)));
/*:RF3*/}
/*inspect]*/
}
}/*--*/

/*C_PLUGIN_FACTORY*/T997*create997(void){
/*[INTERNAL_C_LOCAL list*/
T0* tmp0;
/*INTERNAL_C_LOCAL list]*/
tmp0/*new*/=/*alloc*/((T0*)(se_malloc(1)));
return ((T997*)tmp0/*new*/);
/*tmp0.unlock*/
}/*--*/

/*C_PLUGIN_FACTORY*/T0*r997new(T345 a1,T0*a2,T0*a3){
/*[INTERNAL_C_LOCAL list*/
T0* tmp0;
/*INTERNAL_C_LOCAL list]*/
T0* R=(void*)0;
tmp0/*new*/=/*alloc*/((T0*)(se_malloc(sizeof(T998))));
*((T998*)tmp0/*new*/)=M998;
r345default_create(&(((T998*)tmp0/*new*/)->_start_position));
/*RF3:make*/r998make(((T998*)tmp0/*new*/),a1,a2,a3);
/*:RF3*/R=tmp0/*new*/;
/*tmp0.unlock*/
return R;
}/*--*/

#ifdef __cplusplus
}
#endif
