#ifdef __cplusplus
extern "C" {
#endif
/*
ANSI C code generated by 
Liberty Eiffel The GNU Eiffel Compiler, Eiffel tools and libraries
    release 2013.10 (Charles Adler, Jr.)

Copyright (C), 2011-2013 - C.ADRIAN, P.REDAELLI, R.MACK
    http://www.liberty-eiffel.org

Original SmartEiffel code:
Copyright (C), 1994-2002 - INRIA - LORIA - ESIAL UHP Nancy 1 - FRANCE
Copyright (C), 2003-2005 - INRIA - LORIA - IUT Charlemagne Nancy 2 - FRANCE
D.COLNET, P.RIBET, C.ADRIAN, V.CROIZIER, F.MERIZEN
    http://smarteiffel.loria.fr
C Compiler options used: -pipe -O2 -fno-gcse
*/

#ifdef __cplusplus
}
#endif
#include "compile_to_c.h"
#ifdef __cplusplus
extern "C" {
#endif

/*NATIVE_ARRAY[TMP_FEATURE]*/T1240 r1240realloc(T1240 C,T2 a1,T2 a2){
T1240 R=(void*)0;
R=/*RF8:calloc*/se_calloc(a2,sizeof(T0*))/*:RF8*/;
/*RF3:copy_from*/r1240copy_from(R,C,/*RF8:-*/((int32_t)(a1))-(INT32_C(1))/*:RF8*/);
/*:RF3*/return R;
}/*--*/

/*NATIVE_ARRAY[TMP_FEATURE]*/void r1240copy_from(T1240 C,T1240 a1,T2 a2){
/*RF3:copy_slice_from*/r1240copy_slice_from(C,a1,INT32_C(0),a2);
/*:RF3*/}/*--*/

/*NATIVE_ARRAY[TMP_FEATURE]*/void r1240clear(T1240 C,T2 a1,T2 a2){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:>*/((int32_t)(_i))>(a2)/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:+*/((int32_t)(_i))+(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[TMP_FEATURE]*/void r1240clear_all(T1240 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[TMP_FEATURE]*/void r1240copy_slice_from(T1240 C,T1240 a1,T2 a2,T2 a3){
/*RF7:slice_copy*/{/*slice_copy*/
int a3tmp=a2;
memcpy((C)+(INT32_C(0)),(a1)+a3tmp,((a3)-a3tmp+1)*sizeof(T0*));}
/*:RF7*/}/*--*/

/*NATIVE_ARRAY[ARGUMENT_NAME1]*/T1241 r1241realloc(T1241 C,T2 a1,T2 a2){
T1241 R=(void*)0;
R=/*RF8:calloc*/se_calloc(a2,sizeof(T0*))/*:RF8*/;
/*RF3:copy_from*/r1241copy_from(R,C,/*RF8:-*/((int32_t)(a1))-(INT32_C(1))/*:RF8*/);
/*:RF3*/return R;
}/*--*/

/*NATIVE_ARRAY[ARGUMENT_NAME1]*/void r1241copy_from(T1241 C,T1241 a1,T2 a2){
/*RF3:copy_slice_from*/r1241copy_slice_from(C,a1,INT32_C(0),a2);
/*:RF3*/}/*--*/

/*NATIVE_ARRAY[ARGUMENT_NAME1]*/void r1241set_slice_with(T1241 C,T0* a1,T2 a2,T2 a3){
T2 _i=0;
_i=a2;
while(1){
/*until*/if(/*RF8:>*/((int32_t)(_i))>(a3)/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(a1);
/*:RF7*/_i=/*RF8:+*/((int32_t)(_i))+(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[ARGUMENT_NAME1]*/void r1241clear_all(T1241 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[ARGUMENT_NAME1]*/void r1241set_all_with(T1241 C,T0* a1,T2 a2){
/*RF3:set_slice_with*/r1241set_slice_with(C,a1,INT32_C(0),a2);
/*:RF3*/}/*--*/

/*NATIVE_ARRAY[ARGUMENT_NAME1]*/void r1241copy_slice_from(T1241 C,T1241 a1,T2 a2,T2 a3){
/*RF7:slice_copy*/{/*slice_copy*/
int a3tmp=a2;
memcpy((C)+(INT32_C(0)),(a1)+a3tmp,((a3)-a3tmp+1)*sizeof(T0*));}
/*:RF7*/}/*--*/

/*NATIVE_ARRAY[LOCAL_ARGUMENT1]*/void r1242set_slice_with(T1242 C,T0* a1,T2 a2,T2 a3){
T2 _i=0;
_i=a2;
while(1){
/*until*/if(/*RF8:>*/((int32_t)(_i))>(a3)/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(a1);
/*:RF7*/_i=/*RF8:+*/((int32_t)(_i))+(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[LOCAL_ARGUMENT1]*/void r1242clear_all(T1242 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[LOCAL_ARGUMENT1]*/void r1242set_all_with(T1242 C,T0* a1,T2 a2){
/*RF3:set_slice_with*/r1242set_slice_with(C,a1,INT32_C(0),a2);
/*:RF3*/}/*--*/

/*NATIVE_ARRAY[DECLARATION]*/T1243 r1243realloc(T1243 C,T2 a1,T2 a2){
T1243 R=(void*)0;
R=/*RF8:calloc*/se_calloc(a2,sizeof(T0*))/*:RF8*/;
/*RF3:copy_from*/r1243copy_from(R,C,/*RF8:-*/((int32_t)(a1))-(INT32_C(1))/*:RF8*/);
/*:RF3*/return R;
}/*--*/

/*NATIVE_ARRAY[DECLARATION]*/void r1243copy_from(T1243 C,T1243 a1,T2 a2){
/*RF3:copy_slice_from*/r1243copy_slice_from(C,a1,INT32_C(0),a2);
/*:RF3*/}/*--*/

/*NATIVE_ARRAY[DECLARATION]*/void r1243set_slice_with(T1243 C,T0* a1,T2 a2,T2 a3){
T2 _i=0;
_i=a2;
while(1){
/*until*/if(/*RF8:>*/((int32_t)(_i))>(a3)/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(a1);
/*:RF7*/_i=/*RF8:+*/((int32_t)(_i))+(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[DECLARATION]*/void r1243clear_all(T1243 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[DECLARATION]*/void r1243set_all_with(T1243 C,T0* a1,T2 a2){
/*RF3:set_slice_with*/r1243set_slice_with(C,a1,INT32_C(0),a2);
/*:RF3*/}/*--*/

/*NATIVE_ARRAY[DECLARATION]*/void r1243copy_slice_from(T1243 C,T1243 a1,T2 a2,T2 a3){
/*RF7:slice_copy*/{/*slice_copy*/
int a3tmp=a2;
memcpy((C)+(INT32_C(0)),(a1)+a3tmp,((a3)-a3tmp+1)*sizeof(T0*));}
/*:RF7*/}/*--*/

/*NATIVE_ARRAY[ASSERTION]*/T1245 r1245realloc(T1245 C,T2 a1,T2 a2){
T1245 R=(void*)0;
R=/*RF8:calloc*/se_calloc(a2,sizeof(T0*))/*:RF8*/;
/*RF3:copy_from*/r1245copy_from(R,C,/*RF8:-*/((int32_t)(a1))-(INT32_C(1))/*:RF8*/);
/*:RF3*/return R;
}/*--*/

/*NATIVE_ARRAY[ASSERTION]*/void r1245copy_from(T1245 C,T1245 a1,T2 a2){
/*RF3:copy_slice_from*/r1245copy_slice_from(C,a1,INT32_C(0),a2);
/*:RF3*/}/*--*/

/*NATIVE_ARRAY[ASSERTION]*/void r1245clear(T1245 C,T2 a1,T2 a2){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:>*/((int32_t)(_i))>(a2)/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:+*/((int32_t)(_i))+(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[ASSERTION]*/void r1245clear_all(T1245 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[ASSERTION]*/void r1245copy_slice_from(T1245 C,T1245 a1,T2 a2,T2 a3){
/*RF7:slice_copy*/{/*slice_copy*/
int a3tmp=a2;
memcpy((C)+(INT32_C(0)),(a1)+a3tmp,((a3)-a3tmp+1)*sizeof(T0*));}
/*:RF7*/}/*--*/

/*NATIVE_ARRAY[LOCAL_NAME1]*/T1246 r1246realloc(T1246 C,T2 a1,T2 a2){
T1246 R=(void*)0;
R=/*RF8:calloc*/se_calloc(a2,sizeof(T0*))/*:RF8*/;
/*RF3:copy_from*/r1246copy_from(R,C,/*RF8:-*/((int32_t)(a1))-(INT32_C(1))/*:RF8*/);
/*:RF3*/return R;
}/*--*/

/*NATIVE_ARRAY[LOCAL_NAME1]*/void r1246copy_from(T1246 C,T1246 a1,T2 a2){
/*RF3:copy_slice_from*/r1246copy_slice_from(C,a1,INT32_C(0),a2);
/*:RF3*/}/*--*/

/*NATIVE_ARRAY[LOCAL_NAME1]*/void r1246set_slice_with(T1246 C,T0* a1,T2 a2,T2 a3){
T2 _i=0;
_i=a2;
while(1){
/*until*/if(/*RF8:>*/((int32_t)(_i))>(a3)/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(a1);
/*:RF7*/_i=/*RF8:+*/((int32_t)(_i))+(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[LOCAL_NAME1]*/void r1246clear_all(T1246 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[LOCAL_NAME1]*/void r1246set_all_with(T1246 C,T0* a1,T2 a2){
/*RF3:set_slice_with*/r1246set_slice_with(C,a1,INT32_C(0),a2);
/*:RF3*/}/*--*/

/*NATIVE_ARRAY[LOCAL_NAME1]*/void r1246copy_slice_from(T1246 C,T1246 a1,T2 a2,T2 a3){
/*RF7:slice_copy*/{/*slice_copy*/
int a3tmp=a2;
memcpy((C)+(INT32_C(0)),(a1)+a3tmp,((a3)-a3tmp+1)*sizeof(T0*));}
/*:RF7*/}/*--*/

/*NATIVE_ARRAY[MANIFEST_STRING]*/T1247 r1247realloc(T1247 C,T2 a1,T2 a2){
T1247 R=(void*)0;
R=/*RF8:calloc*/se_calloc(a2,sizeof(T0*))/*:RF8*/;
/*RF3:copy_from*/r1247copy_from(R,C,/*RF8:-*/((int32_t)(a1))-(INT32_C(1))/*:RF8*/);
/*:RF3*/return R;
}/*--*/

/*NATIVE_ARRAY[MANIFEST_STRING]*/void r1247copy_from(T1247 C,T1247 a1,T2 a2){
/*RF3:copy_slice_from*/r1247copy_slice_from(C,a1,INT32_C(0),a2);
/*:RF3*/}/*--*/

/*NATIVE_ARRAY[MANIFEST_STRING]*/void r1247clear(T1247 C,T2 a1,T2 a2){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:>*/((int32_t)(_i))>(a2)/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:+*/((int32_t)(_i))+(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[MANIFEST_STRING]*/void r1247clear_all(T1247 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[MANIFEST_STRING]*/void r1247copy_slice_from(T1247 C,T1247 a1,T2 a2,T2 a3){
/*RF7:slice_copy*/{/*slice_copy*/
int a3tmp=a2;
memcpy((C)+(INT32_C(0)),(a1)+a3tmp,((a3)-a3tmp+1)*sizeof(T0*));}
/*:RF7*/}/*--*/

/*NATIVE_ARRAY[WHEN_CLAUSE]*/T1249 r1249realloc(T1249 C,T2 a1,T2 a2){
T1249 R=(void*)0;
R=/*RF8:calloc*/se_calloc(a2,sizeof(T0*))/*:RF8*/;
/*RF3:copy_from*/r1249copy_from(R,C,/*RF8:-*/((int32_t)(a1))-(INT32_C(1))/*:RF8*/);
/*:RF3*/return R;
}/*--*/

/*NATIVE_ARRAY[WHEN_CLAUSE]*/void r1249copy_from(T1249 C,T1249 a1,T2 a2){
/*RF3:copy_slice_from*/r1249copy_slice_from(C,a1,INT32_C(0),a2);
/*:RF3*/}/*--*/

/*NATIVE_ARRAY[WHEN_CLAUSE]*/void r1249clear(T1249 C,T2 a1,T2 a2){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:>*/((int32_t)(_i))>(a2)/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:+*/((int32_t)(_i))+(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[WHEN_CLAUSE]*/void r1249clear_all(T1249 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[WHEN_CLAUSE]*/void r1249remove(T1249 C,T2 a1,T2 a2){
T2 _i=0;
_i=a1;
while(1){
/*until*/if((_i)==(a2)) break;
/*RF7:put*/(C)[_i]=(/*RF8:item*/(C)[/*RF8:+*/((int32_t)(_i))+(INT32_C(1))/*:RF8*/]/*:RF8*/);
/*:RF7*/_i=/*RF8:+*/((int32_t)(_i))+(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[WHEN_CLAUSE]*/void r1249copy_slice_from(T1249 C,T1249 a1,T2 a2,T2 a3){
/*RF7:slice_copy*/{/*slice_copy*/
int a3tmp=a2;
memcpy((C)+(INT32_C(0)),(a1)+a3tmp,((a3)-a3tmp+1)*sizeof(T0*));}
/*:RF7*/}/*--*/

/*NATIVE_ARRAY[EXPORT_ITEM]*/T1257 r1257realloc(T1257 C,T2 a1,T2 a2){
T1257 R=(void*)0;
R=/*RF8:calloc*/se_calloc(a2,sizeof(T0*))/*:RF8*/;
/*RF3:copy_from*/r1257copy_from(R,C,/*RF8:-*/((int32_t)(a1))-(INT32_C(1))/*:RF8*/);
/*:RF3*/return R;
}/*--*/

/*NATIVE_ARRAY[EXPORT_ITEM]*/void r1257copy_from(T1257 C,T1257 a1,T2 a2){
/*RF3:copy_slice_from*/r1257copy_slice_from(C,a1,INT32_C(0),a2);
/*:RF3*/}/*--*/

/*NATIVE_ARRAY[EXPORT_ITEM]*/void r1257set_slice_with(T1257 C,T0* a1,T2 a2,T2 a3){
T2 _i=0;
_i=a2;
while(1){
/*until*/if(/*RF8:>*/((int32_t)(_i))>(a3)/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(a1);
/*:RF7*/_i=/*RF8:+*/((int32_t)(_i))+(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[EXPORT_ITEM]*/void r1257clear_all(T1257 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[EXPORT_ITEM]*/void r1257set_all_with(T1257 C,T0* a1,T2 a2){
/*RF3:set_slice_with*/r1257set_slice_with(C,a1,INT32_C(0),a2);
/*:RF3*/}/*--*/

/*NATIVE_ARRAY[EXPORT_ITEM]*/void r1257copy_slice_from(T1257 C,T1257 a1,T2 a2,T2 a3){
/*RF7:slice_copy*/{/*slice_copy*/
int a3tmp=a2;
memcpy((C)+(INT32_C(0)),(a1)+a3tmp,((a3)-a3tmp+1)*sizeof(T0*));}
/*:RF7*/}/*--*/

/*NATIVE_ARRAY[HASHED_SET_NODE[LIVE_TYPE]]*/void r1258clear_all(T1258 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[EXTERNAL_ROUTINE]*/T1261 r1261realloc(T1261 C,T2 a1,T2 a2){
T1261 R=(void*)0;
R=/*RF8:calloc*/se_calloc(a2,sizeof(T0*))/*:RF8*/;
/*RF3:copy_from*/r1261copy_from(R,C,/*RF8:-*/((int32_t)(a1))-(INT32_C(1))/*:RF8*/);
/*:RF3*/return R;
}/*--*/

/*NATIVE_ARRAY[EXTERNAL_ROUTINE]*/T2 r1261fast_index_of(T1261 C,T0* a1,T2 a2,T2 a3){
/*[INTERNAL_C_LOCAL list*/
T6 tmp0;
/*INTERNAL_C_LOCAL list]*/
T2 R=0;
R=a2;
while(1){
tmp0/*or else*/=((T6)(/*RF8:>*/((int32_t)(R))>(a3)/*:RF8*/));
if(tmp0/*or else*/){
}
else{
tmp0/*or else*/=((T6)((a1)==((void*)(/*RF8:item*/(C)[R]/*:RF8*/))));
}
/*until*/if(tmp0/*or else*/) break;
R=/*RF8:+*/((int32_t)(R))+(INT32_C(1))/*:RF8*/;
}
return R;
}/*--*/

/*NATIVE_ARRAY[EXTERNAL_ROUTINE]*/void r1261copy_from(T1261 C,T1261 a1,T2 a2){
/*RF3:copy_slice_from*/r1261copy_slice_from(C,a1,INT32_C(0),a2);
/*:RF3*/}/*--*/

/*NATIVE_ARRAY[EXTERNAL_ROUTINE]*/void r1261clear(T1261 C,T2 a1,T2 a2){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:>*/((int32_t)(_i))>(a2)/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:+*/((int32_t)(_i))+(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[EXTERNAL_ROUTINE]*/void r1261clear_all(T1261 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[EXTERNAL_ROUTINE]*/void r1261copy_slice_from(T1261 C,T1261 a1,T2 a2,T2 a3){
/*RF7:slice_copy*/{/*slice_copy*/
int a3tmp=a2;
memcpy((C)+(INT32_C(0)),(a1)+a3tmp,((a3)-a3tmp+1)*sizeof(T0*));}
/*:RF7*/}/*--*/

/*NATIVE_ARRAY[HASHED_DICTIONARY_NODE[ANONYMOUS_FEATURE,FEATURE_STAMP]]*/void r1264clear_all(T1264 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[TYPE]*/T1265 r1265realloc(T1265 C,T2 a1,T2 a2){
T1265 R=(void*)0;
R=/*RF8:calloc*/se_calloc(a2,sizeof(T0*))/*:RF8*/;
/*RF3:copy_from*/r1265copy_from(R,C,/*RF8:-*/((int32_t)(a1))-(INT32_C(1))/*:RF8*/);
/*:RF3*/return R;
}/*--*/

/*NATIVE_ARRAY[TYPE]*/T2 r1265fast_index_of(T1265 C,T0* a1,T2 a2,T2 a3){
/*[INTERNAL_C_LOCAL list*/
T6 tmp0;
/*INTERNAL_C_LOCAL list]*/
T2 R=0;
R=a2;
while(1){
tmp0/*or else*/=((T6)(/*RF8:>*/((int32_t)(R))>(a3)/*:RF8*/));
if(tmp0/*or else*/){
}
else{
tmp0/*or else*/=((T6)((a1)==((void*)(/*RF8:item*/(C)[R]/*:RF8*/))));
}
/*until*/if(tmp0/*or else*/) break;
R=/*RF8:+*/((int32_t)(R))+(INT32_C(1))/*:RF8*/;
}
return R;
}/*--*/

/*NATIVE_ARRAY[TYPE]*/void r1265copy_from(T1265 C,T1265 a1,T2 a2){
/*RF3:copy_slice_from*/r1265copy_slice_from(C,a1,INT32_C(0),a2);
/*:RF3*/}/*--*/

/*NATIVE_ARRAY[TYPE]*/void r1265clear(T1265 C,T2 a1,T2 a2){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:>*/((int32_t)(_i))>(a2)/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:+*/((int32_t)(_i))+(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[TYPE]*/void r1265set_slice_with(T1265 C,T0* a1,T2 a2,T2 a3){
T2 _i=0;
_i=a2;
while(1){
/*until*/if(/*RF8:>*/((int32_t)(_i))>(a3)/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(a1);
/*:RF7*/_i=/*RF8:+*/((int32_t)(_i))+(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[TYPE]*/void r1265clear_all(T1265 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[TYPE]*/void r1265remove(T1265 C,T2 a1,T2 a2){
T2 _i=0;
_i=a1;
while(1){
/*until*/if((_i)==(a2)) break;
/*RF7:put*/(C)[_i]=(/*RF8:item*/(C)[/*RF8:+*/((int32_t)(_i))+(INT32_C(1))/*:RF8*/]/*:RF8*/);
/*:RF7*/_i=/*RF8:+*/((int32_t)(_i))+(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[TYPE]*/void r1265set_all_with(T1265 C,T0* a1,T2 a2){
/*RF3:set_slice_with*/r1265set_slice_with(C,a1,INT32_C(0),a2);
/*:RF3*/}/*--*/

/*NATIVE_ARRAY[TYPE]*/void r1265copy_slice_from(T1265 C,T1265 a1,T2 a2,T2 a3){
/*RF7:slice_copy*/{/*slice_copy*/
int a3tmp=a2;
memcpy((C)+(INT32_C(0)),(a1)+a3tmp,((a3)-a3tmp+1)*sizeof(T0*));}
/*:RF7*/}/*--*/

/*NATIVE_ARRAY[RUN_FEATURE]*/T1266 r1266realloc(T1266 C,T2 a1,T2 a2){
T1266 R=(void*)0;
R=/*RF8:calloc*/se_calloc(a2,sizeof(T0*))/*:RF8*/;
/*RF3:copy_from*/r1266copy_from(R,C,/*RF8:-*/((int32_t)(a1))-(INT32_C(1))/*:RF8*/);
/*:RF3*/return R;
}/*--*/

/*NATIVE_ARRAY[RUN_FEATURE]*/T2 r1266fast_index_of(T1266 C,T0* a1,T2 a2,T2 a3){
/*[INTERNAL_C_LOCAL list*/
T6 tmp0;
/*INTERNAL_C_LOCAL list]*/
T2 R=0;
R=a2;
while(1){
tmp0/*or else*/=((T6)(/*RF8:>*/((int32_t)(R))>(a3)/*:RF8*/));
if(tmp0/*or else*/){
}
else{
tmp0/*or else*/=((T6)((a1)==((void*)(/*RF8:item*/(C)[R]/*:RF8*/))));
}
/*until*/if(tmp0/*or else*/) break;
R=/*RF8:+*/((int32_t)(R))+(INT32_C(1))/*:RF8*/;
}
return R;
}/*--*/

/*NATIVE_ARRAY[RUN_FEATURE]*/void r1266copy_from(T1266 C,T1266 a1,T2 a2){
/*RF3:copy_slice_from*/r1266copy_slice_from(C,a1,INT32_C(0),a2);
/*:RF3*/}/*--*/

/*NATIVE_ARRAY[RUN_FEATURE]*/void r1266clear(T1266 C,T2 a1,T2 a2){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:>*/((int32_t)(_i))>(a2)/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:+*/((int32_t)(_i))+(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[RUN_FEATURE]*/void r1266clear_all(T1266 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[RUN_FEATURE]*/void r1266copy_slice_from(T1266 C,T1266 a1,T2 a2,T2 a3){
/*RF7:slice_copy*/{/*slice_copy*/
int a3tmp=a2;
memcpy((C)+(INT32_C(0)),(a1)+a3tmp,((a3)-a3tmp+1)*sizeof(T0*));}
/*:RF7*/}/*--*/

/*NATIVE_ARRAY[LIVE_TYPE_EXTRA_COLLECTOR]*/T1267 r1267realloc(T1267 C,T2 a1,T2 a2){
T1267 R=(void*)0;
R=/*RF8:calloc*/se_calloc(a2,sizeof(T0*))/*:RF8*/;
/*RF3:copy_from*/r1267copy_from(R,C,/*RF8:-*/((int32_t)(a1))-(INT32_C(1))/*:RF8*/);
/*:RF3*/return R;
}/*--*/

/*NATIVE_ARRAY[LIVE_TYPE_EXTRA_COLLECTOR]*/void r1267copy_from(T1267 C,T1267 a1,T2 a2){
/*RF3:copy_slice_from*/r1267copy_slice_from(C,a1,INT32_C(0),a2);
/*:RF3*/}/*--*/

/*NATIVE_ARRAY[LIVE_TYPE_EXTRA_COLLECTOR]*/void r1267clear_all(T1267 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[LIVE_TYPE_EXTRA_COLLECTOR]*/void r1267copy_slice_from(T1267 C,T1267 a1,T2 a2,T2 a3){
/*RF7:slice_copy*/{/*slice_copy*/
int a3tmp=a2;
memcpy((C)+(INT32_C(0)),(a1)+a3tmp,((a3)-a3tmp+1)*sizeof(T0*));}
/*:RF7*/}/*--*/

/*NATIVE_ARRAY[ANONYMOUS_FEATURE]*/T1268 r1268realloc(T1268 C,T2 a1,T2 a2){
T1268 R=(void*)0;
R=/*RF8:calloc*/se_calloc(a2,sizeof(T0*))/*:RF8*/;
/*RF3:copy_from*/r1268copy_from(R,C,/*RF8:-*/((int32_t)(a1))-(INT32_C(1))/*:RF8*/);
/*:RF3*/return R;
}/*--*/

/*NATIVE_ARRAY[ANONYMOUS_FEATURE]*/T2 r1268fast_index_of(T1268 C,T0* a1,T2 a2,T2 a3){
/*[INTERNAL_C_LOCAL list*/
T6 tmp0;
/*INTERNAL_C_LOCAL list]*/
T2 R=0;
R=a2;
while(1){
tmp0/*or else*/=((T6)(/*RF8:>*/((int32_t)(R))>(a3)/*:RF8*/));
if(tmp0/*or else*/){
}
else{
tmp0/*or else*/=((T6)((a1)==((void*)(/*RF8:item*/(C)[R]/*:RF8*/))));
}
/*until*/if(tmp0/*or else*/) break;
R=/*RF8:+*/((int32_t)(R))+(INT32_C(1))/*:RF8*/;
}
return R;
}/*--*/

/*NATIVE_ARRAY[ANONYMOUS_FEATURE]*/void r1268copy_from(T1268 C,T1268 a1,T2 a2){
/*RF3:copy_slice_from*/r1268copy_slice_from(C,a1,INT32_C(0),a2);
/*:RF3*/}/*--*/

/*NATIVE_ARRAY[ANONYMOUS_FEATURE]*/void r1268clear(T1268 C,T2 a1,T2 a2){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:>*/((int32_t)(_i))>(a2)/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:+*/((int32_t)(_i))+(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[ANONYMOUS_FEATURE]*/void r1268clear_all(T1268 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[ANONYMOUS_FEATURE]*/void r1268copy_slice_from(T1268 C,T1268 a1,T2 a2,T2 a3){
/*RF7:slice_copy*/{/*slice_copy*/
int a3tmp=a2;
memcpy((C)+(INT32_C(0)),(a1)+a3tmp,((a3)-a3tmp+1)*sizeof(T0*));}
/*:RF7*/}/*--*/

/*NATIVE_ARRAY[HASHED_DICTIONARY_NODE[INTEGER_8,CLASS_TEXT]]*/void r1269clear_all(T1269 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[HASHED_DICTIONARY_NODE[TAGGED_DATA,FIXED_STRING]]*/void r1272clear_all(T1272 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[HASHED_DICTIONARY_NODE[ANONYMOUS_FEATURE,FEATURE_NAME]]*/void r1279clear_all(T1279 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[HASHED_DICTIONARY_NODE[INTEGER_8,TYPE]]*/void r1281clear_all(T1281 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[HASHED_BIJECTIVE_DICTIONARY_NODE[FEATURE_STAMP,FEATURE_NAME]]*/void r1288clear_all(T1288 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[HASHED_DICTIONARY_NODE[RUN_FEATURE,TYPE]]*/void r1294clear_all(T1294 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[FEATURE_STAMP]*/T1295 r1295realloc(T1295 C,T2 a1,T2 a2){
T1295 R=(void*)0;
R=/*RF8:calloc*/se_calloc(a2,sizeof(T0*))/*:RF8*/;
/*RF3:copy_from*/r1295copy_from(R,C,/*RF8:-*/((int32_t)(a1))-(INT32_C(1))/*:RF8*/);
/*:RF3*/return R;
}/*--*/

/*NATIVE_ARRAY[FEATURE_STAMP]*/T2 r1295fast_index_of(T1295 C,T0* a1,T2 a2,T2 a3){
/*[INTERNAL_C_LOCAL list*/
T6 tmp0;
/*INTERNAL_C_LOCAL list]*/
T2 R=0;
R=a2;
while(1){
tmp0/*or else*/=((T6)(/*RF8:>*/((int32_t)(R))>(a3)/*:RF8*/));
if(tmp0/*or else*/){
}
else{
tmp0/*or else*/=((T6)((a1)==((void*)(/*RF8:item*/(C)[R]/*:RF8*/))));
}
/*until*/if(tmp0/*or else*/) break;
R=/*RF8:+*/((int32_t)(R))+(INT32_C(1))/*:RF8*/;
}
return R;
}/*--*/

/*NATIVE_ARRAY[FEATURE_STAMP]*/void r1295copy_from(T1295 C,T1295 a1,T2 a2){
/*RF3:copy_slice_from*/r1295copy_slice_from(C,a1,INT32_C(0),a2);
/*:RF3*/}/*--*/

/*NATIVE_ARRAY[FEATURE_STAMP]*/void r1295clear(T1295 C,T2 a1,T2 a2){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:>*/((int32_t)(_i))>(a2)/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:+*/((int32_t)(_i))+(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[FEATURE_STAMP]*/void r1295set_slice_with(T1295 C,T0* a1,T2 a2,T2 a3){
T2 _i=0;
_i=a2;
while(1){
/*until*/if(/*RF8:>*/((int32_t)(_i))>(a3)/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(a1);
/*:RF7*/_i=/*RF8:+*/((int32_t)(_i))+(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[FEATURE_STAMP]*/void r1295clear_all(T1295 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[FEATURE_STAMP]*/void r1295set_all_with(T1295 C,T0* a1,T2 a2){
/*RF3:set_slice_with*/r1295set_slice_with(C,a1,INT32_C(0),a2);
/*:RF3*/}/*--*/

/*NATIVE_ARRAY[FEATURE_STAMP]*/void r1295copy_slice_from(T1295 C,T1295 a1,T2 a2,T2 a3){
/*RF7:slice_copy*/{/*slice_copy*/
int a3tmp=a2;
memcpy((C)+(INT32_C(0)),(a1)+a3tmp,((a3)-a3tmp+1)*sizeof(T0*));}
/*:RF7*/}/*--*/

/*NATIVE_ARRAY[INTEGER_64]*/T1296 r1296realloc(T1296 C,T2 a1,T2 a2){
T1296 R=(void*)0;
R=/*RF8:calloc*/se_calloc(a2,sizeof(T11))/*:RF8*/;
/*RF3:copy_from*/r1296copy_from(R,C,/*RF8:-*/((int32_t)(a1))-(INT32_C(1))/*:RF8*/);
/*:RF3*/return R;
}/*--*/

/*NATIVE_ARRAY[INTEGER_64]*/void r1296copy_from(T1296 C,T1296 a1,T2 a2){
/*RF3:copy_slice_from*/r1296copy_slice_from(C,a1,INT32_C(0),a2);
/*:RF3*/}/*--*/

/*NATIVE_ARRAY[INTEGER_64]*/void r1296clear(T1296 C,T2 a1,T2 a2){
T11 _v=0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:>*/((int32_t)(_i))>(a2)/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:+*/((int32_t)(_i))+(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[INTEGER_64]*/void r1296clear_all(T1296 C,T2 a1){
T11 _v=0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[INTEGER_64]*/void r1296copy_slice_from(T1296 C,T1296 a1,T2 a2,T2 a3){
/*RF7:slice_copy*/{/*slice_copy*/
int a3tmp=a2;
memcpy((C)+(INT32_C(0)),(a1)+a3tmp,((a3)-a3tmp+1)*sizeof(T11));}
/*:RF7*/}/*--*/

/*NATIVE_ARRAY[FAST_ARRAY[CODE]]*/T1297 r1297realloc(T1297 C,T2 a1,T2 a2){
T1297 R=(void*)0;
R=/*RF8:calloc*/se_calloc(a2,sizeof(T0*))/*:RF8*/;
/*RF3:copy_from*/r1297copy_from(R,C,/*RF8:-*/((int32_t)(a1))-(INT32_C(1))/*:RF8*/);
/*:RF3*/return R;
}/*--*/

/*NATIVE_ARRAY[FAST_ARRAY[CODE]]*/void r1297copy_from(T1297 C,T1297 a1,T2 a2){
/*RF3:copy_slice_from*/r1297copy_slice_from(C,a1,INT32_C(0),a2);
/*:RF3*/}/*--*/

/*NATIVE_ARRAY[FAST_ARRAY[CODE]]*/void r1297clear(T1297 C,T2 a1,T2 a2){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:>*/((int32_t)(_i))>(a2)/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:+*/((int32_t)(_i))+(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[FAST_ARRAY[CODE]]*/void r1297clear_all(T1297 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[FAST_ARRAY[CODE]]*/void r1297copy_slice_from(T1297 C,T1297 a1,T2 a2,T2 a3){
/*RF7:slice_copy*/{/*slice_copy*/
int a3tmp=a2;
memcpy((C)+(INT32_C(0)),(a1)+a3tmp,((a3)-a3tmp+1)*sizeof(T0*));}
/*:RF7*/}/*--*/

/*NATIVE_ARRAY[CODE]*/T1298 r1298realloc(T1298 C,T2 a1,T2 a2){
T1298 R=(void*)0;
R=/*RF8:calloc*/se_calloc(a2,sizeof(T0*))/*:RF8*/;
/*RF3:copy_from*/r1298copy_from(R,C,/*RF8:-*/((int32_t)(a1))-(INT32_C(1))/*:RF8*/);
/*:RF3*/return R;
}/*--*/

/*NATIVE_ARRAY[CODE]*/void r1298copy_from(T1298 C,T1298 a1,T2 a2){
/*RF3:copy_slice_from*/r1298copy_slice_from(C,a1,INT32_C(0),a2);
/*:RF3*/}/*--*/

/*NATIVE_ARRAY[CODE]*/void r1298clear(T1298 C,T2 a1,T2 a2){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:>*/((int32_t)(_i))>(a2)/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:+*/((int32_t)(_i))+(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[CODE]*/void r1298clear_all(T1298 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[CODE]*/void r1298copy_slice_from(T1298 C,T1298 a1,T2 a2,T2 a3){
/*RF7:slice_copy*/{/*slice_copy*/
int a3tmp=a2;
memcpy((C)+(INT32_C(0)),(a1)+a3tmp,((a3)-a3tmp+1)*sizeof(T0*));}
/*:RF7*/}/*--*/

/*NATIVE_ARRAY[HASHED_DICTIONARY_NODE[GRAPH_NODE,TYPE]]*/void r1300clear_all(T1300 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[HASHED_SET_NODE[TYPE]]*/void r1303clear_all(T1303 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[HASHED_SET_NODE[STRING]]*/void r1306clear_all(T1306 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[HASHED_DICTIONARY_NODE[MANIFEST_STRING,STRING]]*/void r1311clear_all(T1311 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[HASHED_DICTIONARY_NODE[MANIFEST_STRING,MANIFEST_STRING]]*/void r1314clear_all(T1314 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[HASHED_SET_NODE[MANIFEST_GENERIC]]*/void r1315clear_all(T1315 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[NON_VOID_NO_DISPATCH]*/T1318 r1318realloc(T1318 C,T2 a1,T2 a2){
T1318 R=(void*)0;
R=/*RF8:calloc*/se_calloc(a2,sizeof(T0*))/*:RF8*/;
/*RF3:copy_from*/r1318copy_from(R,C,/*RF8:-*/((int32_t)(a1))-(INT32_C(1))/*:RF8*/);
/*:RF3*/return R;
}/*--*/

/*NATIVE_ARRAY[NON_VOID_NO_DISPATCH]*/T2 r1318fast_index_of(T1318 C,T0* a1,T2 a2,T2 a3){
/*[INTERNAL_C_LOCAL list*/
T6 tmp0;
/*INTERNAL_C_LOCAL list]*/
T2 R=0;
R=a2;
while(1){
tmp0/*or else*/=((T6)(/*RF8:>*/((int32_t)(R))>(a3)/*:RF8*/));
if(tmp0/*or else*/){
}
else{
tmp0/*or else*/=((T6)((a1)==((void*)(/*RF8:item*/(C)[R]/*:RF8*/))));
}
/*until*/if(tmp0/*or else*/) break;
R=/*RF8:+*/((int32_t)(R))+(INT32_C(1))/*:RF8*/;
}
return R;
}/*--*/

/*NATIVE_ARRAY[NON_VOID_NO_DISPATCH]*/void r1318copy_from(T1318 C,T1318 a1,T2 a2){
/*RF3:copy_slice_from*/r1318copy_slice_from(C,a1,INT32_C(0),a2);
/*:RF3*/}/*--*/

/*NATIVE_ARRAY[NON_VOID_NO_DISPATCH]*/void r1318clear(T1318 C,T2 a1,T2 a2){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:>*/((int32_t)(_i))>(a2)/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:+*/((int32_t)(_i))+(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[NON_VOID_NO_DISPATCH]*/void r1318clear_all(T1318 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[NON_VOID_NO_DISPATCH]*/void r1318copy_slice_from(T1318 C,T1318 a1,T2 a2,T2 a3){
/*RF7:slice_copy*/{/*slice_copy*/
int a3tmp=a2;
memcpy((C)+(INT32_C(0)),(a1)+a3tmp,((a3)-a3tmp+1)*sizeof(T0*));}
/*:RF7*/}/*--*/

/*NATIVE_ARRAY[HASHED_DICTIONARY_NODE[FAST_ARRAY[AGENT_CREATION],TYPE]]*/void r1320clear_all(T1320 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[HASHED_SET_NODE[AGENT_ARGS]]*/void r1322clear_all(T1322 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[HASHED_DICTIONARY_NODE[HASHED_SET[TYPE],TYPE]]*/void r1326clear_all(T1326 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[HASHED_SET[TYPE]]*/T1328 r1328realloc(T1328 C,T2 a1,T2 a2){
T1328 R=(void*)0;
R=/*RF8:calloc*/se_calloc(a2,sizeof(T0*))/*:RF8*/;
/*RF3:copy_from*/r1328copy_from(R,C,/*RF8:-*/((int32_t)(a1))-(INT32_C(1))/*:RF8*/);
/*:RF3*/return R;
}/*--*/

/*NATIVE_ARRAY[HASHED_SET[TYPE]]*/void r1328copy_from(T1328 C,T1328 a1,T2 a2){
/*RF3:copy_slice_from*/r1328copy_slice_from(C,a1,INT32_C(0),a2);
/*:RF3*/}/*--*/

/*NATIVE_ARRAY[HASHED_SET[TYPE]]*/void r1328clear(T1328 C,T2 a1,T2 a2){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:>*/((int32_t)(_i))>(a2)/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:+*/((int32_t)(_i))+(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[HASHED_SET[TYPE]]*/void r1328clear_all(T1328 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[HASHED_SET[TYPE]]*/void r1328copy_slice_from(T1328 C,T1328 a1,T2 a2,T2 a3){
/*RF7:slice_copy*/{/*slice_copy*/
int a3tmp=a2;
memcpy((C)+(INT32_C(0)),(a1)+a3tmp,((a3)-a3tmp+1)*sizeof(T0*));}
/*:RF7*/}/*--*/

/*NATIVE_ARRAY[WEAK_REFERENCE[FAST_ARRAY[FIXED_STRING]]]*/T1329 r1329realloc(T1329 C,T2 a1,T2 a2){
T1329 R=(void*)0;
R=/*RF8:calloc*/se_calloc(a2,sizeof(T0*))/*:RF8*/;
/*RF3:copy_from*/r1329copy_from(R,C,/*RF8:-*/((int32_t)(a1))-(INT32_C(1))/*:RF8*/);
/*:RF3*/return R;
}/*--*/

/*NATIVE_ARRAY[WEAK_REFERENCE[FAST_ARRAY[FIXED_STRING]]]*/void r1329copy_from(T1329 C,T1329 a1,T2 a2){
/*RF3:copy_slice_from*/r1329copy_slice_from(C,a1,INT32_C(0),a2);
/*:RF3*/}/*--*/

/*NATIVE_ARRAY[WEAK_REFERENCE[FAST_ARRAY[FIXED_STRING]]]*/void r1329clear(T1329 C,T2 a1,T2 a2){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:>*/((int32_t)(_i))>(a2)/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:+*/((int32_t)(_i))+(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[WEAK_REFERENCE[FAST_ARRAY[FIXED_STRING]]]*/void r1329clear_all(T1329 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[WEAK_REFERENCE[FAST_ARRAY[FIXED_STRING]]]*/void r1329copy_slice_from(T1329 C,T1329 a1,T2 a2,T2 a3){
/*RF7:slice_copy*/{/*slice_copy*/
int a3tmp=a2;
memcpy((C)+(INT32_C(0)),(a1)+a3tmp,((a3)-a3tmp+1)*sizeof(T0*));}
/*:RF7*/}/*--*/

/*NATIVE_ARRAY[HASHED_DICTIONARY_NODE[FEATURE_STAMP,FEATURE_NAME]]*/void r1330clear_all(T1330 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[ANONYMOUS_FEATURE_MIXER]*/T1333 r1333realloc(T1333 C,T2 a1,T2 a2){
T1333 R=(void*)0;
R=/*RF8:calloc*/se_calloc(a2,sizeof(T0*))/*:RF8*/;
/*RF3:copy_from*/r1333copy_from(R,C,/*RF8:-*/((int32_t)(a1))-(INT32_C(1))/*:RF8*/);
/*:RF3*/return R;
}/*--*/

/*NATIVE_ARRAY[ANONYMOUS_FEATURE_MIXER]*/void r1333copy_from(T1333 C,T1333 a1,T2 a2){
/*RF3:copy_slice_from*/r1333copy_slice_from(C,a1,INT32_C(0),a2);
/*:RF3*/}/*--*/

/*NATIVE_ARRAY[ANONYMOUS_FEATURE_MIXER]*/void r1333clear(T1333 C,T2 a1,T2 a2){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:>*/((int32_t)(_i))>(a2)/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:+*/((int32_t)(_i))+(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[ANONYMOUS_FEATURE_MIXER]*/void r1333clear_all(T1333 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[ANONYMOUS_FEATURE_MIXER]*/void r1333copy_slice_from(T1333 C,T1333 a1,T2 a2,T2 a3){
/*RF7:slice_copy*/{/*slice_copy*/
int a3tmp=a2;
memcpy((C)+(INT32_C(0)),(a1)+a3tmp,((a3)-a3tmp+1)*sizeof(T0*));}
/*:RF7*/}/*--*/

/*NATIVE_ARRAY[HASHED_DICTIONARY_NODE[ANONYMOUS_FEATURE_MIXER,FEATURE_NAME]]*/void r1337clear_all(T1337 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[HASHED_SET_NODE[ABSOLUTE_FEATURE_NAME]]*/void r1338clear_all(T1338 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[HASHED_DICTIONARY_NODE[FEATURE_STAMP,ABSOLUTE_FEATURE_NAME]]*/void r1343clear_all(T1343 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[HASHED_DICTIONARY_NODE[ANONYMOUS_FEATURE,TYPE]]*/void r1346clear_all(T1346 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[ARRAY[INTEGER_8]]*/void r1347set_slice_with(T1347 C,T0* a1,T2 a2,T2 a3){
T2 _i=0;
_i=a2;
while(1){
/*until*/if(/*RF8:>*/((int32_t)(_i))>(a3)/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(a1);
/*:RF7*/_i=/*RF8:+*/((int32_t)(_i))+(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[ARRAY[INTEGER_8]]*/void r1347clear_all(T1347 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[ARRAY[INTEGER_8]]*/void r1347set_all_with(T1347 C,T0* a1,T2 a2){
/*RF3:set_slice_with*/r1347set_slice_with(C,a1,INT32_C(0),a2);
/*:RF3*/}/*--*/

/*NATIVE_ARRAY[INTEGER_8]*/void r1348set_slice_with(T1348 C,T1 a1,T2 a2,T2 a3){
T2 _i=0;
_i=a2;
while(1){
/*until*/if(/*RF8:>*/((int32_t)(_i))>(a3)/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(a1);
/*:RF7*/_i=/*RF8:+*/((int32_t)(_i))+(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[INTEGER_8]*/void r1348clear_all(T1348 C,T2 a1){
T1 _v=0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[INTEGER_8]*/void r1348set_all_with(T1348 C,T1 a1,T2 a2){
/*RF3:set_slice_with*/r1348set_slice_with(C,a1,INT32_C(0),a2);
/*:RF3*/}/*--*/

/*NATIVE_ARRAY[HASHED_DICTIONARY_NODE[WEAK_REFERENCE[ANY_HASHED_SET_NODE],STRING]]*/void r1351clear_all(T1351 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[ABSTRACT_STRING]*/T1353 r1353realloc(T1353 C,T2 a1,T2 a2){
T1353 R=(void*)0;
R=/*RF8:calloc*/se_calloc(a2,sizeof(T0*))/*:RF8*/;
/*RF3:copy_from*/r1353copy_from(R,C,/*RF8:-*/((int32_t)(a1))-(INT32_C(1))/*:RF8*/);
/*:RF3*/return R;
}/*--*/

/*NATIVE_ARRAY[ABSTRACT_STRING]*/void r1353copy_from(T1353 C,T1353 a1,T2 a2){
/*RF3:copy_slice_from*/r1353copy_slice_from(C,a1,INT32_C(0),a2);
/*:RF3*/}/*--*/

/*NATIVE_ARRAY[ABSTRACT_STRING]*/void r1353clear(T1353 C,T2 a1,T2 a2){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:>*/((int32_t)(_i))>(a2)/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:+*/((int32_t)(_i))+(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[ABSTRACT_STRING]*/void r1353clear_all(T1353 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[ABSTRACT_STRING]*/void r1353copy_slice_from(T1353 C,T1353 a1,T2 a2,T2 a3){
/*RF7:slice_copy*/{/*slice_copy*/
int a3tmp=a2;
memcpy((C)+(INT32_C(0)),(a1)+a3tmp,((a3)-a3tmp+1)*sizeof(T0*));}
/*:RF7*/}/*--*/

/*NATIVE_ARRAY[CECIL_ENTRY]*/T1354 r1354realloc(T1354 C,T2 a1,T2 a2){
T1354 R=(void*)0;
R=/*RF8:calloc*/se_calloc(a2,sizeof(T0*))/*:RF8*/;
/*RF3:copy_from*/r1354copy_from(R,C,/*RF8:-*/((int32_t)(a1))-(INT32_C(1))/*:RF8*/);
/*:RF3*/return R;
}/*--*/

/*NATIVE_ARRAY[CECIL_ENTRY]*/void r1354copy_from(T1354 C,T1354 a1,T2 a2){
/*RF3:copy_slice_from*/r1354copy_slice_from(C,a1,INT32_C(0),a2);
/*:RF3*/}/*--*/

/*NATIVE_ARRAY[CECIL_ENTRY]*/void r1354clear(T1354 C,T2 a1,T2 a2){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:>*/((int32_t)(_i))>(a2)/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:+*/((int32_t)(_i))+(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[CECIL_ENTRY]*/void r1354clear_all(T1354 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[CECIL_ENTRY]*/void r1354copy_slice_from(T1354 C,T1354 a1,T2 a2,T2 a3){
/*RF7:slice_copy*/{/*slice_copy*/
int a3tmp=a2;
memcpy((C)+(INT32_C(0)),(a1)+a3tmp,((a3)-a3tmp+1)*sizeof(T0*));}
/*:RF7*/}/*--*/

/*NATIVE_ARRAY[SE_CONFIG]*/T1361 r1361realloc(T1361 C,T2 a1,T2 a2){
T1361 R=(void*)0;
R=/*RF8:calloc*/se_calloc(a2,sizeof(T0*))/*:RF8*/;
/*RF3:copy_from*/r1361copy_from(R,C,/*RF8:-*/((int32_t)(a1))-(INT32_C(1))/*:RF8*/);
/*:RF3*/return R;
}/*--*/

/*NATIVE_ARRAY[SE_CONFIG]*/void r1361copy_from(T1361 C,T1361 a1,T2 a2){
/*RF3:copy_slice_from*/r1361copy_slice_from(C,a1,INT32_C(0),a2);
/*:RF3*/}/*--*/

/*NATIVE_ARRAY[SE_CONFIG]*/void r1361set_slice_with(T1361 C,T0* a1,T2 a2,T2 a3){
T2 _i=0;
_i=a2;
while(1){
/*until*/if(/*RF8:>*/((int32_t)(_i))>(a3)/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(a1);
/*:RF7*/_i=/*RF8:+*/((int32_t)(_i))+(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[SE_CONFIG]*/void r1361clear_all(T1361 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[SE_CONFIG]*/void r1361set_all_with(T1361 C,T0* a1,T2 a2){
/*RF3:set_slice_with*/r1361set_slice_with(C,a1,INT32_C(0),a2);
/*:RF3*/}/*--*/

/*NATIVE_ARRAY[SE_CONFIG]*/void r1361copy_slice_from(T1361 C,T1361 a1,T2 a2,T2 a3){
/*RF7:slice_copy*/{/*slice_copy*/
int a3tmp=a2;
memcpy((C)+(INT32_C(0)),(a1)+a3tmp,((a3)-a3tmp+1)*sizeof(T0*));}
/*:RF7*/}/*--*/

/*NATIVE_ARRAY[STRING_RECYCLING_ITEM]*/T1362 r1362realloc(T1362 C,T2 a1,T2 a2){
T1362 R=(void*)0;
R=/*RF8:calloc*/se_calloc(a2,sizeof(T317))/*:RF8*/;
/*RF3:copy_from*/r1362copy_from(R,C,/*RF8:-*/((int32_t)(a1))-(INT32_C(1))/*:RF8*/);
/*:RF3*/return R;
}/*--*/

/*NATIVE_ARRAY[STRING_RECYCLING_ITEM]*/void r1362copy_from(T1362 C,T1362 a1,T2 a2){
/*RF3:copy_slice_from*/r1362copy_slice_from(C,a1,INT32_C(0),a2);
/*:RF3*/}/*--*/

/*NATIVE_ARRAY[STRING_RECYCLING_ITEM]*/void r1362clear_all(T1362 C,T2 a1){
T317 _v={(void*)0,0};
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/{
T317 a1tmp=_v;
memcpy(&((C)[_i]),&a1tmp,sizeof(T317));}
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[STRING_RECYCLING_ITEM]*/void r1362slice_copy(T1362 C,T2 a1,T1362 a2,T2 a3,T2 a4){
/*[INTERNAL_C_LOCAL list*/
T2 tmp0;
/*INTERNAL_C_LOCAL list]*/
tmp0/*copy index*/=a3;
while(1){
/*until*/if(/*RF8:>*/((int32_t)(tmp0/*copy index*/))>(a4)/*:RF8*/) break;
/*RF3:copy*/r317copy(&(/*NAI*/(C[/*RF8:-*/((int32_t)(/*RF8:+*/((int32_t)(tmp0/*copy index*/))+(a1)/*:RF8*/))-(a3)/*:RF8*/])),/*NAI*/((a2)[tmp0/*copy index*/]));
/*:RF3*/tmp0/*copy index*/=/*RF8:+*/((int32_t)(tmp0/*copy index*/))+(INT8_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[STRING_RECYCLING_ITEM]*/void r1362copy_slice_from(T1362 C,T1362 a1,T2 a2,T2 a3){
/*RF7:slice_copy*/r1362slice_copy(C,INT32_C(0),a1,a2,a3);
/*:RF7*/}/*--*/

/*NATIVE_ARRAY[HASHED_DICTIONARY_NODE[SE_C_MODE,STRING]]*/void r1365clear_all(T1365 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[PROCEDURE[TUPLE]]*/void r1367set_slice_with(T1367 C,T0* a1,T2 a2,T2 a3){
T2 _i=0;
_i=a2;
while(1){
/*until*/if(/*RF8:>*/((int32_t)(_i))>(a3)/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(a1);
/*:RF7*/_i=/*RF8:+*/((int32_t)(_i))+(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[PROCEDURE[TUPLE]]*/void r1367clear_all(T1367 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[PROCEDURE[TUPLE]]*/void r1367set_all_with(T1367 C,T0* a1,T2 a2){
/*RF3:set_slice_with*/r1367set_slice_with(C,a1,INT32_C(0),a2);
/*:RF3*/}/*--*/

/*NATIVE_ARRAY[HASHED_DICTIONARY_NODE[ORDERED_DICTIONARY[STRING,STRING],STRING]]*/void r1368clear_all(T1368 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[HASHED_DICTIONARY_NODE[CLUSTER,STRING]]*/void r1375clear_all(T1375 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[TEXT_FILE_READ]*/void r1377clear_all(T1377 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[HASHED_DICTIONARY_NODE[TEXT_FILE_READ,STRING]]*/void r1380clear_all(T1380 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[HASHED_DICTIONARY_NODE[CLUSTER_CLASS,HASHED_STRING]]*/void r1381clear_all(T1381 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[FORMAL_GENERIC_ARG]*/T1384 r1384realloc(T1384 C,T2 a1,T2 a2){
T1384 R=(void*)0;
R=/*RF8:calloc*/se_calloc(a2,sizeof(T0*))/*:RF8*/;
/*RF3:copy_from*/r1384copy_from(R,C,/*RF8:-*/((int32_t)(a1))-(INT32_C(1))/*:RF8*/);
/*:RF3*/return R;
}/*--*/

/*NATIVE_ARRAY[FORMAL_GENERIC_ARG]*/void r1384copy_from(T1384 C,T1384 a1,T2 a2){
/*RF3:copy_slice_from*/r1384copy_slice_from(C,a1,INT32_C(0),a2);
/*:RF3*/}/*--*/

/*NATIVE_ARRAY[FORMAL_GENERIC_ARG]*/void r1384set_slice_with(T1384 C,T0* a1,T2 a2,T2 a3){
T2 _i=0;
_i=a2;
while(1){
/*until*/if(/*RF8:>*/((int32_t)(_i))>(a3)/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(a1);
/*:RF7*/_i=/*RF8:+*/((int32_t)(_i))+(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[FORMAL_GENERIC_ARG]*/void r1384clear_all(T1384 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[FORMAL_GENERIC_ARG]*/void r1384set_all_with(T1384 C,T0* a1,T2 a2){
/*RF3:set_slice_with*/r1384set_slice_with(C,a1,INT32_C(0),a2);
/*:RF3*/}/*--*/

/*NATIVE_ARRAY[FORMAL_GENERIC_ARG]*/void r1384copy_slice_from(T1384 C,T1384 a1,T2 a2,T2 a3){
/*RF7:slice_copy*/{/*slice_copy*/
int a3tmp=a2;
memcpy((C)+(INT32_C(0)),(a1)+a3tmp,((a3)-a3tmp+1)*sizeof(T0*));}
/*:RF7*/}/*--*/

/*NATIVE_ARRAY[HASHED_DICTIONARY_NODE[FEATURE_STAMP,TYPE]]*/void r1387clear_all(T1387 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[HASHED_DICTIONARY_NODE[TYPE_MARK,TYPE]]*/void r1390clear_all(T1390 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[REQUIRE_ASSERTION]*/T1392 r1392realloc(T1392 C,T2 a1,T2 a2){
T1392 R=(void*)0;
R=/*RF8:calloc*/se_calloc(a2,sizeof(T0*))/*:RF8*/;
/*RF3:copy_from*/r1392copy_from(R,C,/*RF8:-*/((int32_t)(a1))-(INT32_C(1))/*:RF8*/);
/*:RF3*/return R;
}/*--*/

/*NATIVE_ARRAY[REQUIRE_ASSERTION]*/void r1392copy_from(T1392 C,T1392 a1,T2 a2){
/*RF3:copy_slice_from*/r1392copy_slice_from(C,a1,INT32_C(0),a2);
/*:RF3*/}/*--*/

/*NATIVE_ARRAY[REQUIRE_ASSERTION]*/void r1392clear(T1392 C,T2 a1,T2 a2){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:>*/((int32_t)(_i))>(a2)/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:+*/((int32_t)(_i))+(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[REQUIRE_ASSERTION]*/void r1392clear_all(T1392 C,T2 a1){
T0* _v=(void*)0;
T2 _i=0;
_i=a1;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:put*/(C)[_i]=(_v);
/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*NATIVE_ARRAY[REQUIRE_ASSERTION]*/void r1392copy_slice_from(T1392 C,T1392 a1,T2 a2,T2 a3){
/*RF7:slice_copy*/{/*slice_copy*/
int a3tmp=a2;
memcpy((C)+(INT32_C(0)),(a1)+a3tmp,((a3)-a3tmp+1)*sizeof(T0*));}
/*:RF7*/}/*--*/

#ifdef __cplusplus
}
#endif
