#ifdef __cplusplus
extern "C" {
#endif
/*
ANSI C code generated by 
Liberty Eiffel The GNU Eiffel Compiler, Eiffel tools and libraries
    release 2013.09 (Charles Adler, Jr.)

Copyright (C), 2011-2013 - C.ADRIAN, P.REDAELLI, R.MACK
    http://www.liberty-eiffel.org

Original SmartEiffel code:
Copyright (C), 1994-2002 - INRIA - LORIA - ESIAL UHP Nancy 1 - FRANCE
Copyright (C), 2003-2005 - INRIA - LORIA - IUT Charlemagne Nancy 2 - FRANCE
D.COLNET, P.RIBET, C.ADRIAN, V.CROIZIER, F.MERIZEN
    http://smarteiffel.loria.fr
C Compiler options used: -pipe -O2 -fno-gcse
*/

#ifdef __cplusplus
}
#endif
#include "compile_to_c.h"
#ifdef __cplusplus
extern "C" {
#endif

/*ITERATOR_ON_DICTIONARY_KEYS[STRING,STRING]*/void r3075make(T3075* C,T0* a1){
/*SFN*/(C->_dictionary/*Tiip*/)=a1;
/*RF3:start*/r3075start(C);
/*:RF3*/}/*--*/

/*ITERATOR_ON_DICTIONARY_KEYS[STRING,STRING]*/T6 r3075is_off(T3075* C){
/*[INTERNAL_C_LOCAL list*/
T2 tmp0;
/*INTERNAL_C_LOCAL list]*/
T6 R=0;
/*[inspectDynamicDispatch*/
switch((((/*RF2:dictionary*/(C)->_dictionary/*Tiip*//*:RF2*/))->id)){
case 2575:
tmp0/*count*/=(/*RF2:count*/(((T2575*)(/*RF2:dictionary*/(C)->_dictionary/*Tiip*//*:RF2*/)))->_count/*Tpipiiini*//*:RF2*/);
break;
default:;
tmp0/*count*/=(/*RF2:count*/(((T2761*)(/*RF2:dictionary*/(C)->_dictionary/*Tiip*//*:RF2*/)))->_count/*T2pipiiini*//*:RF2*/);
}
/*inspect]*/
R=((T6)(/*RF8:>*/((int32_t)((/*RF2:item_index*/(C)->_item_index/*Tiip*//*:RF2*/)))>(tmp0/*count*/)/*:RF8*/));
return R;
}/*--*/

/*ITERATOR_ON_DICTIONARY_KEYS[STRING,STRING]*/void r3075next(T3075* C){
/*SFN*/(C->_item_index/*Tiip*/)=/*RF8:+*/((int32_t)((/*RF2:item_index*/(C)->_item_index/*Tiip*//*:RF2*/)))+(INT32_C(1))/*:RF8*/;
}/*--*/

/*ITERATOR_ON_DICTIONARY_KEYS[STRING,STRING]*/T2 r3075iterable_generation(T3075* C){
/*[INTERNAL_C_LOCAL list*/
T2 tmp0;
/*INTERNAL_C_LOCAL list]*/
T2 R=0;
/*[inspectDynamicDispatch*/
switch((((/*RF2:dictionary*/(C)->_dictionary/*Tiip*//*:RF2*/))->id)){
case 2575:
tmp0/*generation*/=(/*RF2:generation*/(((T2575*)(/*RF2:dictionary*/(C)->_dictionary/*Tiip*//*:RF2*/)))->_generation/*Tpipiiini*//*:RF2*/);
break;
default:;
tmp0/*generation*/=(/*RF2:generation*/(((T2761*)(/*RF2:dictionary*/(C)->_dictionary/*Tiip*//*:RF2*/)))->_generation/*T2pipiiini*//*:RF2*/);
}
/*inspect]*/
R=tmp0/*generation*/;
return R;
}/*--*/

/*ITERATOR_ON_DICTIONARY_KEYS[STRING,STRING]*/T0* r3075item(T3075* C){
/*[INTERNAL_C_LOCAL list*/
T0* tmp0;
/*INTERNAL_C_LOCAL list]*/
T0* R=(void*)0;
/*[inspectDynamicDispatch*/
switch((((/*RF2:dictionary*/(C)->_dictionary/*Tiip*//*:RF2*/))->id)){
case 2575:
tmp0/*key*/=/*RF4:key*/r2575key(((T2575*)(/*RF2:dictionary*/(C)->_dictionary/*Tiip*//*:RF2*/)),(/*RF2:item_index*/(C)->_item_index/*Tiip*//*:RF2*/))/*:RF4*/;
break;
default:;
tmp0/*key*/=/*RF4:key*/r2761key(((T2761*)(/*RF2:dictionary*/(C)->_dictionary/*Tiip*//*:RF2*/)),(/*RF2:item_index*/(C)->_item_index/*Tiip*//*:RF2*/))/*:RF4*/;
}
/*inspect]*/
R=tmp0/*key*/;
return R;
}/*--*/

/*ITERATOR_ON_DICTIONARY_KEYS[STRING,STRING]*/void r3075start(T3075* C){
/*SFN*/(C->_item_index/*Tiip*/)=INT32_C(1);
/*SFN*/(C->_generation/*Tiip*/)=/*RF4:iterable_generation*/r3075iterable_generation(C)/*:RF4*/;
}/*--*/

/*REVERSE_COLLECTION_SORTER[INTEGER_32]*/T2 r3076insert_index(T0* a1,T2 a2){
T2 R=0;
T2 _min=0;
T2 _max=0;
_min=INT32_C(0);
_max=/*RF8:+*/((int32_t)((/*RF2:upper*/(((T2585*)/*ND*/(T0*)(a1)))->_upper/*iini*//*:RF2*/)))+(INT32_C(1))/*:RF8*/;
while(1){
/*until*/if((_min)==(_max)) break;
R=/*RF8:#//*/((int32_t)(/*RF8:+*/((int32_t)(_min))+(_max)/*:RF8*/))/(INT32_C(2))/*:RF8*/;
if(/*RF4:lte*/r3076lte(/*RF8:item*/((/*RF2:storage*/(((T2585*)/*ND*/(T0*)(a1)))->_storage/*iini*//*:RF2*/))[R]/*:RF8*/,a2)/*:RF4*/){
_min=/*RF8:+*/((int32_t)(R))+(INT32_C(1))/*:RF8*/;
}
else{
_max=R;
}
}
R=_min;
return R;
}/*--*/

/*REVERSE_COLLECTION_SORTER[INTEGER_32]*/T6 r3076lt(T2 a1,T2 a2){
T6 R=0;
R=((T6)(/*RF8:<*/((int32_t)(a2))<(a1)/*:RF8*/));
return R;
}/*--*/

/*REVERSE_COLLECTION_SORTER[INTEGER_32]*/T6 r3076lte(T2 a1,T2 a2){
T6 R=0;
R=((T6)((/*RF4:lt*/r3076lt(a2,a1)/*:RF4*/)==(0)));
return R;
}/*--*/

/*HASHED_DICTIONARY[AGENT_ARGS,STRING]*/T0* r3085common_free_nodes(void){
/*[INTERNAL_C_LOCAL list*/
T0* tmp0;
/*INTERNAL_C_LOCAL list]*/
T0* _fn=(void*)0;
if(fBC1851common_free_nodes==0){fBC1851common_free_nodes=1;{
tmp0/*new*/=/*alloc*/((T0*)(new2616()));
*((T2616*)tmp0/*new*/)=M2616;
_fn=tmp0/*new*/;
/*tmp0.unlock*/
/*reusing tmp0*/tmp0/*new*/=/*alloc*/((T0*)(new2618()));
*((T2618*)tmp0/*new*/)=M2618;
/*RF3:special_common_dictionary*/r2618special_common_dictionary(((T2618*)tmp0/*new*/),_fn);
/*:RF3*/oBC1851common_free_nodes=tmp0/*new*/;
/*tmp0.unlock*/
/*RF3:add*/r2618add(((T2618*)/*ND*/(T0*)(oBC1851common_free_nodes)),_fn,/*RF8:generating_type*/(T0*)(t[2618])/*:RF8*/);
/*:RF3*/}}
return oBC1851common_free_nodes;
}/*--*/

/*HASHED_DICTIONARY[AGENT_ARGS,STRING]*/void r3085make(T3085* C){
/*RF3:create_with_capacity*/r3085create_with_capacity(C,INT32_C(53));
/*:RF3*/}/*--*/

/*HASHED_DICTIONARY[AGENT_ARGS,STRING]*/void r3085put(T3085* C,T0* a1,T0* a2){
/*[INTERNAL_C_LOCAL list*/
T6 tmp0;
/*INTERNAL_C_LOCAL list]*/
T2 _h=0;
T2 _idx=0;
T0* _node=(void*)0;
_h=/*RF4:hash_code*/r3085hash_code(a2)/*:RF4*/;
_idx=/*RF8:#\\*/((int32_t)(_h))%((/*RF2:capacity*/(C)->_capacity/*piiini*//*:RF2*/))/*:RF8*/;
_node=/*RF4:buckets_item*/r3085buckets_item((/*RF2:buckets*/(C)->_buckets/*piiini*//*:RF2*/),_idx)/*:RF4*/;
while(1){
tmp0/*or else*/=((T6)((_node)==((void*)((void*)0))));
if(tmp0/*or else*/){
}
else{
tmp0/*or else*/=((T6)(/*RF4:key_safe_equal*/r3085key_safe_equal((/*RF2:key*/(((T3091*)_node))->_key/*3p*//*:RF2*/),a2)/*:RF4*/));
}
/*until*/if(tmp0/*or else*/) break;
_node=(/*RF2:next*/(((T3091*)_node))->_next/*3p*//*:RF2*/);
}
if((_node)==((void*)((void*)0))){
if(/*RF4:should_increase_capacity*/r3085should_increase_capacity((/*RF2:capacity*/(C)->_capacity/*piiini*//*:RF2*/),(/*RF2:count*/(C)->_count/*piiini*//*:RF2*/))/*:RF4*/){
/*RF3:increase_capacity*/r3085increase_capacity(C);
/*:RF3*/_idx=/*RF8:#\\*/((int32_t)(_h))%((/*RF2:capacity*/(C)->_capacity/*piiini*//*:RF2*/))/*:RF8*/;
}
_node=/*RF4:new_node*/r3085new_node(C,a1,a2,/*RF4:buckets_item*/r3085buckets_item((/*RF2:buckets*/(C)->_buckets/*piiini*//*:RF2*/),_idx)/*:RF4*/)/*:RF4*/;
/*RF7:put*/((/*RF2:buckets*/(C)->_buckets/*piiini*//*:RF2*/))[_idx]=(_node);
/*:RF7*//*SFN*/(C->_count/*piiini*/)=/*RF8:+*/((int32_t)((/*RF2:count*/(C)->_count/*piiini*//*:RF2*/)))+(INT32_C(1))/*:RF8*/;
/*SFN*/(C->_cache_user/*piiini*/)=INT32_C(-1);
}
else{
(/*RF2:item*/(((T3091*)_node))->_item/*3p*//*:RF2*/)=a1;
}
/*RF3:next_generation*/r3085next_generation(C);
/*:RF3*/}/*--*/

/*HASHED_DICTIONARY[AGENT_ARGS,STRING]*/T0* r3085new_node(T3085* C,T0* a1,T0* a2,T0* a3){
/*[INTERNAL_C_LOCAL list*/
T0* tmp0;
/*INTERNAL_C_LOCAL list]*/
T0* R=(void*)0;
R=/*RF8:item*/(((T3093*)((/*RF2:free_nodes*/(C)->_free_nodes/*piiini*//*:RF2*/)))->o)/*:RF8*/;
if((R)==((void*)((void*)0))){
tmp0/*new*/=/*alloc*/((T0*)(new3091()));
*((T3091*)tmp0/*new*/)=M3091;
/*RF3:make*/r3091make(((T3091*)tmp0/*new*/),a1,a2,a3);
/*:RF3*/R=tmp0/*new*/;
/*tmp0.unlock*/
}
else{
/*RF7:set_item*/(((T3093*)((/*RF2:free_nodes*/(C)->_free_nodes/*piiini*//*:RF2*/)))->o)=(T0*)((/*RF2:next*/(((T3091*)R))->_next/*3p*//*:RF2*/));
/*:RF7*//*RF3:make*/r3091make(((T3091*)R),a1,a2,a3);
/*:RF3*/}
return R;
}/*--*/

/*HASHED_DICTIONARY[AGENT_ARGS,STRING]*/T2 r3085prime_capacity(T2 a1){
T2 R=0;
R=/*RF8:#+*/(int32_t)(((uint32_t)(a1))+((uint32_t)(/*RF8:#//*/((int32_t)(a1))/(INT32_C(2))/*:RF8*/)))/*:RF8*/;
if(/*RF8:>=*/((int32_t)(R))>=(INT32_C(0))/*:RF8*/){
R=/*RF4:prime_number_ceiling*/r3085prime_number_ceiling(R)/*:RF4*/;
}
else{
R=/*RF4:prime_number_ceiling*/r3085prime_number_ceiling(INT32_C(2147483647))/*:RF4*/;
}
return R;
}/*--*/

/*HASHED_DICTIONARY[AGENT_ARGS,STRING]*/T0* r3085buckets_item(T3092 a1,T2 a2){
T0* R=(void*)0;
R=/*RF8:item*/(a1)[a2]/*:RF8*/;
return R;
}/*--*/

/*HASHED_DICTIONARY[AGENT_ARGS,STRING]*/T6 r3085should_increase_capacity(T2 a1,T2 a2){
/*[INTERNAL_C_LOCAL list*/
T6 tmp0;
/*INTERNAL_C_LOCAL list]*/
T6 R=0;
tmp0/*and then*/=((T6)(/*RF8:>*/((int32_t)(a2))>(/*RF8:#**/(int32_t)(((uint32_t)(/*RF8:#//*/((int32_t)(a1))/(INT32_C(3))/*:RF8*/))*((uint32_t)(INT32_C(2))))/*:RF8*/)/*:RF8*/));
if(tmp0/*and then*/){
tmp0/*and then*/=((T6)(/*RF8:<*/((int32_t)(a1))<(INT32_C(2147483647))/*:RF8*/));
}
R=((T6)(tmp0/*and then*/));
return R;
}/*--*/

/*HASHED_DICTIONARY[AGENT_ARGS,STRING]*/T6 r3085key_safe_equal(T0* a1,T0* a2){
T6 R=0;
if((a1)==((void*)(a2))){
R=((T6)(1));
}
else{
R=((T6)(/*RF4:is_equal*/r7is_equal(((T7*)a1),a2)/*:RF4*/));
}
return R;
}/*--*/

/*HASHED_DICTIONARY[AGENT_ARGS,STRING]*/T0* r3085reference_at(T3085* C,T0* a1){
/*[INTERNAL_C_LOCAL list*/
T6 tmp0;
/*INTERNAL_C_LOCAL list]*/
T0* R=(void*)0;
T2 _idx=0;
T0* _node=(void*)0;
_idx=/*RF8:#\\*/((int32_t)(/*RF4:hash_code*/r3085hash_code(a1)/*:RF4*/))%((/*RF2:capacity*/(C)->_capacity/*piiini*//*:RF2*/))/*:RF8*/;
_node=/*RF4:buckets_item*/r3085buckets_item((/*RF2:buckets*/(C)->_buckets/*piiini*//*:RF2*/),_idx)/*:RF4*/;
while(1){
tmp0/*or else*/=((T6)((_node)==((void*)((void*)0))));
if(tmp0/*or else*/){
}
else{
tmp0/*or else*/=((T6)(/*RF4:key_safe_equal*/r3085key_safe_equal((/*RF2:key*/(((T3091*)_node))->_key/*3p*//*:RF2*/),a1)/*:RF4*/));
}
/*until*/if(tmp0/*or else*/) break;
_node=(/*RF2:next*/(((T3091*)_node))->_next/*3p*//*:RF2*/);
}
if((_node)!=((void*)((void*)0))){
R=(/*RF2:item*/(((T3091*)_node))->_item/*3p*//*:RF2*/);
}
return R;
}/*--*/

/*HASHED_DICTIONARY[AGENT_ARGS,STRING]*/T2 r3085prime_number_ceiling(T2 a1){
T2 R=0;
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(98317))/*:RF8*/){
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(769))/*:RF8*/){
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(53))/*:RF8*/){
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(11))/*:RF8*/){
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(3))/*:RF8*/){
R=INT32_C(3);
}
else{
R=INT32_C(11);
}
}
else{
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(23))/*:RF8*/){
R=INT32_C(23);
}
else{
R=INT32_C(53);
}
}
}
else{
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(193))/*:RF8*/){
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(97))/*:RF8*/){
R=INT32_C(97);
}
else{
R=INT32_C(193);
}
}
else{
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(389))/*:RF8*/){
R=INT32_C(389);
}
else{
R=INT32_C(769);
}
}
}
}
else{
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(12289))/*:RF8*/){
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(3079))/*:RF8*/){
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(1543))/*:RF8*/){
R=INT32_C(1543);
}
else{
R=INT32_C(3079);
}
}
else{
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(6151))/*:RF8*/){
R=INT32_C(6151);
}
else{
R=INT32_C(12289);
}
}
}
else{
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(24593))/*:RF8*/){
R=INT32_C(24593);
}
else{
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(49157))/*:RF8*/){
R=INT32_C(49157);
}
else{
R=INT32_C(98317);
}
}
}
}
}
else{
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(12582917))/*:RF8*/){
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(1572869))/*:RF8*/){
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(393241))/*:RF8*/){
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(196613))/*:RF8*/){
R=INT32_C(196613);
}
else{
R=INT32_C(393241);
}
}
else{
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(786433))/*:RF8*/){
R=INT32_C(786433);
}
else{
R=INT32_C(1572869);
}
}
}
else{
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(3145739))/*:RF8*/){
R=INT32_C(3145739);
}
else{
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(6291469))/*:RF8*/){
R=INT32_C(6291469);
}
else{
R=INT32_C(12582917);
}
}
}
}
else{
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(201326611))/*:RF8*/){
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(50331653))/*:RF8*/){
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(25165843))/*:RF8*/){
R=INT32_C(25165843);
}
else{
R=INT32_C(50331653);
}
}
else{
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(100663319))/*:RF8*/){
R=INT32_C(100663319);
}
else{
R=INT32_C(201326611);
}
}
}
else{
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(805306457))/*:RF8*/){
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(402653189))/*:RF8*/){
R=INT32_C(402653189);
}
else{
R=INT32_C(805306457);
}
}
else{
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(1610612741))/*:RF8*/){
R=INT32_C(1610612741);
}
else{
R=INT32_C(2147483647);
}
}
}
}
}
return R;
}/*--*/

/*HASHED_DICTIONARY[AGENT_ARGS,STRING]*/void r3085create_with_capacity(T3085* C,T2 a1){
/*[INTERNAL_C_LOCAL list*/
T0* tmp0;
/*INTERNAL_C_LOCAL list]*/
/*SFN*/(C->_free_nodes/*piiini*/)=/*RF4:fast_reference_at*/r2618fast_reference_at(((T2618*)/*ND*/(T0*)(/*RF6:common_free_nodes*/r3085common_free_nodes()/*:RF6*/)),/*RF8:generating_type*/(T0*)(t[3085])/*:RF8*/)/*:RF4*/;
if(((/*RF2:free_nodes*/(C)->_free_nodes/*piiini*//*:RF2*/))==((void*)((void*)0))){
tmp0/*new*/=/*alloc*/((T0*)(new3093()));
*((T3093*)tmp0/*new*/)=M3093;
/*SFN*/(C->_free_nodes/*piiini*/)=tmp0/*new*/;
/*tmp0.unlock*/
/*RF3:add*/r2618add(((T2618*)/*ND*/(T0*)(/*RF6:common_free_nodes*/r3085common_free_nodes()/*:RF6*/)),(/*RF2:free_nodes*/(C)->_free_nodes/*piiini*//*:RF2*/),/*RF8:generating_type*/(T0*)(t[3085])/*:RF8*/);
/*:RF3*/}
/*SFN*/(C->_buckets/*piiini*/)=/*RF8:calloc*/new3092(a1)/*:RF8*/;
/*SFN*/(C->_capacity/*piiini*/)=a1;
/*SFN*/(C->_cache_user/*piiini*/)=INT32_C(-1);
/*SFN*/(C->_count/*piiini*/)=INT32_C(0);
}/*--*/

/*HASHED_DICTIONARY[AGENT_ARGS,STRING]*/void r3085increase_capacity(T3085* C){
T2 _i=0;
T2 _idx=0;
T2 _new_capacity=0;
T3092 _old_buckets=(void*)0;
T0* _node1=(void*)0;
T0* _node2=(void*)0;
_new_capacity=/*RF4:prime_capacity*/r3085prime_capacity(/*RF8:+*/((int32_t)((/*RF2:capacity*/(C)->_capacity/*piiini*//*:RF2*/)))+(INT32_C(1))/*:RF8*/)/*:RF4*/;
_old_buckets=(/*RF2:buckets*/(C)->_buckets/*piiini*//*:RF2*/);
/*SFN*/(C->_buckets/*piiini*/)=/*RF8:calloc*/new3092(_new_capacity)/*:RF8*/;
_i=/*RF8:-*/((int32_t)((/*RF2:capacity*/(C)->_capacity/*piiini*//*:RF2*/)))-(INT32_C(1))/*:RF8*/;
/*SFN*/(C->_capacity/*piiini*/)=_new_capacity;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
_node1=/*RF4:buckets_item*/r3085buckets_item(_old_buckets,_i)/*:RF4*/;
while(1){
/*until*/if((_node1)==((void*)((void*)0))) break;
_node2=(/*RF2:next*/(((T3091*)_node1))->_next/*3p*//*:RF2*/);
_idx=/*RF8:#\\*/((int32_t)(/*RF4:hash_code*/r3085hash_code((/*RF2:key*/(((T3091*)_node1))->_key/*3p*//*:RF2*/))/*:RF4*/))%((/*RF2:capacity*/(C)->_capacity/*piiini*//*:RF2*/))/*:RF8*/;
(/*RF2:next*/(((T3091*)_node1))->_next/*3p*//*:RF2*/)=/*RF4:buckets_item*/r3085buckets_item((/*RF2:buckets*/(C)->_buckets/*piiini*//*:RF2*/),_idx)/*:RF4*/;
/*RF7:put*/((/*RF2:buckets*/(C)->_buckets/*piiini*//*:RF2*/))[_idx]=(_node1);
/*:RF7*/_node1=_node2;
}
_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
/*SFN*/(C->_cache_user/*piiini*/)=INT32_C(-1);
}/*--*/

/*HASHED_DICTIONARY[AGENT_ARGS,STRING]*/void r3085next_generation(T3085* C){
/*SFN*/(C->_generation/*piiini*/)=/*RF8:+*/((int32_t)((/*RF2:generation*/(C)->_generation/*piiini*//*:RF2*/)))+(INT32_C(1))/*:RF8*/;
}/*--*/

/*HASHED_DICTIONARY[AGENT_ARGS,STRING]*/T2 r3085hash_code(T0* a1){
T2 R=0;
R=/*RF4:computed_hash_code*/r7computed_hash_code(((T7*)a1))/*:RF4*/;
return R;
}/*--*/

/*HASHED_DICTIONARY_NODE[AGENT_ARGS,STRING]*/void r3091make(T3091* C,T0* a1,T0* a2,T0* a3){
/*SFN*/(C->_item/*3p*/)=a1;
/*SFN*/(C->_key/*3p*/)=a2;
/*SFN*/(C->_next/*3p*/)=a3;
}/*--*/

/*STACK[EXPRESSION]*/void r3110make(T3110* C){
/*RF3:with_capacity*/r3110with_capacity(C,INT32_C(16));
/*:RF3*/}/*--*/

/*STACK[EXPRESSION]*/void r3110mark_native_arrays(T3110* C){
T2 _i=0;
_i=(/*RF2:upper*/(C)->_upper/*iini*//*:RF2*/);
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
/*RF7:mark_item*/{/*mark_item*/
T0* elt=(/*RF2:storage*/(C)->_storage/*iini*//*:RF2*/)[_i];
if(NULL!=elt)Xgc_mark1896((T0*)(elt));
/*mark_item*/}/*:RF7*/_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
}/*--*/

/*STACK[EXPRESSION]*/void r3110push(T3110* C,T0* a1){
T2 _new_capacity=0;
if(/*RF8:<=*/((int32_t)(/*RF8:+*/((int32_t)((/*RF2:upper*/(C)->_upper/*iini*//*:RF2*/)))+(INT32_C(1))/*:RF8*/))<=(/*RF8:-*/((int32_t)((/*RF2:capacity*/(C)->_capacity/*iini*//*:RF2*/)))-(INT32_C(1))/*:RF8*/)/*:RF8*/){
/*SFN*/(C->_upper/*iini*/)=/*RF8:+*/((int32_t)((/*RF2:upper*/(C)->_upper/*iini*//*:RF2*/)))+(INT32_C(1))/*:RF8*/;
}
else{
if(((/*RF2:capacity*/(C)->_capacity/*iini*//*:RF2*/))==(INT8_C(0))){
/*SFN*/(C->_storage/*iini*/)=/*RF8:calloc*/new2785(INT32_C(2))/*:RF8*/;
/*SFN*/(C->_capacity/*iini*/)=INT32_C(2);
/*SFN*/(C->_upper/*iini*/)=INT32_C(0);
}
else{
_new_capacity=/*RF8:**/((int32_t)((/*RF2:capacity*/(C)->_capacity/*iini*//*:RF2*/)))*(INT32_C(2))/*:RF8*/;
/*SFN*/(C->_storage/*iini*/)=/*RF4:realloc*/r2785realloc((/*RF2:storage*/(C)->_storage/*iini*//*:RF2*/),(/*RF2:capacity*/(C)->_capacity/*iini*//*:RF2*/),_new_capacity)/*:RF4*/;
/*SFN*/(C->_capacity/*iini*/)=_new_capacity;
/*SFN*/(C->_upper/*iini*/)=/*RF8:+*/((int32_t)((/*RF2:upper*/(C)->_upper/*iini*//*:RF2*/)))+(INT32_C(1))/*:RF8*/;
}
}
/*RF7:put*/((/*RF2:storage*/(C)->_storage/*iini*//*:RF2*/))[(/*RF2:upper*/(C)->_upper/*iini*//*:RF2*/)]=(a1);
/*:RF7*//*RF3:next_generation*/r3110next_generation(C);
/*:RF3*/}/*--*/

/*STACK[EXPRESSION]*/void r3110pop(T3110* C){
/*SFN*/(C->_upper/*iini*/)=/*RF8:-*/((int32_t)((/*RF2:upper*/(C)->_upper/*iini*//*:RF2*/)))-(INT32_C(1))/*:RF8*/;
}/*--*/

/*STACK[EXPRESSION]*/T0* r3110top(T3110* C){
T0* R=(void*)0;
R=/*RF8:item*/((/*RF2:storage*/(C)->_storage/*iini*//*:RF2*/))[(/*RF2:upper*/(C)->_upper/*iini*//*:RF2*/)]/*:RF8*/;
return R;
}/*--*/

/*STACK[EXPRESSION]*/void r3110with_capacity(T3110* C,T2 a1){
if(/*RF8:<*/((int32_t)((/*RF2:capacity*/(C)->_capacity/*iini*//*:RF2*/)))<(a1)/*:RF8*/){
/*SFN*/(C->_storage/*iini*/)=/*RF8:calloc*/new2785(a1)/*:RF8*/;
/*SFN*/(C->_capacity/*iini*/)=a1;
}
else{
if(/*RF8:>*/((int32_t)((/*RF2:capacity*/(C)->_capacity/*iini*//*:RF2*/)))>(a1)/*:RF8*/){
/*RF3:clear*/r2785clear((/*RF2:storage*/(C)->_storage/*iini*//*:RF2*/),INT32_C(0),(/*RF2:upper*/(C)->_upper/*iini*//*:RF2*/));
/*:RF3*/}
}
/*SFN*/(C->_upper/*iini*/)=INT32_C(-1);
/*RF3:next_generation*/r3110next_generation(C);
/*:RF3*/}/*--*/

/*STACK[EXPRESSION]*/void r3110next_generation(T3110* C){
/*SFN*/(C->_generation/*iini*/)=/*RF8:+*/((int32_t)((/*RF2:generation*/(C)->_generation/*iini*//*:RF2*/)))+(INT32_C(1))/*:RF8*/;
}/*--*/

/*HASHED_DICTIONARY[TAGGED_INTEGER,INTEGER_32]*/T0* r3111common_free_nodes(void){
/*[INTERNAL_C_LOCAL list*/
T0* tmp0;
/*INTERNAL_C_LOCAL list]*/
T0* _fn=(void*)0;
if(fBC1851common_free_nodes==0){fBC1851common_free_nodes=1;{
tmp0/*new*/=/*alloc*/((T0*)(new2616()));
*((T2616*)tmp0/*new*/)=M2616;
_fn=tmp0/*new*/;
/*tmp0.unlock*/
/*reusing tmp0*/tmp0/*new*/=/*alloc*/((T0*)(new2618()));
*((T2618*)tmp0/*new*/)=M2618;
/*RF3:special_common_dictionary*/r2618special_common_dictionary(((T2618*)tmp0/*new*/),_fn);
/*:RF3*/oBC1851common_free_nodes=tmp0/*new*/;
/*tmp0.unlock*/
/*RF3:add*/r2618add(((T2618*)/*ND*/(T0*)(oBC1851common_free_nodes)),_fn,/*RF8:generating_type*/(T0*)(t[2618])/*:RF8*/);
/*:RF3*/}}
return oBC1851common_free_nodes;
}/*--*/

/*HASHED_DICTIONARY[TAGGED_INTEGER,INTEGER_32]*/void r3111make(T3111* C){
/*RF3:create_with_capacity*/r3111create_with_capacity(C,INT32_C(53));
/*:RF3*/}/*--*/

/*HASHED_DICTIONARY[TAGGED_INTEGER,INTEGER_32]*/T0* r3111new_node(T3111* C,T0* a1,T2 a2,T0* a3){
/*[INTERNAL_C_LOCAL list*/
T0* tmp0;
/*INTERNAL_C_LOCAL list]*/
T0* R=(void*)0;
R=/*RF8:item*/(((T3117*)((/*RF2:free_nodes*/(C)->_free_nodes/*piiini*//*:RF2*/)))->o)/*:RF8*/;
if((R)==((void*)((void*)0))){
tmp0/*new*/=/*alloc*/((T0*)(new3116()));
*((T3116*)tmp0/*new*/)=M3116;
/*RF3:make*/r3116make(((T3116*)tmp0/*new*/),a1,a2,a3);
/*:RF3*/R=tmp0/*new*/;
/*tmp0.unlock*/
}
else{
/*RF7:set_item*/(((T3117*)((/*RF2:free_nodes*/(C)->_free_nodes/*piiini*//*:RF2*/)))->o)=(T0*)((/*RF2:next*/(((T3116*)R))->_next/*pip*//*:RF2*/));
/*:RF7*//*RF3:make*/r3116make(((T3116*)R),a1,a2,a3);
/*:RF3*/}
return R;
}/*--*/

/*HASHED_DICTIONARY[TAGGED_INTEGER,INTEGER_32]*/void r3111add(T3111* C,T0* a1,T2 a2){
T2 _idx=0;
T0* _node=(void*)0;
/*SFN*/(C->_cache_user/*piiini*/)=INT32_C(-1);
if(/*RF4:should_increase_capacity*/r3111should_increase_capacity((/*RF2:capacity*/(C)->_capacity/*piiini*//*:RF2*/),(/*RF2:count*/(C)->_count/*piiini*//*:RF2*/))/*:RF4*/){
/*RF3:increase_capacity*/r3111increase_capacity(C);
/*:RF3*/}
_idx=/*RF8:#\\*/((int32_t)(/*RF4:hash_code*/r3111hash_code(a2)/*:RF4*/))%((/*RF2:capacity*/(C)->_capacity/*piiini*//*:RF2*/))/*:RF8*/;
_node=/*RF4:new_node*/r3111new_node(C,a1,a2,/*RF4:buckets_item*/r3111buckets_item((/*RF2:buckets*/(C)->_buckets/*piiini*//*:RF2*/),_idx)/*:RF4*/)/*:RF4*/;
/*RF7:put*/((/*RF2:buckets*/(C)->_buckets/*piiini*//*:RF2*/))[_idx]=(_node);
/*:RF7*//*SFN*/(C->_count/*piiini*/)=/*RF8:+*/((int32_t)((/*RF2:count*/(C)->_count/*piiini*//*:RF2*/)))+(INT32_C(1))/*:RF8*/;
/*RF3:next_generation*/r3111next_generation(C);
/*:RF3*/}/*--*/

/*HASHED_DICTIONARY[TAGGED_INTEGER,INTEGER_32]*/T2 r3111prime_capacity(T2 a1){
T2 R=0;
R=/*RF8:#+*/(int32_t)(((uint32_t)(a1))+((uint32_t)(/*RF8:#//*/((int32_t)(a1))/(INT32_C(2))/*:RF8*/)))/*:RF8*/;
if(/*RF8:>=*/((int32_t)(R))>=(INT32_C(0))/*:RF8*/){
R=/*RF4:prime_number_ceiling*/r3111prime_number_ceiling(R)/*:RF4*/;
}
else{
R=/*RF4:prime_number_ceiling*/r3111prime_number_ceiling(INT32_C(2147483647))/*:RF4*/;
}
return R;
}/*--*/

/*HASHED_DICTIONARY[TAGGED_INTEGER,INTEGER_32]*/T0* r3111buckets_item(T3115 a1,T2 a2){
T0* R=(void*)0;
R=/*RF8:item*/(a1)[a2]/*:RF8*/;
return R;
}/*--*/

/*HASHED_DICTIONARY[TAGGED_INTEGER,INTEGER_32]*/T6 r3111should_increase_capacity(T2 a1,T2 a2){
/*[INTERNAL_C_LOCAL list*/
T6 tmp0;
/*INTERNAL_C_LOCAL list]*/
T6 R=0;
tmp0/*and then*/=((T6)(/*RF8:>*/((int32_t)(a2))>(/*RF8:#**/(int32_t)(((uint32_t)(/*RF8:#//*/((int32_t)(a1))/(INT32_C(3))/*:RF8*/))*((uint32_t)(INT32_C(2))))/*:RF8*/)/*:RF8*/));
if(tmp0/*and then*/){
tmp0/*and then*/=((T6)(/*RF8:<*/((int32_t)(a1))<(INT32_C(2147483647))/*:RF8*/));
}
R=((T6)(tmp0/*and then*/));
return R;
}/*--*/

/*HASHED_DICTIONARY[TAGGED_INTEGER,INTEGER_32]*/T2 r3111prime_number_ceiling(T2 a1){
T2 R=0;
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(98317))/*:RF8*/){
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(769))/*:RF8*/){
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(53))/*:RF8*/){
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(11))/*:RF8*/){
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(3))/*:RF8*/){
R=INT32_C(3);
}
else{
R=INT32_C(11);
}
}
else{
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(23))/*:RF8*/){
R=INT32_C(23);
}
else{
R=INT32_C(53);
}
}
}
else{
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(193))/*:RF8*/){
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(97))/*:RF8*/){
R=INT32_C(97);
}
else{
R=INT32_C(193);
}
}
else{
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(389))/*:RF8*/){
R=INT32_C(389);
}
else{
R=INT32_C(769);
}
}
}
}
else{
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(12289))/*:RF8*/){
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(3079))/*:RF8*/){
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(1543))/*:RF8*/){
R=INT32_C(1543);
}
else{
R=INT32_C(3079);
}
}
else{
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(6151))/*:RF8*/){
R=INT32_C(6151);
}
else{
R=INT32_C(12289);
}
}
}
else{
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(24593))/*:RF8*/){
R=INT32_C(24593);
}
else{
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(49157))/*:RF8*/){
R=INT32_C(49157);
}
else{
R=INT32_C(98317);
}
}
}
}
}
else{
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(12582917))/*:RF8*/){
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(1572869))/*:RF8*/){
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(393241))/*:RF8*/){
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(196613))/*:RF8*/){
R=INT32_C(196613);
}
else{
R=INT32_C(393241);
}
}
else{
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(786433))/*:RF8*/){
R=INT32_C(786433);
}
else{
R=INT32_C(1572869);
}
}
}
else{
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(3145739))/*:RF8*/){
R=INT32_C(3145739);
}
else{
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(6291469))/*:RF8*/){
R=INT32_C(6291469);
}
else{
R=INT32_C(12582917);
}
}
}
}
else{
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(201326611))/*:RF8*/){
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(50331653))/*:RF8*/){
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(25165843))/*:RF8*/){
R=INT32_C(25165843);
}
else{
R=INT32_C(50331653);
}
}
else{
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(100663319))/*:RF8*/){
R=INT32_C(100663319);
}
else{
R=INT32_C(201326611);
}
}
}
else{
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(805306457))/*:RF8*/){
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(402653189))/*:RF8*/){
R=INT32_C(402653189);
}
else{
R=INT32_C(805306457);
}
}
else{
if(/*RF8:<=*/((int32_t)(a1))<=(INT32_C(1610612741))/*:RF8*/){
R=INT32_C(1610612741);
}
else{
R=INT32_C(2147483647);
}
}
}
}
}
return R;
}/*--*/

/*HASHED_DICTIONARY[TAGGED_INTEGER,INTEGER_32]*/void r3111create_with_capacity(T3111* C,T2 a1){
/*[INTERNAL_C_LOCAL list*/
T0* tmp0;
/*INTERNAL_C_LOCAL list]*/
/*SFN*/(C->_free_nodes/*piiini*/)=/*RF4:fast_reference_at*/r2618fast_reference_at(((T2618*)/*ND*/(T0*)(/*RF6:common_free_nodes*/r3111common_free_nodes()/*:RF6*/)),/*RF8:generating_type*/(T0*)(t[3111])/*:RF8*/)/*:RF4*/;
if(((/*RF2:free_nodes*/(C)->_free_nodes/*piiini*//*:RF2*/))==((void*)((void*)0))){
tmp0/*new*/=/*alloc*/((T0*)(new3117()));
*((T3117*)tmp0/*new*/)=M3117;
/*SFN*/(C->_free_nodes/*piiini*/)=tmp0/*new*/;
/*tmp0.unlock*/
/*RF3:add*/r2618add(((T2618*)/*ND*/(T0*)(/*RF6:common_free_nodes*/r3111common_free_nodes()/*:RF6*/)),(/*RF2:free_nodes*/(C)->_free_nodes/*piiini*//*:RF2*/),/*RF8:generating_type*/(T0*)(t[3111])/*:RF8*/);
/*:RF3*/}
/*SFN*/(C->_buckets/*piiini*/)=/*RF8:calloc*/new3115(a1)/*:RF8*/;
/*SFN*/(C->_capacity/*piiini*/)=a1;
/*SFN*/(C->_cache_user/*piiini*/)=INT32_C(-1);
/*SFN*/(C->_count/*piiini*/)=INT32_C(0);
}/*--*/

/*HASHED_DICTIONARY[TAGGED_INTEGER,INTEGER_32]*/void r3111increase_capacity(T3111* C){
T2 _i=0;
T2 _idx=0;
T2 _new_capacity=0;
T3115 _old_buckets=(void*)0;
T0* _node1=(void*)0;
T0* _node2=(void*)0;
_new_capacity=/*RF4:prime_capacity*/r3111prime_capacity(/*RF8:+*/((int32_t)((/*RF2:capacity*/(C)->_capacity/*piiini*//*:RF2*/)))+(INT32_C(1))/*:RF8*/)/*:RF4*/;
_old_buckets=(/*RF2:buckets*/(C)->_buckets/*piiini*//*:RF2*/);
/*SFN*/(C->_buckets/*piiini*/)=/*RF8:calloc*/new3115(_new_capacity)/*:RF8*/;
_i=/*RF8:-*/((int32_t)((/*RF2:capacity*/(C)->_capacity/*piiini*//*:RF2*/)))-(INT32_C(1))/*:RF8*/;
/*SFN*/(C->_capacity/*piiini*/)=_new_capacity;
while(1){
/*until*/if(/*RF8:<*/((int32_t)(_i))<(INT32_C(0))/*:RF8*/) break;
_node1=/*RF4:buckets_item*/r3111buckets_item(_old_buckets,_i)/*:RF4*/;
while(1){
/*until*/if((_node1)==((void*)((void*)0))) break;
_node2=(/*RF2:next*/(((T3116*)_node1))->_next/*pip*//*:RF2*/);
_idx=/*RF8:#\\*/((int32_t)(/*RF4:hash_code*/r3111hash_code((/*RF2:key*/(((T3116*)_node1))->_key/*pip*//*:RF2*/))/*:RF4*/))%((/*RF2:capacity*/(C)->_capacity/*piiini*//*:RF2*/))/*:RF8*/;
(/*RF2:next*/(((T3116*)_node1))->_next/*pip*//*:RF2*/)=/*RF4:buckets_item*/r3111buckets_item((/*RF2:buckets*/(C)->_buckets/*piiini*//*:RF2*/),_idx)/*:RF4*/;
/*RF7:put*/((/*RF2:buckets*/(C)->_buckets/*piiini*//*:RF2*/))[_idx]=(_node1);
/*:RF7*/_node1=_node2;
}
_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
}
/*SFN*/(C->_cache_user/*piiini*/)=INT32_C(-1);
}/*--*/

/*HASHED_DICTIONARY[TAGGED_INTEGER,INTEGER_32]*/void r3111next_generation(T3111* C){
/*SFN*/(C->_generation/*piiini*/)=/*RF8:+*/((int32_t)((/*RF2:generation*/(C)->_generation/*piiini*//*:RF2*/)))+(INT32_C(1))/*:RF8*/;
}/*--*/

/*HASHED_DICTIONARY[TAGGED_INTEGER,INTEGER_32]*/T2 r3111hash_code(T2 a1){
T2 R=0;
R=/*RF8:&*/(a1&/*0x7FFFFFFF*/INT32_C(2147483647))/*:RF8*/;
return R;
}/*--*/

/*HASHED_DICTIONARY[TAGGED_INTEGER,INTEGER_32]*/T0* r3111fast_reference_at(T3111* C,T2 a1){
/*[INTERNAL_C_LOCAL list*/
T6 tmp0;
/*INTERNAL_C_LOCAL list]*/
T0* R=(void*)0;
T2 _idx=0;
T0* _node=(void*)0;
_idx=/*RF8:#\\*/((int32_t)(/*RF4:hash_code*/r3111hash_code(a1)/*:RF4*/))%((/*RF2:capacity*/(C)->_capacity/*piiini*//*:RF2*/))/*:RF8*/;
_node=/*RF4:buckets_item*/r3111buckets_item((/*RF2:buckets*/(C)->_buckets/*piiini*//*:RF2*/),_idx)/*:RF4*/;
while(1){
tmp0/*or else*/=((T6)((_node)==((void*)((void*)0))));
if(tmp0/*or else*/){
}
else{
tmp0/*or else*/=((T6)(((/*RF2:key*/(((T3116*)_node))->_key/*pip*//*:RF2*/))==(a1)));
}
/*until*/if(tmp0/*or else*/) break;
_node=(/*RF2:next*/(((T3116*)_node))->_next/*pip*//*:RF2*/);
}
if((_node)!=((void*)((void*)0))){
R=(/*RF2:item*/(((T3116*)_node))->_item/*pip*//*:RF2*/);
}
return R;
}/*--*/

/*SAFE_EQUAL[INTEGER_32]*/T6 r3113test(T2 a1,T2 a2){
T6 R=0;
T2 _e_type=0;
if((a1)==(a2)){
R=((T6)(1));
}
return R;
}/*--*/

/*HASHED_DICTIONARY_NODE[TAGGED_INTEGER,INTEGER_32]*/void r3116make(T3116* C,T0* a1,T2 a2,T0* a3){
/*SFN*/(C->_item/*pip*/)=a1;
/*SFN*/(C->_key/*pip*/)=a2;
/*SFN*/(C->_next/*pip*/)=a3;
}/*--*/

/*COMPILE_TO_C*/T6 r1580is_version_flag(T1580* C,T0* a1){
/*[INTERNAL_C_LOCAL list*/
T2 tmp0;
/*INTERNAL_C_LOCAL list]*/
T6 R=0;
R=((T6)(/*RF4:is_version_flag_no_exit*/r1580is_version_flag_no_exit(C,a1)/*:RF4*/));
if(R){
tmp0/*inspectExpression*/=/*RF4:argument_count*/r1580argument_count()/*:RF4*/;
/*[inspect*/
switch(tmp0/*inspectExpression*/){
case 1:
/*RF7:die_with_code*/se_die(INT32_C(0));
/*:RF7*/break;
case 2:
if((/*RF2:help_flag*/(C)->_help_flag/*ppp*//*:RF2*/)){
/*RF7:die_with_code*/se_die(INT32_C(0));
/*:RF7*/}
break;
}
/*inspect]*/
}
return R;
}/*--*/
T0*oBC1583eiffel_parser=(void*)0;
int fBC1583eiffel_parser=0;

/*COMPILE_TO_C*/T0* r1580eiffel_parser(void){
/*[INTERNAL_C_LOCAL list*/
T0* tmp0;
/*INTERNAL_C_LOCAL list]*/
if(fBC1583eiffel_parser==0){fBC1583eiffel_parser=1;{
tmp0/*new*/=/*alloc*/((T0*)(new1652()));
*((T1652*)tmp0/*new*/)=M1652;
/*RF3:make*/r1652make(((T1652*)tmp0/*new*/));
/*:RF3*/oBC1583eiffel_parser=tmp0/*new*/;
/*tmp0.unlock*/
}}
return oBC1583eiffel_parser;
}/*--*/

/*COMPILE_TO_C*/T6 r1580is_style_warning_flag(T0* a1){
T6 R=0;
if(/*RF4:flag_match*/r1580flag_match(ms1586_822199910Abc1586A,a1)/*:RF4*/){
R=((T6)(1));
(/*RF2:style_warning*/(((T1837*)oBC1583error_handler))->_style_warning/*pppii*//*:RF2*/)=((T6)(1));
}
return R;
}/*--*/

/*COMPILE_TO_C*/T6 r1580is_output_error_warning_on_flag(T1580* C,T0* a1,T2 a2){
T6 R=0;
if(/*RF4:flag_match*/r1580flag_match(ms1581_941571923Abc1581A,a1)/*:RF4*/){
R=((T6)(1));
if(/*RF8:>=*/((int32_t)(a2))>=(/*RF4:argument_count*/r1580argument_count()/*:RF4*/)/*:RF8*/){
/*RF3:w_put_string*/r1674w_put_string((T1674*)(/*RF6:echo*/r1580echo()/*:RF6*/),ms1580_1889925553Abc1580A);
/*:RF3*//*RF3:w_put_string*/r1674w_put_string((T1674*)(/*RF6:echo*/r1580echo()/*:RF6*/),se_ms(62,s1581_1202957293A));
/*:RF3*//*RF7:die_with_code*/se_die(INT32_C(1));
/*:RF7*/}
}
return R;
}/*--*/

/*COMPILE_TO_C*/T6 r1580is_version_flag_no_exit(T1580* C,T0* a1){
/*[INTERNAL_C_LOCAL list*/
T6 tmp0;
/*INTERNAL_C_LOCAL list]*/
T6 R=0;
tmp0/*or else*/=((T6)(/*RF4:flag_match*/r1580flag_match(ms1586_2248290Abc1586A,a1)/*:RF4*/));
if(tmp0/*or else*/){
}
else{
tmp0/*or else*/=((T6)(/*RF4:flag_match*/r1580flag_match(ms1581_118Abc1581A,a1)/*:RF4*/));
}
if(tmp0/*or else*/){
if(((/*RF2:version_flag*/(C)->_version_flag/*ppp*//*:RF2*/))==(0)){
/*RF3:print_version*/r1659print_version(((T1659*)oBC1583smart_eiffel));
/*:RF3*//*SFN*/(C->_version_flag/*ppp*/)=((T6)(1));
}
R=((T6)(1));
}
return R;
}/*--*/

/*COMPILE_TO_C*/T6 r1580is_relax_flag(T0* a1){
T6 R=0;
if(/*RF4:flag_match*/r1580flag_match(ms1586_87180Abc1586A,a1)/*:RF4*/){
R=((T6)(1));
(/*RF2:relax*/(((T1827*)oBC1583ace))->_relax/*p2pipippppppppp3ppiiiippcpii*//*:RF2*/)=((T6)(1));
}
return R;
}/*--*/

/*COMPILE_TO_C*/T6 r1580is_flat_check_flag(T0* a1){
T6 R=0;
if(/*RF4:flag_match*/r1580flag_match(ms1585_251171752Abc1585A,a1)/*:RF4*/){
R=((T6)(1));
(/*RF2:flat_check*/(((T1827*)oBC1583ace))->_flat_check/*p2pipippppppppp3ppiiiippcpii*//*:RF2*/)=((T6)(1));
}
return R;
}/*--*/
T0*oBC1583smart_eiffel=(void*)0;
T0*oBC1583system_tools=(void*)0;
int fBC1583system_tools=0;

/*COMPILE_TO_C*/T0* r1580system_tools(void){
/*[INTERNAL_C_LOCAL list*/
T0* tmp0;
/*INTERNAL_C_LOCAL list]*/
if(fBC1583system_tools==0){fBC1583system_tools=1;{
tmp0/*new*/=/*alloc*/((T0*)(new1661()));
*((T1661*)tmp0/*new*/)=M1661;
/*RF3:make*/r1661make(((T1661*)tmp0/*new*/));
/*:RF3*/oBC1583system_tools=tmp0/*new*/;
/*tmp0.unlock*/
}}
return oBC1583system_tools;
}/*--*/

/*COMPILE_TO_C*/T6 r1580is_cecil_flag(T1580* C,T0* a1,T2 a2){
T6 R=0;
if(/*RF4:flag_match*/r1580flag_match(ms1586_77608Abc1586A,a1)/*:RF4*/){
R=((T6)(1));
if(/*RF8:<*/((int32_t)(a2))<(/*RF4:argument_count*/r1580argument_count()/*:RF4*/)/*:RF8*/){
/*RF3:add_cecil_file*/r1636add_cecil_file((T1636*)((/*RF2:item*/(((T2574*)oBC1583cecil_pool_memory))->_item/*p*//*:RF2*/)),/*RF8:item*/((/*RF2:storage*/((T2573*)(/*RF6:command_arguments*/r1580command_arguments()/*:RF6*/))->_storage/*Tiini*//*:RF2*/))[/*RF8:+*/((int32_t)(a2))+(INT32_C(1))/*:RF8*/]/*:RF8*/);
/*:RF3*/}
else{
/*RF3:w_put_string*/r1674w_put_string((T1674*)(/*RF6:echo*/r1580echo()/*:RF6*/),ms1580_1889925553Abc1580A);
/*:RF3*//*RF3:w_put_string*/r1674w_put_string((T1674*)(/*RF6:echo*/r1580echo()/*:RF6*/),se_ms(39,s1581_1335263213A));
/*:RF3*//*RF7:die_with_code*/se_die(INT32_C(1));
/*:RF7*/}
}
return R;
}/*--*/
T0*oBC1582command_arguments=(void*)0;
int fBC1582command_arguments=0;

/*COMPILE_TO_C*/T0* r1580command_arguments(void){
/*[INTERNAL_C_LOCAL list*/
T0* tmp0;
/*INTERNAL_C_LOCAL list]*/
T2 _i=0;
T0* _arg=(void*)0;
if(fBC1582command_arguments==0){fBC1582command_arguments=1;{
_i=/*RF8:se_argc*/se_argc/*:RF8*/;
tmp0/*new*/=/*alloc*/((T0*)(new2573()));
*((T2573*)tmp0/*new*/)=M2573;
/*RF3:make*/r2573make(((T2573*)tmp0/*new*/),_i);
/*:RF3*/oBC1582command_arguments=tmp0/*new*/;
/*tmp0.unlock*/
while(1){
/*until*/if((_i)==(INT8_C(0))) break;
_i=/*RF8:-*/((int32_t)(_i))-(INT32_C(1))/*:RF8*/;
_arg=/*RF8:se_argv*/((T0*)se_string(se_argv[_i]))/*:RF8*/;
/*RF3:put*/r2573put(((T2573*)oBC1582command_arguments),_arg,_i);
/*:RF3*/}
}}
return oBC1582command_arguments;
}/*--*/

/*COMPILE_TO_C*/T6 r1580ace_file_mode(T1580* C){
/*[INTERNAL_C_LOCAL list*/
T6 tmp0;
T6 tmp1;
/*INTERNAL_C_LOCAL list]*/
T6 R=0;
T2 _i=0;
T0* _arg=(void*)0;
tmp0/*ifthen (empty)*/=((T6)((/*RF6:system_tools*/r1580system_tools()/*:RF6*/)!=((void*)((void*)0))));
_i=INT32_C(1);
while(1){
/*auto-unlock tmp0*/tmp0/*or else*/=((T6)(R));
if(tmp0/*or else*/){
}
else{
tmp0/*or else*/=((T6)(/*RF8:>*/((int32_t)(_i))>(/*RF4:argument_count*/r1580argument_count()/*:RF4*/)/*:RF8*/));
}
/*until*/if(tmp0/*or else*/) break;
_arg=/*RF8:item*/((/*RF2:storage*/((T2573*)(/*RF6:command_arguments*/r1580command_arguments()/*:RF6*/))->_storage/*Tiini*//*:RF2*/))[_i]/*:RF8*/;
tmp1/*or else*/=((T6)(/*RF4:has_suffix*/r7has_suffix(((T7*)_arg),ms1581_8771Abc1581A)/*:RF4*/));
if(tmp1/*or else*/){
}
else{
tmp1/*or else*/=((T6)(/*RF4:has_suffix*/r7has_suffix(((T7*)_arg),ms1581_7779Abc1581A)/*:RF4*/));
}
if(tmp1/*or else*/){
R=((T6)(1));
/*RF3:analyse_ace_file*/r1827analyse_ace_file(((T1827*)oBC1583ace),_arg);
/*:RF3*/}
_i=/*RF8:+*/((int32_t)(_i))+(INT32_C(1))/*:RF8*/;
}
if(R){
_i=INT32_C(1);
while(1){
/*until*/if(/*RF8:>*/((int32_t)(_i))>(/*RF4:argument_count*/r1580argument_count()/*:RF4*/)/*:RF8*/) break;
_arg=/*RF8:item*/((/*RF2:storage*/((T2573*)(/*RF6:command_arguments*/r1580command_arguments()/*:RF6*/))->_storage/*Tiini*//*:RF2*/))[_i]/*:RF8*/;
if(/*RF4:is_equal*/r7is_equal(((T7*)_arg),(/*RF2:file_path*/(((T1827*)oBC1583ace))->_file_path/*p2pipippppppppp3ppiiiippcpii*//*:RF2*/))/*:RF4*/){
}
else{
if(/*RF4:is_valid_argument_for_ace_mode*/r1580is_valid_argument_for_ace_mode(C,_arg)/*:RF4*/){
}
else{
/*RF3:w_put_string*/r1674w_put_string((T1674*)(/*RF6:echo*/r1580echo()/*:RF6*/),se_ms(18,s1581_613587359A));
/*:RF3*//*RF3:w_put_string*/r1674w_put_string((T1674*)(/*RF6:echo*/r1580echo()/*:RF6*/),_arg);
/*:RF3*//*RF3:w_put_string*/r1674w_put_string((T1674*)(/*RF6:echo*/r1580echo()/*:RF6*/),se_ms(35,s1581_1102047298A));
/*:RF3*//*RF3:w_put_string*/r1674w_put_string((T1674*)(/*RF6:echo*/r1580echo()/*:RF6*/),(/*RF2:file_path*/(((T1827*)oBC1583ace))->_file_path/*p2pipippppppppp3ppiiiippcpii*//*:RF2*/));
/*:RF3*//*RF3:w_put_string*/r1674w_put_string((T1674*)(/*RF6:echo*/r1580echo()/*:RF6*/),se_ms(11,s1581_513843490A));
/*:RF3*//*RF3:w_put_string*/r1674w_put_string((T1674*)(/*RF6:echo*/r1580echo()/*:RF6*/),ms1580_1525604536Abc1580A);
/*:RF3*//*RF3:bad_use_exit*/r1661bad_use_exit((T1661*)(/*RF6:system_tools*/r1580system_tools()/*:RF6*/),ms1580_1889925553Abc1580A,ms1580_1464431905Abc1580A);
/*:RF3*/}
}
_i=/*RF8:+*/((int32_t)(_i))+(INT32_C(1))/*:RF8*/;
}
}
return R;
}/*--*/

/*COMPILE_TO_C*/T2 r1580argument_count(void){
T2 R=0;
R=(/*RF2:upper*/((T2573*)(/*RF6:command_arguments*/r1580command_arguments()/*:RF6*/))->_upper/*Tiini*//*:RF2*/);
return R;
}/*--*/
T0*oBC1583cpp=(void*)0;
int fBC1583cpp=0;

/*COMPILE_TO_C*/T0* r1580cpp(void){
/*[INTERNAL_C_LOCAL list*/
T0* tmp0;
/*INTERNAL_C_LOCAL list]*/
if(fBC1583cpp==0){fBC1583cpp=1;{
tmp0/*new*/=/*alloc*/((T0*)(new1665()));
*((T1665*)tmp0/*new*/)=M1665;
/*RF3:make*/r1665make(((T1665*)tmp0/*new*/));
/*:RF3*/oBC1583cpp=tmp0/*new*/;
/*tmp0.unlock*/
}}
return oBC1583cpp;
}/*--*/

/*COMPILE_TO_C*/T6 r1580flag_match(T0* a1,T0* a2){
/*[INTERNAL_C_LOCAL list*/
T3 tmp0;
T6 tmp1;
T6 tmp2;
T6 tmp3;
/*INTERNAL_C_LOCAL list]*/
T6 R=0;
T2 _i_flag=0;
T2 _i_arg=0;
T3 _flag_char='\0';
T3 _arg_char='\0';
_i_arg=(/*RF2:count*/(((T7*)a2))->_count/*Tiiiini*//*:RF2*/);
if(/*RF8:>=*/((int32_t)(_i_arg))>=(INT32_C(2))/*:RF8*/){
_i_flag=(/*RF2:count*/(((T7*)a1))->_count/*Tiiiini*//*:RF2*/);
tmp0/*inspectExpression*/=/*RF4:first*/r7first(((T7*)a2))/*:RF4*/;
/*[inspect*/
switch(tmp0/*inspectExpression*/){
case 45:
if((/*RF4:item*/r7item(((T7*)a2),INT32_C(2))/*:RF4*/)==(((T3)'\055'))){
R=((T6)((/*RF8:+*/((int32_t)(_i_flag))+(INT32_C(2))/*:RF8*/)==(_i_arg)));
}
else{
R=((T6)((/*RF8:+*/((int32_t)(_i_flag))+(INT32_C(1))/*:RF8*/)==(_i_arg)));
}
break;
case 47:
R=((T6)((/*RF8:+*/((int32_t)(_i_flag))+(INT32_C(1))/*:RF8*/)==(_i_arg)));
break;
}
/*inspect]*/
while(1){
tmp1/*or else*/=((T6)((R)==(0)));
if(tmp1/*or else*/){
}
else{
tmp1/*or else*/=((T6)((_i_flag)==(INT8_C(0))));
}
/*until*/if(tmp1/*or else*/) break;
_flag_char=/*RF4:item*/r7item(((T7*)a1),_i_flag)/*:RF4*/;
_arg_char=/*RF4:item*/r7item(((T7*)a2),_i_arg)/*:RF4*/;
tmp2/*or else*/=((T6)(/*RF4:same_as*/r3same_as(_flag_char,_arg_char)/*:RF4*/));
if(tmp2/*or else*/){
}
else{
tmp3/*and then*/=((T6)((_flag_char)==(((T3)'\137'))));
if(tmp3/*and then*/){
tmp3/*and then*/=((T6)((_arg_char)==(((T3)'\055'))));
}
tmp2/*or else*/=((T6)(tmp3/*and then*/));
}
if(tmp2/*or else*/){
_i_arg=/*RF8:-*/((int32_t)(_i_arg))-(INT32_C(1))/*:RF8*/;
_i_flag=/*RF8:-*/((int32_t)(_i_flag))-(INT32_C(1))/*:RF8*/;
}
else{
R=((T6)(0));
}
}
}
return R;
}/*--*/
T0*oBC1583cecil_pool_memory=(void*)0;

/*COMPILE_TO_C*/T6 r1580valid_arg_index(T2 a1){
T6 R=0;
R=((T6)(/*RF4:in_range*/r2in_range(a1,INT32_C(1),/*RF4:argument_count*/r1580argument_count()/*:RF4*/)/*:RF4*/));
return R;
}/*--*/

/*COMPILE_TO_C*/T6 r1580is_trace_flag(T0* a1){
T6 R=0;
if(/*RF4:flag_match*/r1580flag_match(ms1586_17498Abc1586A,a1)/*:RF4*/){
R=((T6)(1));
}
if(/*RF4:flag_match*/r1580flag_match(ms1585_89771Abc1585A,a1)/*:RF4*/){
/*RF3:w_put_string*/r1674w_put_string((T1674*)(/*RF6:echo*/r1580echo()/*:RF6*/),ms1580_1889925553Abc1580A);
/*:RF3*//*RF3:w_put_string*/r1674w_put_string((T1674*)(/*RF6:echo*/r1580echo()/*:RF6*/),ms1581_579450289Abc1581A);
/*:RF3*/R=((T6)(1));
}
if(R){
/*RF3:set_default_trace*/r1827set_default_trace(((T1827*)oBC1583ace));
/*:RF3*/}
return R;
}/*--*/

/*COMPILE_TO_C*/T6 r1580is_o_flag(T1580* C,T0* a1,T2 a2){
T6 R=0;
T0* _executable_name=(void*)0;
if(/*RF4:is_equal*/r7is_equal(((T7*)ms1586_336Abc1586A),a1)/*:RF4*/){
R=((T6)(1));
if(/*RF8:<*/((int32_t)(a2))<(/*RF4:argument_count*/r1580argument_count()/*:RF4*/)/*:RF8*/){
_executable_name=/*RF8:item*/((/*RF2:storage*/((T2573*)(/*RF6:command_arguments*/r1580command_arguments()/*:RF6*/))->_storage/*Tiini*//*:RF2*/))[/*RF8:+*/((int32_t)(a2))+(INT32_C(1))/*:RF8*/]/*:RF8*/;
if(/*RF4:has_suffix*/r7has_suffix(((T7*)_executable_name),ms1583_331Abc1583A)/*:RF4*/){
/*RF3:w_put_string*/r1674w_put_string((T1674*)(/*RF6:echo*/r1580echo()/*:RF6*/),se_ms(22,s1581_1812938425A));
/*:RF3*//*RF3:w_put_string*/r1674w_put_string((T1674*)(/*RF6:echo*/r1580echo()/*:RF6*/),_executable_name);
/*:RF3*//*RF3:w_put_string*/r1674w_put_string((T1674*)(/*RF6:echo*/r1580echo()/*:RF6*/),se_ms(77,s1581_1009954795A));
/*:RF3*//*RF7:die_with_code*/se_die(INT32_C(1));
/*:RF7*/}
(/*RF2:executable_name*/(((T1827*)oBC1583ace))->_executable_name/*p2pipippppppppp3ppiiiippcpii*//*:RF2*/)=_executable_name;
}
else{
/*RF3:w_put_string*/r1674w_put_string((T1674*)(/*RF6:echo*/r1580echo()/*:RF6*/),ms1580_1889925553Abc1580A);
/*:RF3*//*RF3:w_put_string*/r1674w_put_string((T1674*)(/*RF6:echo*/r1580echo()/*:RF6*/),se_ms(37,s1581_1724187394A));
/*:RF3*//*RF7:die_with_code*/se_die(INT32_C(1));
/*:RF7*/}
}
return R;
}/*--*/

/*COMPILE_TO_C*/void r1580make(T1580* C){
int _string_command_line=0;
T0* _echo_redirect=(void*)0;
/*RF5:set_cecil_pool*/r1580set_cecil_pool();
/*:RF5*/(/*RF2:plugin_factory*/((T1661*)(/*RF6:system_tools*/r1580system_tools()/*:RF6*/))->_plugin_factory/*5pp10pipppp2pp7p*//*:RF2*/)=((T0*)create2544());
(/*RF2:drop_comments*/((T1652*)(/*RF6:eiffel_parser*/r1580eiffel_parser()/*:RF6*/))->_drop_comments/*pii10pp3ppppp2psIpppiiiip2pcpii*//*:RF2*/)=((T6)(1));
/*RF3:copy*/r7copy(((T7*)ms1840_624587783Abc1840A),ms1580_1889925553Abc1580A);
/*:RF3*/if(/*RF8:<*/((int32_t)(/*RF4:argument_count*/r1580argument_count()/*:RF4*/))<(INT32_C(1))/*:RF8*/){
/*RF3:bad_use_exit*/r1661bad_use_exit((T1661*)(/*RF6:system_tools*/r1580system_tools()/*:RF6*/),ms1580_1889925553Abc1580A,ms1580_1464431905Abc1580A);
/*:RF3*/}
_echo_redirect=/*RF4:search_for_echo_redirect_flag*/r1580search_for_echo_redirect_flag(C)/*:RF4*/;
if((_echo_redirect)!=((void*)((void*)0))){
/*RF3:redirect_output_on*/r1674redirect_output_on((T1674*)(/*RF6:echo*/r1580echo()/*:RF6*/),_echo_redirect);
/*:RF3*/}
/*RF3:search_for_verbose_flag*/r1580search_for_verbose_flag();
/*:RF3*//*RF3:search_for_cc_flag*/r1580search_for_cc_flag();
/*:RF3*/if(/*RF4:ace_file_mode*/r1580ace_file_mode(C)/*:RF4*/){
/*RF3:add_smarteiffel_c_mode_options*/r1661add_smarteiffel_c_mode_options((T1661*)(/*RF6:system_tools*/r1580system_tools()/*:RF6*/));
/*:RF3*/}
else{
/*RF3:parse_command_line*/r1580parse_command_line(C,INT32_C(1));
/*:RF3*//*RF3:set_default_level*/r1827set_default_level(((T1827*)oBC1583ace));
/*:RF3*//*RF3:add_smarteiffel_c_mode_options*/r1661add_smarteiffel_c_mode_options((T1661*)(/*RF6:system_tools*/r1580system_tools()/*:RF6*/));
/*:RF3*//*RF3:parse_command_line*/r1580parse_command_line(C,INT32_C(2));
/*:RF3*//*RF3:command_line_parsed*/r1827command_line_parsed(((T1827*)oBC1583ace),ms1580_1889925553Abc1580A);
/*:RF3*/}
/*RF3:prepare_memory*/r1665prepare_memory((T1665*)(/*RF6:cpp*/r1580cpp()/*:RF6*/));
/*:RF3*//*RF3:compile*/r1659compile(((T1659*)oBC1583smart_eiffel),/*RF6:cpp*/r1580cpp()/*:RF6*/);
/*:RF3*//*RF3:disk_save*/r1835disk_save((T1835*)(/*RF6:id_provider*/r1580id_provider()/*:RF6*/));
/*:RF3*//*RF3:echo_information*/r1825echo_information();
/*:RF3*//*RF3:before_exit_close*/r1674before_exit_close((T1674*)(/*RF6:echo*/r1580echo()/*:RF6*/));
/*:RF3*/}/*--*/

/*COMPILE_TO_C*/void r1580parse_command_line(T1580* C,T2 a1){
/*[INTERNAL_C_LOCAL list*/
T6 tmp0;
/*INTERNAL_C_LOCAL list]*/
T2 _argi=0;
T0* _arg=(void*)0;
int _mhf=0;
_argi=INT32_C(1);
while(1){
/*until*/if(/*RF8:>*/((int32_t)(_argi))>(/*RF4:argument_count*/r1580argument_count()/*:RF4*/)/*:RF8*/) break;
_arg=/*RF8:item*/((/*RF2:storage*/((T2573*)(/*RF6:command_arguments*/r1580command_arguments()/*:RF6*/))->_storage/*Tiini*//*:RF2*/))[_argi]/*:RF8*/;
if(/*RF4:is_help_flag*/r1580is_help_flag(C,_arg)/*:RF4*/){
_argi=/*RF8:+*/((int32_t)(_argi))+(INT32_C(1))/*:RF8*/;
}
else{
if(/*RF4:is_relax_flag*/r1580is_relax_flag(_arg)/*:RF4*/){
_argi=/*RF8:+*/((int32_t)(_argi))+(INT32_C(1))/*:RF8*/;
}
else{
if(/*RF4:is_case_insensitive_flag*/r1580is_case_insensitive_flag(_arg)/*:RF4*/){
_argi=/*RF8:+*/((int32_t)(_argi))+(INT32_C(1))/*:RF8*/;
}
else{
if(/*RF4:is_style_warning_flag*/r1580is_style_warning_flag(_arg)/*:RF4*/){
_argi=/*RF8:+*/((int32_t)(_argi))+(INT32_C(1))/*:RF8*/;
}
else{
if(/*RF4:is_no_warning_flag*/r1580is_no_warning_flag(_arg)/*:RF4*/){
_argi=/*RF8:+*/((int32_t)(_argi))+(INT32_C(1))/*:RF8*/;
}
else{
if(/*RF4:is_version_flag*/r1580is_version_flag(C,_arg)/*:RF4*/){
_argi=/*RF8:+*/((int32_t)(_argi))+(INT32_C(1))/*:RF8*/;
}
else{
if(/*RF4:is_verbose_flag*/r1580is_verbose_flag(_arg)/*:RF4*/){
_argi=/*RF8:+*/((int32_t)(_argi))+(INT32_C(1))/*:RF8*/;
}
else{
if(/*RF4:is_a_compilation_level_flag*/r1580is_a_compilation_level_flag(C,_arg)/*:RF4*/){
_argi=/*RF8:+*/((int32_t)(_argi))+(INT32_C(1))/*:RF8*/;
}
else{
if(/*RF4:is_debug_flag*/r1580is_debug_flag(_arg)/*:RF4*/){
_argi=/*RF8:+*/((int32_t)(_argi))+(INT32_C(1))/*:RF8*/;
}
else{
if(/*RF4:is_flat_check_flag*/r1580is_flat_check_flag(_arg)/*:RF4*/){
_argi=/*RF8:+*/((int32_t)(_argi))+(INT32_C(1))/*:RF8*/;
}
else{
if(/*RF4:is_cecil_flag*/r1580is_cecil_flag(C,_arg,_argi)/*:RF4*/){
_argi=/*RF8:+*/((int32_t)(_argi))+(INT32_C(2))/*:RF8*/;
}
else{
if(/*RF4:is_o_flag*/r1580is_o_flag(C,_arg,_argi)/*:RF4*/){
_argi=/*RF8:+*/((int32_t)(_argi))+(INT32_C(2))/*:RF8*/;
}
else{
if(/*RF4:flag_match*/r1580flag_match(ms1586_2141685Abc1586A,_arg)/*:RF4*/){
(/*RF2:no_main*/(((T1827*)oBC1583ace))->_no_main/*p2pipippppppppp3ppiiiippcpii*//*:RF2*/)=((T6)(1));
_argi=/*RF8:+*/((int32_t)(_argi))+(INT32_C(1))/*:RF8*/;
}
else{
if(/*RF4:flag_match*/r1580flag_match(ms1580_85614Abc1580A,_arg)/*:RF4*/){
/*RF3:set_no_gc*/r1841set_no_gc();
/*:RF3*/_argi=/*RF8:+*/((int32_t)(_argi))+(INT32_C(1))/*:RF8*/;
}
else{
if(/*RF4:flag_match*/r1580flag_match(ms1580_386614Abc1580A,_arg)/*:RF4*/){
/*RF3:set_bdw_gc*/r1841set_bdw_gc();
/*:RF3*/_argi=/*RF8:+*/((int32_t)(_argi))+(INT32_C(1))/*:RF8*/;
}
else{
if(/*RF4:flag_match*/r1580flag_match(ms1586_1994621Abc1586A,_arg)/*:RF4*/){
(/*RF2:item*/(((T2577*)oBC1841info))->_item/*p*//*:RF2*/)=((T6)(1));
_argi=/*RF8:+*/((int32_t)(_argi))+(INT32_C(1))/*:RF8*/;
}
else{
if(/*RF4:is_safety_check_flag*/r1580is_safety_check_flag(_arg)/*:RF4*/){
_argi=/*RF8:+*/((int32_t)(_argi))+(INT32_C(1))/*:RF8*/;
}
else{
if(/*RF4:is_manifest_string_trace_flag*/r1580is_manifest_string_trace_flag(_arg)/*:RF4*/){
_argi=/*RF8:+*/((int32_t)(_argi))+(INT32_C(1))/*:RF8*/;
}
else{
if(/*RF4:is_no_rescue_flag*/r1580is_no_rescue_flag(_arg)/*:RF4*/){
_argi=/*RF8:+*/((int32_t)(_argi))+(INT32_C(1))/*:RF8*/;
}
else{
if(/*RF4:flag_match*/r1580flag_match(ms1586_10714862Abc1586A,_arg)/*:RF4*/){
(/*RF2:no_strip*/((T1661*)(/*RF6:system_tools*/r1580system_tools()/*:RF6*/))->_no_strip/*5pp10pipppp2pp7p*//*:RF2*/)=((T6)(1));
_argi=/*RF8:+*/((int32_t)(_argi))+(INT32_C(1))/*:RF8*/;
}
else{
if(/*RF4:flag_match*/r1580flag_match(ms1586_89216Abc1586A,_arg)/*:RF4*/){
_argi=/*RF8:+*/((int32_t)(_argi))+(INT32_C(1))/*:RF8*/;
if(/*RF8:<=*/((int32_t)(_argi))<=(/*RF4:argument_count*/r1580argument_count()/*:RF4*/)/*:RF8*/){
/*RF3:set_split*/r1827set_split(((T1827*)oBC1583ace),/*RF8:item*/((/*RF2:storage*/((T2573*)(/*RF6:command_arguments*/r1580command_arguments()/*:RF6*/))->_storage/*Tiini*//*:RF2*/))[_argi]/*:RF8*/);
/*:RF3*/_argi=/*RF8:+*/((int32_t)(_argi))+(INT32_C(1))/*:RF8*/;
}
else{
/*RF3:w_put_string*/r1674w_put_string((T1674*)(/*RF6:echo*/r1580echo()/*:RF6*/),ms1580_1889925553Abc1580A);
/*:RF3*//*RF3:w_put_string*/r1674w_put_string((T1674*)(/*RF6:echo*/r1580echo()/*:RF6*/),se_ms(40,s1580_425790270A));
/*:RF3*//*RF7:die_with_code*/se_die(INT32_C(1));
/*:RF7*/}
}
else{
if(/*RF4:flag_match*/r1580flag_match(ms1586_10714216Abc1586A,_arg)/*:RF4*/){
/*RF3:set_no_split*/r1827set_no_split(((T1827*)oBC1583ace),(T6)(1));
/*:RF3*/_argi=/*RF8:+*/((int32_t)(_argi))+(INT32_C(1))/*:RF8*/;
}
else{
if(/*RF4:is_trace_flag*/r1580is_trace_flag(_arg)/*:RF4*/){
_argi=/*RF8:+*/((int32_t)(_argi))+(INT32_C(1))/*:RF8*/;
}
else{
if(/*RF4:is_high_memory_compiler*/r1580is_high_memory_compiler(_arg)/*:RF4*/){
_argi=/*RF8:+*/((int32_t)(_argi))+(INT32_C(1))/*:RF8*/;
}
else{
if(/*RF4:is_profile*/r1580is_profile(_arg)/*:RF4*/){
_argi=/*RF8:+*/((int32_t)(_argi))+(INT32_C(1))/*:RF8*/;
}
else{
if(/*RF4:is_output_error_warning_on_flag*/r1580is_output_error_warning_on_flag(C,_arg,_argi)/*:RF4*/){
_argi=/*RF8:+*/((int32_t)(_argi))+(INT32_C(2))/*:RF8*/;
}
else{
if(/*RF4:flag_match*/r1580flag_match(ms1580_1767481079Abc1580A,_arg)/*:RF4*/){
_argi=/*RF8:+*/((int32_t)(_argi))+(INT32_C(1))/*:RF8*/;
if((a1)==(INT8_C(2))){
if(/*RF4:precompile_header_supported*/r1661precompile_header_supported((T1661*)(/*RF6:system_tools*/r1580system_tools()/*:RF6*/))/*:RF4*/){
(/*RF2:precompile_header*/(((T1827*)oBC1583ace))->_precompile_header/*p2pipippppppppp3ppiiiippcpii*//*:RF2*/)=((T6)(1));
}
else{
/*RF3:w_put_string*/r1674w_put_string((T1674*)(/*RF6:echo*/r1580echo()/*:RF6*/),ms1580_1128710280Abc1580A);
/*:RF3*/}
}
}
else{
if(/*RF4:flag_match*/r1580flag_match(ms1586_10554609Abc1586A,_arg)/*:RF4*/){
if((a1)==(INT8_C(1))){
if(/*RF8:<*/((int32_t)(_argi))<(/*RF4:argument_count*/r1580argument_count()/*:RF4*/)/*:RF8*/){
/*RF3:add_loadpath_file*/r1661add_loadpath_file((T1661*)(/*RF6:system_tools*/r1580system_tools()/*:RF6*/),/*RF8:item*/((/*RF2:storage*/((T2573*)(/*RF6:command_arguments*/r1580command_arguments()/*:RF6*/))->_storage/*Tiini*//*:RF2*/))[/*RF8:+*/((int32_t)(_argi))+(INT32_C(1))/*:RF8*/]/*:RF8*/);
/*:RF3*/_argi=/*RF8:+*/((int32_t)(_argi))+(INT32_C(2))/*:RF8*/;
}
else{
/*RF3:w_put_string*/r1674w_put_string((T1674*)(/*RF6:echo*/r1580echo()/*:RF6*/),ms1580_1889925553Abc1580A);
/*:RF3*//*RF3:w_put_string*/r1674w_put_string((T1674*)(/*RF6:echo*/r1580echo()/*:RF6*/),ms1580_1325879523Abc1580A);
/*:RF3*//*RF7:die_with_code*/se_die(INT32_C(1));
/*:RF7*/}
}
else{
_argi=/*RF8:+*/((int32_t)(_argi))+(INT32_C(2))/*:RF8*/;
}
}
else{
if(/*RF4:flag_match*/r1580flag_match(ms1586_385751Abc1586A,_arg)/*:RF4*/){
if((a1)==(INT8_C(1))){
if(/*RF8:<*/((int32_t)(_argi))<(/*RF4:argument_count*/r1580argument_count()/*:RF4*/)/*:RF8*/){
/*RF3:set_alternate_c_mode*/r1661set_alternate_c_mode((T1661*)(/*RF6:system_tools*/r1580system_tools()/*:RF6*/),/*RF8:item*/((/*RF2:storage*/((T2573*)(/*RF6:command_arguments*/r1580command_arguments()/*:RF6*/))->_storage/*Tiini*//*:RF2*/))[/*RF8:+*/((int32_t)(_argi))+(INT32_C(1))/*:RF8*/]/*:RF8*/);
/*:RF3*/_argi=/*RF8:+*/((int32_t)(_argi))+(INT32_C(2))/*:RF8*/;
}
else{
/*RF3:w_put_string*/r1674w_put_string((T1674*)(/*RF6:echo*/r1580echo()/*:RF6*/),ms1580_1889925553Abc1580A);
/*:RF3*//*RF3:w_put_string*/r1674w_put_string((T1674*)(/*RF6:echo*/r1580echo()/*:RF6*/),ms1580_1852009437Abc1580A);
/*:RF3*//*RF7:die_with_code*/se_die(INT32_C(1));
/*:RF7*/}
}
else{
_argi=/*RF8:+*/((int32_t)(_argi))+(INT32_C(2))/*:RF8*/;
}
}
else{
if(/*RF4:flag_match*/r1580flag_match(ms1586_594Abc1586A,_arg)/*:RF4*/){
tmp0/*or else*/=((T6)(/*RF8:<*/((int32_t)(_argi))<(/*RF4:argument_count*/r1580argument_count()/*:RF4*/)/*:RF8*/));
if(tmp0/*or else*/){
}
else{
tmp0/*or else*/=((T6)((a1)!=(INT8_C(1))));
}
if(tmp0/*or else*/){
_argi=/*RF8:+*/((int32_t)(_argi))+(INT32_C(2))/*:RF8*/;
}
else{
/*RF3:w_put_string*/r1674w_put_string((T1674*)(/*RF6:echo*/r1580echo()/*:RF6*/),ms1580_1889925553Abc1580A);
/*:RF3*//*RF3:w_put_string*/r1674w_put_string((T1674*)(/*RF6:echo*/r1580echo()/*:RF6*/),se_ms(40,s1580_24284008A));
/*:RF3*//*RF7:die_with_code*/se_die(INT32_C(1));
/*:RF7*/}
}
else{
if((a1)==(INT8_C(2))){
if(/*RF8:<*/((int32_t)(_argi))<(/*RF4:argument_count*/r1580argument_count()/*:RF4*/)/*:RF8*/){
_argi=/*RF4:extra_arg*/r1661extra_arg((T1661*)(/*RF6:system_tools*/r1580system_tools()/*:RF6*/),_arg,_argi,/*RF8:item*/((/*RF2:storage*/((T2573*)(/*RF6:command_arguments*/r1580command_arguments()/*:RF6*/))->_storage/*Tiini*//*:RF2*/))[/*RF8:+*/((int32_t)(_argi))+(INT32_C(1))/*:RF8*/]/*:RF8*/)/*:RF4*/;
}
else{
_argi=/*RF4:extra_arg*/r1661extra_arg((T1661*)(/*RF6:system_tools*/r1580system_tools()/*:RF6*/),_arg,_argi,(void*)0)/*:RF4*/;
}
}
else{
_argi=/*RF8:+*/((int32_t)(_argi))+(INT32_C(1))/*:RF8*/;
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}/*--*/
T0*oBC1583echo=(void*)0;
int fBC1583echo=0;

/*COMPILE_TO_C*/T0* r1580echo(void){
/*[INTERNAL_C_LOCAL list*/
T0* tmp0;
/*INTERNAL_C_LOCAL list]*/
if(fBC1583echo==0){fBC1583echo=1;{
tmp0/*new*/=/*alloc*/((T0*)(new1674()));
*((T1674*)tmp0/*new*/)=M1674;
/*RF3:make*/r1674make(((T1674*)tmp0/*new*/));
/*:RF3*/oBC1583echo=tmp0/*new*/;
/*tmp0.unlock*/
}}
return oBC1583echo;
}/*--*/

/*COMPILE_TO_C*/T6 r1580is_verbose_flag(T0* a1){
T6 R=0;
if(/*RF4:flag_match*/r1580flag_match(ms1586_2246326Abc1586A,a1)/*:RF4*/){
(/*RF2:is_verbose*/((T1674*)(/*RF6:echo*/r1580echo()/*:RF6*/))->_is_verbose/*3pip*//*:RF2*/)=((T6)(1));
R=((T6)(1));
}
return R;
}/*--*/

/*COMPILE_TO_C*/T0* r1580search_for_echo_redirect_flag(T1580* C){
T0* R=(void*)0;
T2 _argi=0;
T0* _arg=(void*)0;
int _file_tools=0;
_argi=INT32_C(1);
while(1){
/*until*/if((/*RF4:valid_arg_index*/r1580valid_arg_index(_argi)/*:RF4*/)==(0)) break;
_arg=/*RF8:item*/((/*RF2:storage*/((T2573*)(/*RF6:command_arguments*/r1580command_arguments()/*:RF6*/))->_storage/*Tiini*//*:RF2*/))[_argi]/*:RF8*/;
if(/*RF4:is_output_error_warning_on_flag*/r1580is_output_error_warning_on_flag(C,_arg,_argi)/*:RF4*/){
if((R)==((void*)((void*)0))){
R=/*RF8:item*/((/*RF2:storage*/((T2573*)(/*RF6:command_arguments*/r1580command_arguments()/*:RF6*/))->_storage/*Tiini*//*:RF2*/))[/*RF8:+*/((int32_t)(_argi))+(INT32_C(1))/*:RF8*/]/*:RF8*/;
_argi=/*RF8:+*/((int32_t)(_argi))+(INT32_C(2))/*:RF8*/;
if(/*RF4:file_exists*/r1839file_exists(R)/*:RF4*/){
/*RF3:delete*/r1839delete(R);
/*:RF3*/if(/*RF4:file_exists*/r1839file_exists(R)/*:RF4*/){
/*RF3:w_put_string*/r1674w_put_string((T1674*)(/*RF6:echo*/r1580echo()/*:RF6*/),se_ms(36,s1581_1364794873A));
/*:RF3*//*RF3:w_put_string*/r1674w_put_string((T1674*)(/*RF6:echo*/r1580echo()/*:RF6*/),R);
/*:RF3*//*RF3:w_put_string*/r1674w_put_string((T1674*)(/*RF6:echo*/r1580echo()/*:RF6*/),se_ms(54,s1581_525197655A));
/*:RF3*//*RF7:die_with_code*/se_die(INT32_C(1));
/*:RF7*/}
}
}
else{
/*RF3:w_put_string*/r1674w_put_string((T1674*)(/*RF6:echo*/r1580echo()/*:RF6*/),se_ms(75,s1581_1010347497A));
/*:RF3*//*RF3:w_put_string*/r1674w_put_string((T1674*)(/*RF6:echo*/r1580echo()/*:RF6*/),/*RF8:item*/((/*RF2:storage*/((T2573*)(/*RF6:command_arguments*/r1580command_arguments()/*:RF6*/))->_storage/*Tiini*//*:RF2*/))[INT32_C(0)]/*:RF8*/);
/*:RF3*/_argi=INT32_C(1);
while(1){
/*until*/if((/*RF4:valid_arg_index*/r1580valid_arg_index(_argi)/*:RF4*/)==(0)) break;
/*RF3:w_put_character*/r1674w_put_character((T1674*)(/*RF6:echo*/r1580echo()/*:RF6*/),((T3)'\040'));
/*:RF3*//*RF3:w_put_string*/r1674w_put_string((T1674*)(/*RF6:echo*/r1580echo()/*:RF6*/),/*RF8:item*/((/*RF2:storage*/((T2573*)(/*RF6:command_arguments*/r1580command_arguments()/*:RF6*/))->_storage/*Tiini*//*:RF2*/))[_argi]/*:RF8*/);
/*:RF3*/_argi=/*RF8:+*/((int32_t)(_argi))+(INT32_C(1))/*:RF8*/;
}
/*RF3:w_put_character*/r1674w_put_character((T1674*)(/*RF6:echo*/r1580echo()/*:RF6*/),((T3)'\n'));
/*:RF3*//*RF7:die_with_code*/se_die(INT32_C(1));
/*:RF7*/}
}
else{
_argi=/*RF8:+*/((int32_t)(_argi))+(INT32_C(1))/*:RF8*/;
}
}
return R;
}/*--*/
T0*oBC1583string_aliaser=(void*)0;

/*COMPILE_TO_C*/T6 r1580is_help_flag(T1580* C,T0* a1){
/*[INTERNAL_C_LOCAL list*/
T6 tmp0;
T6 tmp1;
T2 tmp2;
/*INTERNAL_C_LOCAL list]*/
T6 R=0;
T6 _echo_verbose_status_save=0;
tmp0/*or else*/=((T6)(/*RF4:flag_match*/r1580flag_match(ms1586_16177Abc1586A,a1)/*:RF4*/));
if(tmp0/*or else*/){
}
else{
tmp0/*or else*/=((T6)(/*RF4:flag_match*/r1580flag_match(ms1581_104Abc1581A,a1)/*:RF4*/));
}
tmp1/*or else*/=((T6)(tmp0/*or else*/));
if(tmp1/*or else*/){
}
else{
tmp1/*or else*/=((T6)(/*RF4:is_equal*/r7is_equal(((T7*)ms1581_63Abc1581A),a1)/*:RF4*/));
}
if(tmp1/*or else*/){
if(((/*RF2:help_flag*/(C)->_help_flag/*ppp*//*:RF2*/))==(0)){
_echo_verbose_status_save=((T6)((/*RF2:is_verbose*/((T1674*)(/*RF6:echo*/r1580echo()/*:RF6*/))->_is_verbose/*3pip*//*:RF2*/)));
(/*RF2:is_verbose*/((T1674*)(/*RF6:echo*/r1580echo()/*:RF6*/))->_is_verbose/*3pip*//*:RF2*/)=((T6)(1));
/*RF3:put_string*/r1674put_string((T1674*)(/*RF6:echo*/r1580echo()/*:RF6*/),ms1580_1464431905Abc1580A);
/*:RF3*/(/*RF2:is_verbose*/((T1674*)(/*RF6:echo*/r1580echo()/*:RF6*/))->_is_verbose/*3pip*//*:RF2*/)=((T6)(_echo_verbose_status_save));
}
tmp2/*inspectExpression*/=/*RF4:argument_count*/r1580argument_count()/*:RF4*/;
/*[inspect*/
switch(tmp2/*inspectExpression*/){
case 1:
/*RF7:die_with_code*/se_die(INT32_C(0));
/*:RF7*/break;
case 2:
if((/*RF2:version_flag*/(C)->_version_flag/*ppp*//*:RF2*/)){
/*RF7:die_with_code*/se_die(INT32_C(0));
/*:RF7*/}
break;
}
/*inspect]*/
/*SFN*/(C->_help_flag/*ppp*/)=((T6)(1));
R=((T6)(1));
}
return R;
}/*--*/

/*COMPILE_TO_C*/T6 r1580is_no_rescue_flag(T0* a1){
T6 R=0;
if(/*RF4:flag_match*/r1580flag_match(ms1581_53561911Abc1581A,a1)/*:RF4*/){
(/*RF2:no_rescue*/((T1652*)(/*RF6:eiffel_parser*/r1580eiffel_parser()/*:RF6*/))->_no_rescue/*pii10pp3ppppp2psIpppiiiip2pcpii*//*:RF2*/)=((T6)(1));
R=((T6)(1));
}
return R;
}/*--*/

/*COMPILE_TO_C*/T6 r1580is_debug_flag(T0* a1){
T6 R=0;
if(/*RF4:flag_match*/r1580flag_match(ms1585_78263Abc1585A,a1)/*:RF4*/){
R=((T6)(1));
/*RF3:set_command_line_debug*/r1827set_command_line_debug(((T1827*)oBC1583ace));
/*:RF3*/}
return R;
}/*--*/
T0*oBC1583ace=(void*)0;

/*COMPILE_TO_C*/T6 r1580is_high_memory_compiler(T0* a1){
T6 R=0;
if(/*RF4:flag_match*/r1580flag_match(ms1586_914215870Abc1586A,a1)/*:RF4*/){
(/*RF2:high_memory_compiler*/(((T1827*)oBC1583ace))->_high_memory_compiler/*p2pipippppppppp3ppiiiippcpii*//*:RF2*/)=((T6)(1));
R=((T6)(1));
}
return R;
}/*--*/

/*COMPILE_TO_C*/T6 r1580is_no_warning_flag(T0* a1){
T6 R=0;
if(/*RF4:flag_match*/r1580flag_match(ms1586_267875778Abc1586A,a1)/*:RF4*/){
R=((T6)(1));
(/*RF2:no_warning*/(((T1837*)oBC1583error_handler))->_no_warning/*pppii*//*:RF2*/)=((T6)(1));
}
return R;
}/*--*/

/*COMPILE_TO_C*/T6 r1580is_safety_check_flag(T0* a1){
T6 R=0;
if(/*RF4:flag_match*/r1580flag_match(ms1586_1777434714Abc1586A,a1)/*:RF4*/){
(/*RF2:safety_check*/(((T1827*)oBC1583ace))->_safety_check/*p2pipippppppppp3ppiiiippcpii*//*:RF2*/)=((T6)(1));
R=((T6)(1));
}
return R;
}/*--*/

/*COMPILE_TO_C*/T6 r1580is_profile(T0* a1){
T6 R=0;
if(/*RF4:flag_match*/r1580flag_match(ms1586_2191641Abc1586A,a1)/*:RF4*/){
(/*RF2:profile*/(((T1827*)oBC1583ace))->_profile/*p2pipippppppppp3ppiiiippcpii*//*:RF2*/)=((T6)(1));
R=((T6)(1));
}
return R;
}/*--*/

/*COMPILE_TO_C*/T6 r1580is_case_insensitive_flag(T0* a1){
T6 R=0;
if(/*RF4:flag_match*/r1580flag_match(ms1586_388005040Abc1586A,a1)/*:RF4*/){
/*RF3:w_put_string*/r1674w_put_string((T1674*)(/*RF6:echo*/r1580echo()/*:RF6*/),ms1580_1889925553Abc1580A);
/*:RF3*//*RF3:w_put_string*/r1674w_put_string((T1674*)(/*RF6:echo*/r1580echo()/*:RF6*/),ms1581_375350487Abc1581A);
/*:RF3*/R=((T6)(1));
}
return R;
}/*--*/

/*COMPILE_TO_C*/T6 r1580is_valid_argument_for_ace_mode(T1580* C,T0* a1){
/*[INTERNAL_C_LOCAL list*/
T6 tmp0;
T6 tmp1;
T6 tmp2;
T6 tmp3;
/*INTERNAL_C_LOCAL list]*/
T6 R=0;
tmp0/*or else*/=((T6)(/*RF4:is_version_flag*/r1580is_version_flag(C,a1)/*:RF4*/));
if(tmp0/*or else*/){
}
else{
tmp0/*or else*/=((T6)(/*RF4:is_style_warning_flag*/r1580is_style_warning_flag(a1)/*:RF4*/));
}
tmp1/*or else*/=((T6)(tmp0/*or else*/));
if(tmp1/*or else*/){
}
else{
tmp1/*or else*/=((T6)(/*RF4:is_no_warning_flag*/r1580is_no_warning_flag(a1)/*:RF4*/));
}
tmp2/*or else*/=((T6)(tmp1/*or else*/));
if(tmp2/*or else*/){
}
else{
tmp2/*or else*/=((T6)(/*RF4:is_verbose_flag*/r1580is_verbose_flag(a1)/*:RF4*/));
}
tmp3/*or else*/=((T6)(tmp2/*or else*/));
if(tmp3/*or else*/){
}
else{
tmp3/*or else*/=((T6)(/*RF4:is_relax_flag*/r1580is_relax_flag(a1)/*:RF4*/));
}
if(tmp3/*or else*/){
R=((T6)(1));
}
return R;
}/*--*/

/*COMPILE_TO_C*/T6 r1580is_manifest_string_trace_flag(T0* a1){
T6 R=0;
if(/*RF4:flag_match*/r1580flag_match(ms1586_234165132Abc1586A,a1)/*:RF4*/){
(/*RF2:manifest_string_trace*/(((T1827*)oBC1583ace))->_manifest_string_trace/*p2pipippppppppp3ppiiiippcpii*//*:RF2*/)=((T6)(1));
R=((T6)(1));
}
return R;
}/*--*/

/*COMPILE_TO_C*/void r1580search_for_cc_flag(void){
T2 _i=0;
T2 _argc=0;
T0* _c_compiler=(void*)0;
_argc=/*RF4:argument_count*/r1580argument_count()/*:RF4*/;
_i=INT32_C(1);
while(1){
/*until*/if(/*RF8:>*/((int32_t)(_i))>(_argc)/*:RF8*/) break;
if(/*RF4:flag_match*/r1580flag_match(ms1586_594Abc1586A,/*RF8:item*/((/*RF2:storage*/((T2573*)(/*RF6:command_arguments*/r1580command_arguments()/*:RF6*/))->_storage/*Tiini*//*:RF2*/))[_i]/*:RF8*/)/*:RF4*/){
if(/*RF8:<*/((int32_t)(_i))<(_argc)/*:RF8*/){
_i=/*RF8:+*/((int32_t)(_i))+(INT32_C(1))/*:RF8*/;
_c_compiler=/*RF8:item*/((/*RF2:storage*/((T2573*)(/*RF6:command_arguments*/r1580command_arguments()/*:RF6*/))->_storage/*Tiini*//*:RF2*/))[_i]/*:RF8*/;
_i=/*RF8:+*/((int32_t)(_argc))+(INT32_C(1))/*:RF8*/;
}
}
_i=/*RF8:+*/((int32_t)(_i))+(INT32_C(1))/*:RF8*/;
}
/*RF3:set_c_compiler*/r1661set_c_compiler((T1661*)(/*RF6:system_tools*/r1580system_tools()/*:RF6*/),_c_compiler);
/*:RF3*/}/*--*/

/*COMPILE_TO_C*/T6 r1580is_a_compilation_level_flag(T1580* C,T0* a1){
T6 R=0;
if(/*RF4:flag_match*/r1580flag_match(ms1585_78591Abc1585A,a1)/*:RF4*/){
R=((T6)(1));
(/*RF2:default_assertion_level*/(((T1827*)oBC1583ace))->_default_assertion_level/*p2pipippppppppp3ppiiiippcpii*//*:RF2*/)=INT32_C(1);
}
else{
if(/*RF4:flag_match*/r1580flag_match(ms1585_10703002Abc1585A,a1)/*:RF4*/){
R=((T6)(1));
(/*RF2:default_assertion_level*/(((T1827*)oBC1583ace))->_default_assertion_level/*p2pipippppppppp3ppiiiippcpii*//*:RF2*/)=INT32_C(2);
}
else{
if(/*RF4:flag_match*/r1580flag_match(ms1585_212160365Abc1585A,a1)/*:RF4*/){
R=((T6)(1));
(/*RF2:default_assertion_level*/(((T1827*)oBC1583ace))->_default_assertion_level/*p2pipippppppppp3ppiiiippcpii*//*:RF2*/)=INT32_C(3);
}
else{
if(/*RF4:flag_match*/r1580flag_match(ms1585_1992063831Abc1585A,a1)/*:RF4*/){
R=((T6)(1));
(/*RF2:default_assertion_level*/(((T1827*)oBC1583ace))->_default_assertion_level/*p2pipippppppppp3ppiiiippcpii*//*:RF2*/)=INT32_C(4);
}
else{
if(/*RF4:flag_match*/r1580flag_match(ms1585_1690381566Abc1585A,a1)/*:RF4*/){
R=((T6)(1));
(/*RF2:default_assertion_level*/(((T1827*)oBC1583ace))->_default_assertion_level/*p2pipippppppppp3ppiiiippcpii*//*:RF2*/)=INT32_C(5);
}
else{
if(/*RF4:flag_match*/r1580flag_match(ms1585_265093627Abc1585A,a1)/*:RF4*/){
R=((T6)(1));
(/*RF2:default_assertion_level*/(((T1827*)oBC1583ace))->_default_assertion_level/*p2pipippppppppp3ppiiiippcpii*//*:RF2*/)=INT32_C(6);
}
else{
if(/*RF4:flag_match*/r1580flag_match(ms1585_48390502Abc1585A,a1)/*:RF4*/){
R=((T6)(1));
(/*RF2:default_assertion_level*/(((T1827*)oBC1583ace))->_default_assertion_level/*p2pipippppppppp3ppiiiippcpii*//*:RF2*/)=INT32_C(7);
}
else{
if(/*RF4:flag_match*/r1580flag_match(ms1585_1223234252Abc1585A,a1)/*:RF4*/){
R=((T6)(1));
/*RF3:set_debug_check*/r1827set_debug_check(((T1827*)oBC1583ace));
/*:RF3*/}
}
}
}
}
}
}
}
if(R){
/*RF3:check_for_level*/r1580check_for_level(C,a1);
/*:RF3*/}
return R;
}/*--*/
T0*oBC1583id_provider=(void*)0;
int fBC1583id_provider=0;

/*COMPILE_TO_C*/T0* r1580id_provider(void){
/*[INTERNAL_C_LOCAL list*/
T0* tmp0;
/*INTERNAL_C_LOCAL list]*/
if(fBC1583id_provider==0){fBC1583id_provider=1;{
tmp0/*new*/=/*alloc*/((T0*)(new1835()));
*((T1835*)tmp0/*new*/)=M1835;
/*RF3:make*/r1835make(((T1835*)tmp0/*new*/));
/*:RF3*/oBC1583id_provider=tmp0/*new*/;
/*tmp0.unlock*/
}}
return oBC1583id_provider;
}/*--*/

/*COMPILE_TO_C*/void r1580search_for_verbose_flag(void){
/*[INTERNAL_C_LOCAL list*/
T6 tmp0;
/*INTERNAL_C_LOCAL list]*/
T2 _argi=0;
T0* _arg=(void*)0;
T6 _found=0;
_argi=INT32_C(1);
while(1){
tmp0/*or else*/=((T6)(_found));
if(tmp0/*or else*/){
}
else{
tmp0/*or else*/=((T6)((/*RF4:valid_arg_index*/r1580valid_arg_index(_argi)/*:RF4*/)==(0)));
}
/*until*/if(tmp0/*or else*/) break;
_arg=/*RF8:item*/((/*RF2:storage*/((T2573*)(/*RF6:command_arguments*/r1580command_arguments()/*:RF6*/))->_storage/*Tiini*//*:RF2*/))[_argi]/*:RF8*/;
if(/*RF4:is_verbose_flag*/r1580is_verbose_flag(_arg)/*:RF4*/){
_found=((T6)(1));
}
else{
_argi=/*RF8:+*/((int32_t)(_argi))+(INT32_C(1))/*:RF8*/;
}
}
/*RF3:put_line*/r1674put_line((T1674*)(/*RF6:echo*/r1580echo()/*:RF6*/),/*RF6:copyright*/r1659copyright(((T1659*)oBC1583smart_eiffel))/*:RF6*/);
/*:RF3*/}/*--*/
T0*oBC1583error_handler=(void*)0;

/*COMPILE_TO_C*/void r1580check_for_level(T1580* C,T0* a1){
if(((/*RF2:level_flag*/(C)->_level_flag/*ppp*//*:RF2*/))!=((void*)((void*)0))){
if((/*RF4:same_as*/r7same_as((T7*)((/*RF2:level_flag*/(C)->_level_flag/*ppp*//*:RF2*/)),a1)/*:RF4*/)==(0)){
/*RF3:w_put_string*/r1674w_put_string((T1674*)(/*RF6:echo*/r1580echo()/*:RF6*/),ms1580_1889925553Abc1580A);
/*:RF3*//*RF3:w_put_string*/r1674w_put_string((T1674*)(/*RF6:echo*/r1580echo()/*:RF6*/),se_ms(26,s1581_199827552A));
/*:RF3*//*RF3:w_put_string*/r1674w_put_string((T1674*)(/*RF6:echo*/r1580echo()/*:RF6*/),(/*RF2:level_flag*/(C)->_level_flag/*ppp*//*:RF2*/));
/*:RF3*//*RF3:w_put_string*/r1674w_put_string((T1674*)(/*RF6:echo*/r1580echo()/*:RF6*/),se_ms(11,s1581_546820847A));
/*:RF3*//*RF3:w_put_string*/r1674w_put_string((T1674*)(/*RF6:echo*/r1580echo()/*:RF6*/),a1);
/*:RF3*//*RF3:w_put_string*/r1674w_put_string((T1674*)(/*RF6:echo*/r1580echo()/*:RF6*/),ms1581_1090Abc1581A);
/*:RF3*//*RF7:die_with_code*/se_die(INT32_C(1));
/*:RF7*/}
}
else{
/*SFN*/(C->_level_flag/*ppp*/)=a1;
}
}/*--*/
int fBC1583set_cecil_pool=0;

/*COMPILE_TO_C*/void r1580set_cecil_pool(void){
if(fBC1583set_cecil_pool==0){fBC1583set_cecil_pool=1;{
(/*RF2:item*/(((T2574*)oBC1583cecil_pool_memory))->_item/*p*//*:RF2*/)=((T0*)create1636());
}}}/*--*/

/*STRING_COMMAND_LINE*/T6 r1840is_profile(T0* a1){
T6 R=0;
if(/*RF4:flag_match*/r1840flag_match(ms1586_2191641Abc1586A,a1)/*:RF4*/){
(/*RF2:profile*/(((T1827*)oBC1583ace))->_profile/*p2pipippppppppp3ppiiiippcpii*//*:RF2*/)=((T6)(1));
R=((T6)(1));
}
return R;
}/*--*/

/*STRING_COMMAND_LINE*/void r1840parse(T0* a1){
T0* _arg=(void*)0;
int _mhf=0;
/*RF3:copy*/r7copy((T7*)(/*RF6:command_line_buffer*/r1840command_line_buffer()/*:RF6*/),a1);
/*:RF3*/while(1){
/*until*/if(((/*RF2:count*/((T7*)(/*RF6:command_line_buffer*/r1840command_line_buffer()/*:RF6*/))->_count/*Tiiiini*//*:RF2*/))==(INT8_C(0))) break;
/*RF3:next_option*/r1840next_option();
/*:RF3*/_arg=/*RF6:option_buffer*/r1840option_buffer()/*:RF6*/;
if(/*RF4:flag_match*/r1840flag_match(ms1580_85614Abc1840A,_arg)/*:RF4*/){
/*RF3:set_no_gc*/r1841set_no_gc();
/*:RF3*/}
else{
if(/*RF4:flag_match*/r1840flag_match(ms1580_386614Abc1840A,_arg)/*:RF4*/){
/*RF3:set_bdw_gc*/r1841set_bdw_gc();
/*:RF3*/}
else{
if(/*RF4:flag_match*/r1840flag_match(ms1586_10714862Abc1586A,_arg)/*:RF4*/){
(/*RF2:no_strip*/((T1661*)(/*RF6:system_tools*/r1840system_tools()/*:RF6*/))->_no_strip/*5pp10pipppp2pp7p*//*:RF2*/)=((T6)(1));
}
else{
if(/*RF4:flag_match*/r1840flag_match(ms1586_10714216Abc1586A,_arg)/*:RF4*/){
/*RF3:set_no_split*/r1827set_no_split(((T1827*)oBC1583ace),(T6)(1));
/*:RF3*/}
else{
if(/*RF4:is_trace_flag*/r1840is_trace_flag(_arg)/*:RF4*/){
}
else{
if(/*RF4:is_profile*/r1840is_profile(_arg)/*:RF4*/){
}
else{
/*RF3:w_put_string*/r1674w_put_string((T1674*)(/*RF6:echo*/r1840echo()/*:RF6*/),ms1840_624587783Abc1840A);
/*:RF3*//*RF3:w_put_string*/r1674w_put_string((T1674*)(/*RF6:echo*/r1840echo()/*:RF6*/),se_ms(22,s1840_1477688005A));
/*:RF3*//*RF3:w_put_string*/r1674w_put_string((T1674*)(/*RF6:echo*/r1840echo()/*:RF6*/),_arg);
/*:RF3*//*RF3:w_put_string*/r1674w_put_string((T1674*)(/*RF6:echo*/r1840echo()/*:RF6*/),se_ms(3,s1581_1090A));
/*:RF3*/}
}
}
}
}
}
}
}/*--*/
T0*oBC1840command_line_buffer=(void*)0;
int fBC1840command_line_buffer=0;

/*STRING_COMMAND_LINE*/T0* r1840command_line_buffer(void){
/*[INTERNAL_C_LOCAL list*/
T0* tmp0;
/*INTERNAL_C_LOCAL list]*/
if(fBC1840command_line_buffer==0){fBC1840command_line_buffer=1;{
tmp0/*new*/=/*alloc*/((T0*)(new7()));
*((T7*)tmp0/*new*/)=M7;
/*RF3:make*/r7make(((T7*)tmp0/*new*/),INT32_C(16));
/*:RF3*/oBC1840command_line_buffer=tmp0/*new*/;
/*tmp0.unlock*/
}}
return oBC1840command_line_buffer;
}/*--*/

/*STRING_COMMAND_LINE*/T6 r1840is_trace_flag(T0* a1){
T6 R=0;
if(/*RF4:flag_match*/r1840flag_match(ms1586_17498Abc1586A,a1)/*:RF4*/){
R=((T6)(1));
}
if(/*RF4:flag_match*/r1840flag_match(ms1585_89771Abc1585A,a1)/*:RF4*/){
/*RF3:w_put_string*/r1674w_put_string((T1674*)(/*RF6:echo*/r1840echo()/*:RF6*/),ms1840_624587783Abc1840A);
/*:RF3*//*RF3:w_put_string*/r1674w_put_string((T1674*)(/*RF6:echo*/r1840echo()/*:RF6*/),ms1581_579450289Abc1581A);
/*:RF3*/R=((T6)(1));
}
if(R){
/*RF3:set_default_trace*/r1827set_default_trace(((T1827*)oBC1583ace));
/*:RF3*/}
return R;
}/*--*/

/*STRING_COMMAND_LINE*/T0* r1840echo(void){
/*[INTERNAL_C_LOCAL list*/
T0* tmp0;
/*INTERNAL_C_LOCAL list]*/
if(fBC1583echo==0){fBC1583echo=1;{
tmp0/*new*/=/*alloc*/((T0*)(new1674()));
*((T1674*)tmp0/*new*/)=M1674;
/*RF3:make*/r1674make(((T1674*)tmp0/*new*/));
/*:RF3*/oBC1583echo=tmp0/*new*/;
/*tmp0.unlock*/
}}
return oBC1583echo;
}/*--*/

/*STRING_COMMAND_LINE*/void r1840next_option(void){
/*[INTERNAL_C_LOCAL list*/
T6 tmp0;
T6 tmp1;
/*INTERNAL_C_LOCAL list]*/
T2 _low=0;
T2 _up=0;
T2 _i=0;
_low=INT32_C(1);
while(1){
tmp0/*or else*/=((T6)(/*RF8:>*/((int32_t)(_low))>((/*RF2:count*/((T7*)(/*RF6:command_line_buffer*/r1840command_line_buffer()/*:RF6*/))->_count/*Tiiiini*//*:RF2*/))/*:RF8*/));
if(tmp0/*or else*/){
}
else{
tmp0/*or else*/=((T6)((/*RF4:is_separator*/r3is_separator(/*RF4:item*/r7item((T7*)(/*RF6:command_line_buffer*/r1840command_line_buffer()/*:RF6*/),_low)/*:RF4*/)/*:RF4*/)==(0)));
}
/*until*/if(tmp0/*or else*/) break;
_low=/*RF8:+*/((int32_t)(_low))+(INT32_C(1))/*:RF8*/;
}
_up=_low;
while(1){
tmp1/*or else*/=((T6)(/*RF8:>*/((int32_t)(_up))>((/*RF2:count*/((T7*)(/*RF6:command_line_buffer*/r1840command_line_buffer()/*:RF6*/))->_count/*Tiiiini*//*:RF2*/))/*:RF8*/));
if(tmp1/*or else*/){
}
else{
tmp1/*or else*/=((T6)(/*RF4:is_separator*/r3is_separator(/*RF4:item*/r7item((T7*)(/*RF6:command_line_buffer*/r1840command_line_buffer()/*:RF6*/),_up)/*:RF4*/)/*:RF4*/));
}
/*until*/if(tmp1/*or else*/) break;
_up=/*RF8:+*/((int32_t)(_up))+(INT32_C(1))/*:RF8*/;
}
/*RF3:clear_count*/r7clear_count((T7*)(/*RF6:option_buffer*/r1840option_buffer()/*:RF6*/));
/*:RF3*/if(/*RF8:>*/((int32_t)(_up))>((/*RF2:count*/((T7*)(/*RF6:command_line_buffer*/r1840command_line_buffer()/*:RF6*/))->_count/*Tiiiini*//*:RF2*/))/*:RF8*/){
_i=_low;
while(1){
/*until*/if(/*RF8:>*/((int32_t)(_i))>((/*RF2:count*/((T7*)(/*RF6:command_line_buffer*/r1840command_line_buffer()/*:RF6*/))->_count/*Tiiiini*//*:RF2*/))/*:RF8*/) break;
/*RF3:extend*/r7extend((T7*)(/*RF6:option_buffer*/r1840option_buffer()/*:RF6*/),/*RF4:item*/r7item((T7*)(/*RF6:command_line_buffer*/r1840command_line_buffer()/*:RF6*/),_i)/*:RF4*/);
/*:RF3*/_i=/*RF8:+*/((int32_t)(_i))+(INT32_C(1))/*:RF8*/;
}
/*RF3:clear_count*/r7clear_count((T7*)(/*RF6:command_line_buffer*/r1840command_line_buffer()/*:RF6*/));
/*:RF3*/}
else{
_i=_low;
while(1){
/*until*/if((_i)==(_up)) break;
/*RF3:extend*/r7extend((T7*)(/*RF6:option_buffer*/r1840option_buffer()/*:RF6*/),/*RF4:item*/r7item((T7*)(/*RF6:command_line_buffer*/r1840command_line_buffer()/*:RF6*/),_i)/*:RF4*/);
/*:RF3*/_i=/*RF8:+*/((int32_t)(_i))+(INT32_C(1))/*:RF8*/;
}
/*RF3:shrink*/r7shrink((T7*)(/*RF6:command_line_buffer*/r1840command_line_buffer()/*:RF6*/),_up,(/*RF2:count*/((T7*)(/*RF6:command_line_buffer*/r1840command_line_buffer()/*:RF6*/))->_count/*Tiiiini*//*:RF2*/));
/*:RF3*/}
}/*--*/
T0*oBC1840option_buffer=(void*)0;
int fBC1840option_buffer=0;

/*STRING_COMMAND_LINE*/T0* r1840option_buffer(void){
/*[INTERNAL_C_LOCAL list*/
T0* tmp0;
/*INTERNAL_C_LOCAL list]*/
if(fBC1840option_buffer==0){fBC1840option_buffer=1;{
tmp0/*new*/=/*alloc*/((T0*)(new7()));
*((T7*)tmp0/*new*/)=M7;
/*RF3:make*/r7make(((T7*)tmp0/*new*/),INT32_C(16));
/*:RF3*/oBC1840option_buffer=tmp0/*new*/;
/*tmp0.unlock*/
}}
return oBC1840option_buffer;
}/*--*/

/*STRING_COMMAND_LINE*/T0* r1840system_tools(void){
/*[INTERNAL_C_LOCAL list*/
T0* tmp0;
/*INTERNAL_C_LOCAL list]*/
if(fBC1583system_tools==0){fBC1583system_tools=1;{
tmp0/*new*/=/*alloc*/((T0*)(new1661()));
*((T1661*)tmp0/*new*/)=M1661;
/*RF3:make*/r1661make(((T1661*)tmp0/*new*/));
/*:RF3*/oBC1583system_tools=tmp0/*new*/;
/*tmp0.unlock*/
}}
return oBC1583system_tools;
}/*--*/

/*STRING_COMMAND_LINE*/T6 r1840flag_match(T0* a1,T0* a2){
/*[INTERNAL_C_LOCAL list*/
T3 tmp0;
T6 tmp1;
T6 tmp2;
T6 tmp3;
/*INTERNAL_C_LOCAL list]*/
T6 R=0;
T2 _i_flag=0;
T2 _i_arg=0;
T3 _flag_char='\0';
T3 _arg_char='\0';
_i_arg=(/*RF2:count*/(((T7*)a2))->_count/*Tiiiini*//*:RF2*/);
if(/*RF8:>=*/((int32_t)(_i_arg))>=(INT32_C(2))/*:RF8*/){
_i_flag=(/*RF2:count*/(((T7*)a1))->_count/*Tiiiini*//*:RF2*/);
tmp0/*inspectExpression*/=/*RF4:first*/r7first(((T7*)a2))/*:RF4*/;
/*[inspect*/
switch(tmp0/*inspectExpression*/){
case 45:
if((/*RF4:item*/r7item(((T7*)a2),INT32_C(2))/*:RF4*/)==(((T3)'\055'))){
R=((T6)((/*RF8:+*/((int32_t)(_i_flag))+(INT32_C(2))/*:RF8*/)==(_i_arg)));
}
else{
R=((T6)((/*RF8:+*/((int32_t)(_i_flag))+(INT32_C(1))/*:RF8*/)==(_i_arg)));
}
break;
case 47:
R=((T6)((/*RF8:+*/((int32_t)(_i_flag))+(INT32_C(1))/*:RF8*/)==(_i_arg)));
break;
}
/*inspect]*/
while(1){
tmp1/*or else*/=((T6)((R)==(0)));
if(tmp1/*or else*/){
}
else{
tmp1/*or else*/=((T6)((_i_flag)==(INT8_C(0))));
}
/*until*/if(tmp1/*or else*/) break;
_flag_char=/*RF4:item*/r7item(((T7*)a1),_i_flag)/*:RF4*/;
_arg_char=/*RF4:item*/r7item(((T7*)a2),_i_arg)/*:RF4*/;
tmp2/*or else*/=((T6)(/*RF4:same_as*/r3same_as(_flag_char,_arg_char)/*:RF4*/));
if(tmp2/*or else*/){
}
else{
tmp3/*and then*/=((T6)((_flag_char)==(((T3)'\137'))));
if(tmp3/*and then*/){
tmp3/*and then*/=((T6)((_arg_char)==(((T3)'\055'))));
}
tmp2/*or else*/=((T6)(tmp3/*and then*/));
}
if(tmp2/*or else*/){
_i_arg=/*RF8:-*/((int32_t)(_i_arg))-(INT32_C(1))/*:RF8*/;
_i_flag=/*RF8:-*/((int32_t)(_i_flag))-(INT32_C(1))/*:RF8*/;
}
else{
R=((T6)(0));
}
}
}
return R;
}/*--*/

#ifdef __cplusplus
}
#endif
