deferred class LIBERTY_AST_EFFECTIVE_TYPE_PARAMETERS_VISITOR

inherit
	VISITOR

feature {LIBERTY_AST_EFFECTIVE_TYPE_PARAMETERS}
	visit_liberty_ast_effective_type_parameters (v: LIBERTY_AST_EFFECTIVE_TYPE_PARAMETERS) is
		deferred
		end

end -- class LIBERTY_AST_EFFECTIVE_TYPE_PARAMETERS_VISITOR
