deferred class LIBERTY_AST_EFFECTIVE_TYPE_PARAMETER_VISITOR

inherit
	VISITOR

feature {LIBERTY_AST_EFFECTIVE_TYPE_PARAMETER}
	visit_liberty_ast_effective_type_parameter (v: LIBERTY_AST_EFFECTIVE_TYPE_PARAMETER) is
		deferred
		end

end -- class LIBERTY_AST_EFFECTIVE_TYPE_PARAMETER_VISITOR
